# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import heapq
import itertools

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for add-two-numbers
_test_lines = [
    'assert is_same_list(candidate(list_node([9, 8, 7]), list_node([1, 2, 3])), list_node([0, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), list_node([5, 6, 4])), list_node([6, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([5, 6, 4])), list_node([6, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 3]), list_node([5, 6, 4, 1])), list_node([7, 0, 8, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5]), list_node([9, 8, 7, 6, 5])), list_node([0, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1]), list_node([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])), list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([5, 5, 5]), list_node([5, 5, 5, 5, 5])), list_node([0, 1, 1, 6, 5]))',
    'assert is_same_list(candidate(list_node([9, 9, 9, 9, 9, 9, 9]), list_node([9, 9, 9, 9])), list_node([8, 9, 9, 9, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), list_node([1])), list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1]), list_node([9, 9])), list_node([0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0]), list_node([9, 9, 9, 9])), list_node([0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([9, 8, 7, 6, 5, 4, 3, 2, 1]), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9])), list_node([0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 8, 9]), list_node([0, 0, 9])), list_node([1, 8, 8, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 3]), list_node([5, 6, 4])), list_node([7, 0, 8]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([5, 6, 4])), list_node([6, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 6]), list_node([1, 3, 5])), list_node([3, 7, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 1, 1]), list_node([9, 9, 9])), list_node([0, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 8]), list_node([0])), list_node([1, 8]))',
    'assert is_same_list(candidate(list_node([1, 8]), list_node([0])), list_node([1, 8]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), list_node([4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5])), list_node([5, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5]))',
    'assert is_same_list(candidate(list_node([1, 8, 9]), list_node([9, 1])), list_node([0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([7, 2, 4, 3]), list_node([5, 6, 4])), list_node([2, 9, 8, 3]))',
    'assert is_same_list(candidate(list_node([1]), list_node([1, 2, 3, 4, 5])), list_node([2, 2, 3, 4, 5]))',
    'assert is_same_list(candidate(list_node([1]), list_node([9, 9, 9, 9, 9, 9, 9, 9, 9])), list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([6, 4, 5]), list_node([0, 4, 5])), list_node([6, 8, 0, 1]))',
    'assert is_same_list(candidate(list_node([5]), list_node([5])), list_node([0, 1]))',
    'assert is_same_list(candidate(list_node([7, 2, 4, 3]), list_node([5, 6, 4, 2])), list_node([2, 9, 8, 5]))',
    'assert is_same_list(candidate(list_node([1, 2]), list_node([3, 4, 5, 6])), list_node([4, 6, 5, 6]))',
    'assert is_same_list(candidate(list_node([9, 9, 9]), list_node([1])), list_node([0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([9, 9]), list_node([1])), list_node([0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1]), list_node([9, 9, 9, 9, 9, 9, 9, 9])), list_node([0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1]), list_node([9])), list_node([0, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3]), list_node([9, 8, 7])), list_node([0, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3]), list_node([7, 8, 9])), list_node([8, 0, 3, 1]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([5, 6, 4])), list_node([6, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), list_node([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])), list_node([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3]), list_node([4, 5, 6])), list_node([5, 7, 9]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5]), list_node([5, 4, 3, 2, 1])), list_node([6, 6, 6, 6, 6]))',
    'assert is_same_list(candidate(list_node([0, 0, 1]), list_node([0, 0, 1])), list_node([0, 0, 2]))',
    'assert is_same_list(candidate(list_node([9, 9]), list_node([1, 1, 1])), list_node([0, 1, 2]))',
    'assert is_same_list(candidate(list_node([6, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([3, 4, 2])), list_node([9, 8, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([9]), list_node([1])), list_node([0, 1]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]), list_node([1])), list_node([2, 0, 0, 0, 0, 0, 0, 0, 0, 0]))',
    'assert is_same_list(candidate(list_node([1, 2, 3]), list_node([4, 5, 6])), list_node([5, 7, 9]))',
    'assert is_same_list(candidate(list_node([1, 8, 9]), list_node([2, 5, 8])), list_node([3, 3, 8, 1]))',
    'assert is_same_list(candidate(list_node([9, 9, 9, 9, 9, 9, 9]), list_node([9, 9, 9, 9])), list_node([8, 9, 9, 9, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([3, 2, 1]), list_node([9, 8, 7])), list_node([2, 1, 9]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([5, 6, 4])), list_node([6, 6, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), list_node([5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6])), list_node([6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5]), list_node([1, 2, 3, 4, 5])), list_node([2, 4, 6, 8, 0, 1]))',
    'assert is_same_list(candidate(list_node([0]), list_node([0])), list_node([0]))',
    'assert is_same_list(candidate(list_node([2, 4, 9]), list_node([5, 6, 4, 9])), list_node([7, 0, 4, 0, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 3]), list_node([5, 6, 4])), list_node([7, 0, 8]))',
    'assert is_same_list(candidate(list_node([2, 4, 3, 2, 5, 5, 5]), list_node([5, 6, 4])), list_node([7, 0, 8, 2, 5, 5, 5]))',
    'assert is_same_list(candidate(list_node([1, 0, 0, 0, 0]), list_node([9, 9, 9, 9, 9])), list_node([0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 6, 8]), list_node([1, 3, 5, 7])), list_node([3, 7, 1, 6, 1]))',
    'assert is_same_list(candidate(list_node([9]), list_node([1, 9, 9, 9, 9, 9, 9, 9, 9, 9])), list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]))',
    'assert is_same_list(candidate(list_node([0, 1]), list_node([0, 1])), list_node([0, 2]))',
    'assert is_same_list(candidate(list_node([7, 1, 6]), list_node([5, 9, 2])), list_node([2, 1, 9]))',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().addTwoNumbers)
