# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for alien-dictionary
_test_lines = [
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'rftt']) == 'wertf'",
    "assert candidate(['abc', 'ab']) == ''",
    "assert candidate(['a', 'b', 'ca', 'cc']) == 'abc'",
    "assert candidate(['a', 'b', 'ca']) == 'abc'",
    "assert candidate(['z', 'x', 'z']) == ''",
    "assert candidate(['z', 'x']) == 'zx'",
    "assert candidate(['ab', 'abc', 'abcd', 'abcde', 'abcdef']) == 'abcdef'",
    "assert candidate(['abcd', 'abdc', 'acbd', 'dacb', 'adcb', 'acdb', 'adbc', 'cabd', 'dcab', 'dbac', 'dcba', 'bdac', 'bcad', 'bcda', 'bacd', 'badc', 'bdca', 'cdab', 'cdba', 'cbad', 'cbda', 'cdba', 'dcba', 'dacb', 'dbca', 'dcab', 'dabc', 'dbac', 'bdac', 'bcad', 'bcda', 'bacd', 'badc', 'bdca']) == ''",
    "assert candidate(['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']) == ''",
    "assert candidate(['apple', 'apply', 'app']) == ''",
    "assert candidate(['apple', 'app', 'banana', 'banaba', 'bat', 'ba', 'cat']) == ''",
    "assert candidate(['f', 'fx', 'fxz', 'fxk', 'fxkq', 'fxks', 'fxksa', 'fxksb', 'fxksc', 'fxkscv', 'fxkscvd', 'fxkscvde', 'fxkscvdef', 'fxkscvdefg', 'fxkscvdefgh', 'fxkscvdefghi', 'fxkscvdefghij', 'fxkscvdefghijk']) == 'adefghijqvxzbskc'",
    "assert candidate(['warpits', 'warpit', 'warp', 'war', 'wa', 'w']) == ''",
    "assert candidate(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['aac', 'a', 'ccc']) == ''",
    "assert candidate(['xyz', 'xya', 'xyb', 'xyy', 'xyz', 'xya', 'xyb', 'xyy']) == ''",
    "assert candidate(['z', 'x', 'y', 'z']) == ''",
    "assert candidate(['xa', 'xb', 'xc', 'xd', 'xe', 'xf', 'xg', 'xh', 'xi', 'xj', 'xk', 'xl', 'xm', 'xn', 'xo', 'xp', 'xq', 'xr', 'xs', 'xt', 'xu', 'xv', 'xw', 'xx', 'xy', 'xz']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['z', 'z', 'z', 'z', 'z', 'z', 'z', 'z', 'z', 'z']) == 'z'",
    "assert candidate(['a', 'ab', 'abc', 'abcd']) == 'abcd'",
    "assert candidate(['a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b']) == ''",
    "assert candidate(['aaa', 'aa', 'a', 'ab']) == ''",
    "assert candidate(['a', 'abc', 'ab', 'abcd']) == ''",
    "assert candidate(['aa', 'b', 'ca', 'cb', 'cc', 'cd']) == 'abcd'",
    "assert candidate(['xyz', 'zyx', 'yxz', 'zxy', 'yzx', 'xzy']) == ''",
    "assert candidate(['abcd', 'dcba']) == 'abcd'",
    "assert candidate(['abc', 'ab', 'abcd']) == ''",
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'rftt', 'te', 'ewq', 'qwe', 'rte', 'tew', 'wet', 'qet', 'e', 't', 'q', 'w', 'r']) == ''",
    "assert candidate(['f', 'f', 'f', 'fb', 'fba', 'fbac', 'fbacd', 'fbad', 'fbadg', 'fbadgc', 'fbadgcd', 'fbadgce', 'fbadgcef', 'fbadgcem', 'fbadgchem', 'fbadgchemk', 'fbadgchemkj', 'fbadgchemkjc', 'fbadgchemkjcb', 'fbadgchemkjcbh']) == 'abcfgjkdmeh'",
    "assert candidate(['a', 'abc', 'ab', 'b']) == ''",
    "assert candidate(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']) == 'a'",
    "assert candidate(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'a']) == ''",
    "assert candidate(['w', 'wa', 'war', 'warm', 'warp', 'warpd', 'warpe', 'wet', 'went', 'wonder', 'worder']) == 'admtwepnor'",
    "assert candidate(['a', 'b', 'c', 'a', 'b', 'c']) == ''",
    "assert candidate(['ba', 'bc', 'ac', 'bb', 'dc']) == ''",
    "assert candidate(['word', 'world', 'row', 'rows', 'worlds', 'wording', 'worldwide', 'wordsworth', 'wordplay', 'worded']) == ''",
    "assert candidate(['zebra', 'dog', 'duck', 'dove']) == ''",
    "assert candidate(['abcd', 'abdc', 'acdb', 'adbc', 'adcb', 'acbd', 'adcb']) == ''",
    "assert candidate(['v', 'w', 'x', 'vwx', 'vwxyz', 'vyz', 'wxz', 'xzz']) == ''",
    "assert candidate(['abcd', 'dcba', 'abcde', 'edcba', 'abcdef', 'fedcba', 'abcdefg', 'gfedcba']) == ''",
    "assert candidate(['xy', 'xz', 'yz', 'yx']) == ''",
    "assert candidate(['abcd', 'abdc', 'acbd', 'dabc']) == 'abcd'",
    "assert candidate(['zyx', 'zyxw', 'zyxz', 'zyxwz']) == ''",
    "assert candidate(['zyx', 'zyxw', 'zyxwa', 'zyxwab', 'zyxwabc']) == 'abcwxyz'",
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'rftt', 'ert', 'erf', 'ertt', 'erftt', 'wrttt', 'wertt', 'wert', 'wertf', 'ertft', 'wertft', 'wetft', 'werft', 'wert', 'wfrt', 'wrt', 'wertf', 'wer', 'we', 'w']) == ''",
    "assert candidate(['zxx', 'zxa', 'zxb', 'zxc']) == 'xzabc'",
    "assert candidate(['zyx', 'zyxw', 'zyxwa', 'zyxwb', 'zyxwc', 'zyxwd', 'zyxwe', 'zyxwf', 'zyxwg', 'zyxwh', 'zyxwi', 'zyxwj', 'zyxwk', 'zyxwl', 'zyxwm', 'zyxwn', 'zyxwo', 'zyxwp', 'zyxwq', 'zyxwr', 'zyxws', 'zyxwt', 'zyxwu', 'zyxwv', 'zyxww', 'zyxwx', 'zyxwy', 'zyxwz']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']) == 'zyxwvutsrqponmlkjihgfedcba'",
    "assert candidate(['a', 'b', 'c', 'ab', 'bc', 'abc']) == ''",
    "assert candidate(['a', 'b', 'bb', 'aaa', 'aaab', 'aaabb', 'aaaab', 'aaaaa', 'aaaaab', 'aaaaabb', 'aaaaaab', 'aaaaaa', 'aaaaaabb', 'aaaaaaab', 'aaaaaaaa', 'aaaaaaaaa', 'aaaaaaaaaa', 'aaaaaaaaaab', 'aaaaaaaaaabb']) == ''",
    "assert candidate(['a', 'b', 'a']) == ''",
    "assert candidate(['w', 'wa', 'war', 'warm', 'warn', 'warp', 'wary', 'way', 'we', 'wee', 'week', 'weir', 'wet', 'wh', 'wha', 'wham', 'whale', 'what', 'wheel', 'when', 'which', 'while', 'whim', 'whip', 'whirl', 'whisk', 'white', 'whiz', 'who', 'whoa', 'whole', 'whom', 'whomp', 'whoo', 'whose', 'why', 'wick', 'wide', 'widely', 'widen', 'widow', 'width', 'wife', 'wig', 'wild', 'wildly', 'will', 'willow', 'wilt', 'win', 'wind', 'window', 'wine', 'wing', 'wink', 'winner', 'winter', 'wipe', 'wire', 'wisdom', 'wise', 'wish', 'wit', 'witch', 'withe', 'with', 'within', 'without', 'witty', 'wizard', 'wolf', 'wonder', 'wont', 'woo', 'wood', 'wooden', 'wool', 'wooly', 'word', 'worded', 'work', 'worker', 'workout', 'worm', 'worn', 'worry', 'worse', 'worst', 'worth', 'would', 'wow', 'wrath', 'wreath', 'wreck', 'wrest', 'wring', 'wrist', 'writer', 'writing', 'writ', 'wrong', 'wrote', 'wrote', 'wsb', 'wtf', 'wu', 'wug', 'wuss']) == ''",
    "assert candidate(['w', 'whv', 'whw', 'wh', 'wv', 'wvw', 'wva', 'wvaq', 'wvav', 'wvaqw', 'wvaqwd', 'wvaqwdx', 'wvaqwdxb', 'wvaqwdxby', 'wvaqwdxbx', 'wvaqwdxbxz']) == ''",
    "assert candidate(['abc', 'ab', 'abcd', 'abca']) == ''",
    "assert candidate(['y', 'x', 'y', 'x', 'z']) == ''",
    "assert candidate(['xyz', 'xya', 'xyb', 'xyc', 'xyd', 'xye']) == 'xyzabcde'",
    "assert candidate(['abcd', 'abce', 'abcf', 'abcg', 'abch', 'abci', 'abcj', 'abck', 'abcl', 'abcm', 'abcn', 'abco', 'abcp', 'abcq', 'abcr', 'abcs', 'abct', 'abcu', 'abcv', 'abcw', 'abcx', 'abcy', 'abcz']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['abc', 'bca', 'cab', 'cba', 'bac', 'acb']) == ''",
    "assert candidate(['ba', 'bc', 'ac', 'cab']) == 'bac'",
    "assert candidate(['apple', 'app']) == ''",
    "assert candidate(['a', 'a', 'a', 'a', 'a', 'a', 'a']) == 'a'",
    "assert candidate(['xyz', 'xyw', 'xyz', 'xyw', 'xy']) == ''",
    "assert candidate(['a', 'abc', 'abca', 'abcab']) == 'abc'",
    "assert candidate(['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']) == 'zyxwvutsrqponmlkjihgfedcba'",
    "assert candidate(['abc', 'acb', 'bac', 'bca', 'cab', 'cba', 'abc', 'acb']) == ''",
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'ref', 'rftt']) == 'wertf'",
    "assert candidate(['w', 'wa', 'war', 'warp', 'warpit', 'warpits']) == 'aiprstw'",
    "assert candidate(['abc', 'acb', 'bac', 'bca', 'cab', 'cba']) == 'abc'",
    "assert candidate(['abc', 'ab', 'a', 'd', 'dc', 'de', 'def', 'abcd']) == ''",
    "assert candidate(['abcd', 'abcde', 'abcdf', 'abcde', 'abce']) == ''",
    "assert candidate(['a', 'b', 'c', 'a', 'b', 'c']) == ''",
    "assert candidate(['xyz', 'xyw', 'xyz', 'xyy']) == ''",
    "assert candidate(['a', 'b', 'c', 'ac', 'bc', 'abc', 'acb', 'bac', 'bca', 'cab', 'cba']) == ''",
    "assert candidate(['hello', 'hell', 'he', 'h']) == ''",
    "assert candidate(['abc', 'ab', 'a', 'abcd', 'abce', 'abcde']) == ''",
    "assert candidate(['hello', 'hell', 'he']) == ''",
    "assert candidate(['qaz', 'wsx', 'edc', 'rfv', 'tgb', 'yhn', 'ujm', 'ikl', 'opa', 'zxc', 'vbn', 'nm', 'lkj', 'ihgf', 'dcba']) == ''",
    "assert candidate(['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg']) == 'abcdefg'",
    "assert candidate(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['abc', 'ab', 'a']) == ''",
    "assert candidate(['zyx', 'zyxw', 'zyxz', 'zyxwv', 'zyxwvu', 'zyxwvut', 'zyxwvuts', 'zyxwvutsr', 'zyxwvutsrq', 'zyxwvutsrqpo']) == ''",
    "assert candidate(['abc', 'abca', 'abcb', 'abcc', 'abcd', 'abce', 'abcf', 'abcg', 'abch', 'abci', 'abcj', 'abck', 'abcl', 'abcm', 'abcn', 'abco', 'abcp', 'abcq', 'abcr', 'abcs', 'abct', 'abcu', 'abcv', 'abcw', 'abcy', 'abcz']) == 'abcdefghijklmnopqrstuvwyz'",
    "assert candidate(['aaa', 'aab', 'aac', 'aad', 'aae', 'aaf', 'aag', 'aah', 'aai', 'aaj', 'aak', 'aal', 'aam', 'aan', 'aao', 'aap', 'aaq', 'aar', 'aas', 'aat', 'aau', 'aav', 'aaw', 'aax', 'aay', 'aaz']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['abc', 'ab', 'b']) == ''",
    "assert candidate(['hello', 'hell', 'hel', 'he', 'h']) == ''",
    "assert candidate(['z', 'z', 'z', 'z', 'z']) == 'z'",
    "assert candidate(['aaaa', 'aaa', 'aa', 'a']) == ''",
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'rftt', 'wrt', 'wrtf', 'wrft', 'wert', 'wertf']) == ''",
    "assert candidate(['xy', 'xz', 'ya', 'yb', 'yc', 'yd', 'ye', 'yf', 'yg', 'yh', 'yi', 'yj', 'yk', 'yl', 'ym', 'yn', 'yo', 'yp', 'yq', 'yr', 'ys', 'yt', 'yu', 'yv', 'yw', 'yx', 'yy', 'yz']) == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate(['apple', 'app', 'application']) == ''",
    "assert candidate(['aa', 'a']) == ''",
    "assert candidate(['w', 'wa', 'wc', 'wb', 'we']) == 'awcbe'",
    "assert candidate(['a', 'b', 'c', 'a', 'b', 'c', 'a']) == ''",
    "assert candidate(['w', 'wh', 'w', 'wa', 'wq', 'wqr', 'wqa', 'wrq', 'wrqa', 'wqa', 'a', 'as', 'an', 'any', 'ant', 'n', 'nt', 'ny', 'ntn']) == ''",
    "assert candidate(['a', 'ba', 'bca', 'bda', 'bdca']) == 'abcd'",
    "assert candidate(['abcd', 'dcba', 'abdc', 'cbad']) == ''",
    "assert candidate(['zyx', 'zyxw', 'z']) == ''",
    "assert candidate(['abc', 'ab', 'a']) == ''",
    "assert candidate(['ac', 'ab', 'zc', 'zb']) == 'aczb'",
    "assert candidate(['a', 'a', 'a', 'a', 'a']) == 'a'",
    "assert candidate(['a', 'z', 'b', 'f', 'd', 'c', 'e', 'g']) == 'azbfdceg'",
    "assert candidate(['a', 'b', 'a', 'b', 'a', 'b']) == ''",
    "assert candidate(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ba', 'bb', 'bc', 'bd', 'be', 'bf', 'bg', 'bh', 'bi', 'bj', 'bk', 'bl', 'bm', 'bn', 'bo', 'bp', 'bq', 'br', 'bs', 'bt', 'bu', 'bv', 'bw', 'bx', 'by', 'bz', 'ca', 'cb', 'cc', 'cd', 'ce', 'cf', 'cg', 'ch', 'ci', 'cj', 'ck', 'cl', 'cm', 'cn', 'co', 'cp', 'cq', 'cr', 'cs', 'ct', 'cu', 'cv', 'cw', 'cx', 'cy', 'cz']) == ''",
    "assert candidate(['abc', 'abcd', 'abdc', 'abd', 'bdc']) == ''",
    "assert candidate(['a', 'b', 'c', 'b', 'a']) == ''",
    "assert candidate(['wrt', 'wrf', 'er', 'ett', 'rftt', 'te']) == 'wertf'",
    "assert candidate(['w', 'wa', 'wba', 'wbac', 'wbad']) == 'acwbd'",
    "assert candidate(['xzy', 'xyz', 'xzyw', 'xy']) == ''",
    "assert candidate(['xyz', 'xy', 'x']) == ''",
    "assert candidate(['dog', 'cat', 'bird']) == 'adgiortcb'",
    "assert candidate(['a', 'ab', 'abc', 'abcd', 'abcde', 'abcdef']) == 'abcdef'",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().alienOrder)
