# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for car-fleet
_test_lines = [
    'assert candidate(target = 1000,position = [100, 200, 300],speed = [100, 50, 25]) == 1',
    'assert candidate(target = 100,position = [0, 1, 2, 3, 4],speed = [100, 100, 100, 100, 100]) == 5',
    'assert candidate(target = 300,position = [0, 50, 100, 150, 200, 250],speed = [50, 40, 30, 20, 10, 5]) == 1',
    'assert candidate(target = 100,position = [90, 80, 70, 60, 50],speed = [10, 20, 30, 40, 50]) == 1',
    'assert candidate(target = 50,position = [0, 10, 20, 30, 40],speed = [10, 9, 8, 7, 6]) == 5',
    'assert candidate(target = 50,position = [10, 20, 30],speed = [1, 2, 3]) == 3',
    'assert candidate(target = 12,position = [10, 8, 0, 5, 3],speed = [2, 4, 1, 1, 3]) == 3',
    'assert candidate(target = 10,position = [3],speed = [3]) == 1',
    'assert candidate(target = 1,position = [0],speed = [1]) == 1',
    'assert candidate(target = 50,position = [10, 20, 30, 40],speed = [5, 4, 3, 2]) == 4',
    'assert candidate(target = 100,position = [0, 2, 4],speed = [4, 2, 1]) == 1',
    'assert candidate(target = 200,position = [50, 60, 70, 80, 90],speed = [10, 9, 8, 7, 6]) == 1',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50, 60, 70, 80, 90],speed = [10, 10, 10, 10, 10, 10, 10, 10, 10]) == 9',
    'assert candidate(target = 20,position = [0, 18, 5],speed = [4, 4, 4]) == 3',
    'assert candidate(target = 20,position = [6, 2, 17],speed = [3, 9, 2]) == 2',
    'assert candidate(target = 1000,position = [100, 200, 300, 400],speed = [10, 20, 30, 40]) == 4',
    'assert candidate(target = 10,position = [6, 8],speed = [3, 2]) == 2',
    'assert candidate(target = 12,position = [0, 4, 2],speed = [1, 2, 3]) == 2',
    'assert candidate(target = 20,position = [5, 15, 10],speed = [5, 1, 3]) == 1',
    'assert candidate(target = 100,position = [10, 20, 30],speed = [1, 2, 3]) == 3',
    'assert candidate(target = 999999,position = [1, 2, 3, 4, 5],speed = [999998, 999997, 999996, 999995, 999994]) == 1',
    'assert candidate(target = 200,position = [10, 50, 90, 130, 170],speed = [1, 2, 3, 4, 5]) == 5',
    'assert candidate(target = 1000,position = [500, 600, 700, 800, 900],speed = [1, 1, 1, 1, 1]) == 5',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50, 60, 70, 80, 90],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9]) == 9',
    'assert candidate(target = 600,position = [50, 150, 250, 350, 450, 550],speed = [5, 10, 15, 20, 25, 30]) == 6',
    'assert candidate(target = 100,position = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],speed = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 10',
    'assert candidate(target = 1000,position = [100, 200, 300, 400, 500],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 120,position = [10, 30, 50, 70, 90],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 100,position = [0, 25, 50, 75, 99],speed = [5, 4, 3, 2, 1]) == 5',
    'assert candidate(target = 1000,position = [900, 800, 700, 600, 500, 400, 300, 200, 100],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9]) == 1',
    'assert candidate(target = 1000,position = [10, 200, 300, 400, 500, 600, 700, 800, 900],speed = [90, 80, 70, 60, 50, 40, 30, 20, 10]) == 2',
    'assert candidate(target = 300,position = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) == 20',
    'assert candidate(target = 250,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150],speed = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 15',
    'assert candidate(target = 1234,position = [123, 456, 789],speed = [321, 654, 987]) == 3',
    'assert candidate(target = 50,position = [10, 20, 30, 40],speed = [1, 1, 1, 1]) == 4',
    'assert candidate(target = 700,position = [10, 100, 200, 300, 400],speed = [5, 15, 25, 35, 45]) == 5',
    'assert candidate(target = 200,position = [50, 100, 150, 0],speed = [2, 2, 2, 1]) == 4',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50, 60, 70, 80, 90],speed = [9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 200,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],speed = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 10',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50],speed = [1, 2, 3, 4, 5]) == 5',
    'assert candidate(target = 300,position = [0, 50, 100, 150, 200, 250],speed = [1, 2, 3, 4, 5, 6]) == 6',
    'assert candidate(target = 120,position = [10, 30, 50, 70, 90],speed = [10, 8, 6, 4, 2]) == 1',
    'assert candidate(target = 120,position = [10, 15, 20, 25, 30, 35, 40, 45, 50, 55],speed = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) == 10',
    'assert candidate(target = 10000,position = [9990, 9980, 9970, 9960, 9950, 9940, 9930, 9920, 9910, 9900],speed = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) == 10',
    'assert candidate(target = 500,position = [490, 480, 470, 460, 450],speed = [10, 10, 10, 10, 10]) == 5',
    'assert candidate(target = 200,position = [0, 50, 100, 150],speed = [20, 15, 10, 5]) == 1',
    'assert candidate(target = 100,position = [5, 15, 25, 35, 45],speed = [2, 4, 6, 8, 10]) == 5',
    'assert candidate(target = 150,position = [0, 25, 50, 75, 100],speed = [5, 10, 15, 20, 25]) == 5',
    'assert candidate(target = 150,position = [10, 20, 30, 40, 50, 60],speed = [6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 100,position = [90, 80, 70, 60, 50],speed = [10, 10, 10, 10, 10]) == 5',
    'assert candidate(target = 120,position = [0, 10, 20, 30, 40, 50],speed = [1, 2, 3, 4, 5, 6]) == 6',
    'assert candidate(target = 2000,position = [500, 1000, 1500],speed = [1, 1, 1]) == 3',
    'assert candidate(target = 600,position = [0, 150, 300, 450],speed = [600, 300, 150, 100]) == 2',
    'assert candidate(target = 1000,position = [100, 200, 300, 400],speed = [10, 20, 30, 40]) == 4',
    'assert candidate(target = 400,position = [20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380],speed = [20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 19',
    'assert candidate(target = 120,position = [10, 20, 30, 40, 50, 60],speed = [10, 9, 8, 7, 6, 5]) == 1',
    'assert candidate(target = 800,position = [10, 30, 50, 70, 90],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 750,position = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700],speed = [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 1000,position = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900],speed = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 400,position = [10, 30, 50, 70, 90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290, 310, 330, 350, 370, 390],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) == 20',
    'assert candidate(target = 500,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],speed = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 10',
    'assert candidate(target = 1000,position = [990, 980, 970, 960, 950, 940, 930, 920, 910],speed = [10, 10, 10, 10, 10, 10, 10, 10, 10]) == 9',
    'assert candidate(target = 150,position = [5, 10, 20, 30, 40, 50, 60, 70, 80, 90],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 10',
    'assert candidate(target = 200,position = [10, 50, 90, 130, 170],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 800,position = [100, 200, 300, 400, 500, 600, 700],speed = [1, 2, 3, 4, 5, 6, 7]) == 7',
    'assert candidate(target = 500,position = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450],speed = [50, 45, 40, 35, 30, 25, 20, 15, 10, 5]) == 1',
    'assert candidate(target = 1000,position = [10, 50, 90, 130, 170],speed = [10, 10, 10, 10, 10]) == 5',
    'assert candidate(target = 250,position = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125],speed = [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 2000,position = [1900, 1800, 1700, 1600, 1500, 1400, 1300, 1200, 1100, 1000],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 1',
    'assert candidate(target = 1000,position = [0, 250, 500, 750],speed = [50, 100, 150, 200]) == 4',
    'assert candidate(target = 3000,position = [100, 300, 500, 700, 900, 1100, 1300, 1500, 1700, 1900],speed = [10, 15, 20, 25, 30, 35, 40, 45, 50, 55]) == 10',
    'assert candidate(target = 150,position = [10, 20, 30, 40, 50],speed = [5, 5, 5, 5, 5]) == 5',
    'assert candidate(target = 5000,position = [10, 200, 3000, 4000, 4990],speed = [100, 90, 80, 70, 60]) == 4',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50],speed = [10, 9, 8, 7, 6]) == 5',
    'assert candidate(target = 1500,position = [100, 300, 500, 700, 900],speed = [100, 200, 300, 400, 500]) == 5',
    'assert candidate(target = 600,position = [590, 580, 570, 560, 550],speed = [1, 1, 1, 1, 1]) == 5',
    'assert candidate(target = 120,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],speed = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 600,position = [30, 150, 270, 390, 510],speed = [5, 10, 15, 20, 25]) == 5',
    'assert candidate(target = 400,position = [100, 200, 300],speed = [1, 1, 1]) == 3',
    'assert candidate(target = 300,position = [290, 280, 270, 260, 250],speed = [1, 2, 3, 4, 5]) == 1',
    'assert candidate(target = 200,position = [10, 30, 50, 70, 90],speed = [50, 40, 30, 20, 10]) == 1',
    'assert candidate(target = 350,position = [50, 100, 150, 200, 250, 300],speed = [10, 20, 30, 40, 50, 60]) == 6',
    'assert candidate(target = 150,position = [10, 30, 50, 70, 90, 110, 130],speed = [10, 8, 6, 4, 2, 1, 5]) == 2',
    'assert candidate(target = 200,position = [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],speed = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 900,position = [10, 100, 200, 300, 400, 500, 600, 700, 800],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9]) == 9',
    'assert candidate(target = 500,position = [0, 100, 200, 300, 400],speed = [1, 2, 3, 4, 5]) == 5',
    'assert candidate(target = 500,position = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) == 15',
    'assert candidate(target = 300,position = [20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280],speed = [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 300,position = [0, 100, 200],speed = [100, 50, 1]) == 1',
    'assert candidate(target = 1200,position = [900, 600, 300, 0],speed = [10, 20, 30, 40]) == 1',
    'assert candidate(target = 10000,position = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],speed = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]) == 10',
    'assert candidate(target = 800,position = [100, 200, 300, 400, 500, 600, 700],speed = [700, 600, 500, 400, 300, 200, 100]) == 1',
    'assert candidate(target = 500,position = [100, 200, 300, 400],speed = [100, 100, 100, 100]) == 4',
    'assert candidate(target = 900,position = [800, 700, 600, 500, 400, 300, 200, 100, 0],speed = [5, 10, 15, 20, 25, 30, 35, 40, 45]) == 1',
    'assert candidate(target = 1000,position = [50, 250, 450, 650, 850],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 500,position = [100, 150, 200, 250, 300],speed = [5, 10, 15, 20, 25]) == 5',
    'assert candidate(target = 1000,position = [500, 600, 700, 800, 900],speed = [100, 200, 300, 400, 500]) == 5',
    'assert candidate(target = 500,position = [10, 100, 200, 300, 400],speed = [1, 2, 3, 4, 5]) == 5',
    'assert candidate(target = 550,position = [25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400, 425, 450, 475, 500, 525, 550],speed = [22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 21',
    'assert candidate(target = 300,position = [10, 50, 90, 130, 170, 210, 250, 290],speed = [1, 2, 3, 4, 5, 6, 7, 8]) == 8',
    'assert candidate(target = 500,position = [400, 300, 200, 100, 0],speed = [5, 4, 3, 2, 1]) == 5',
    'assert candidate(target = 300,position = [25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275],speed = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 1]) == 2',
    'assert candidate(target = 500,position = [0, 100, 200, 300, 400],speed = [100, 100, 100, 100, 100]) == 5',
    'assert candidate(target = 200,position = [50, 100, 150],speed = [1, 2, 3]) == 3',
    'assert candidate(target = 800,position = [10, 100, 200, 300, 400, 500, 600, 700],speed = [1, 2, 3, 4, 5, 6, 7, 8]) == 8',
    'assert candidate(target = 1000,position = [50, 150, 250, 350, 450],speed = [100, 200, 300, 400, 500]) == 5',
    'assert candidate(target = 1000,position = [50, 150, 250, 350, 450, 550, 650, 750, 850, 950],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 10',
    'assert candidate(target = 1500,position = [0, 150, 300, 450, 600, 750, 900, 1050, 1200, 1350],speed = [1, 1, 1, 1, 1, 1, 1, 1, 1, 10]) == 10',
    'assert candidate(target = 200,position = [0, 20, 40, 60, 80, 100, 120, 140, 160, 180],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 10',
    'assert candidate(target = 200,position = [10, 40, 70, 100],speed = [10, 5, 20, 15]) == 2',
    'assert candidate(target = 300,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 10',
    'assert candidate(target = 1000,position = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150],speed = [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 300,position = [25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275],speed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) == 11',
    'assert candidate(target = 2000,position = [1000, 1500],speed = [500, 250]) == 1',
    'assert candidate(target = 1000,position = [100, 200, 300, 400, 500, 600, 700, 800, 900],speed = [9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate(target = 500,position = [50, 150, 250, 350, 450],speed = [5, 10, 15, 20, 25]) == 5',
    'assert candidate(target = 700,position = [100, 200, 300, 400, 500, 600],speed = [100, 90, 80, 70, 60, 50]) == 6',
    'assert candidate(target = 200,position = [10, 50, 90, 130, 170],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 100,position = [10, 20, 30, 40, 50],speed = [5, 5, 5, 5, 5]) == 5',
    'assert candidate(target = 200,position = [10, 20, 30, 40, 50],speed = [1, 1, 1, 1, 1]) == 5',
    'assert candidate(target = 500,position = [10, 50, 90, 130, 170],speed = [10, 20, 30, 40, 50]) == 5',
    'assert candidate(target = 1000,position = [990, 980, 970, 960, 950],speed = [1, 2, 3, 4, 5]) == 1',
    'assert candidate(target = 1000,position = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500],speed = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) == 10',
    'assert candidate(target = 1000,position = [200, 400, 600, 800],speed = [50, 40, 30, 20]) == 4',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().carFleet)
