# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for coin-change-ii
_test_lines = [
    'assert candidate(20, [1, 5, 10]) == 9',
    'assert candidate(1, [1]) == 1',
    'assert candidate(0, [1, 2, 5]) == 1',
    'assert candidate(5000, [1, 5, 10, 25, 50]) == 432699251',
    'assert candidate(100, [3, 7, 40, 9]) == 48',
    'assert candidate(6249, [186, 419, 83, 408]) == 19',
    'assert candidate(15, [1, 3, 5, 7]) == 19',
    'assert candidate(10, [1, 3, 4, 5]) == 12',
    'assert candidate(10, [10]) == 1',
    'assert candidate(50, [1, 18, 27, 34, 50]) == 7',
    'assert candidate(5000, [3, 5, 7, 8, 9, 10]) == 351757492460',
    'assert candidate(100, [3, 6, 9]) == 0',
    'assert candidate(3, [2]) == 0',
    'assert candidate(25, [1, 2, 5]) == 42',
    'assert candidate(5, [1, 2, 5]) == 4',
    'assert candidate(100, [1, 2, 5, 10, 20, 50]) == 4562',
    'assert candidate(1000, [3, 5, 7, 8, 9, 10, 11]) == 1952879228',
    'assert candidate(3000, [4, 12, 23, 34, 51]) == 1913606',
    'assert candidate(1800, [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]) == 120836624716',
    'assert candidate(3500, [50, 100, 150, 200, 250, 300, 350]) == 94425',
    'assert candidate(2500, [11, 22, 33, 44, 55, 66, 77, 88, 99]) == 0',
    'assert candidate(2500, [13, 17, 19, 23, 29, 31]) == 10673219',
    'assert candidate(4500, [23, 47, 61, 83, 97, 101]) == 358270',
    'assert candidate(4200, [11, 22, 33, 44, 55, 66, 77, 88, 99]) == 0',
    'assert candidate(4000, [3, 9, 18, 36, 72, 144]) == 0',
    'assert candidate(8000, [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]) == 0',
    'assert candidate(3333, [3, 6, 9, 12, 15, 18, 21, 24, 27]) == 186150339220814',
    'assert candidate(1200, [2, 5, 10, 25, 50, 100]) == 2459925',
    'assert candidate(4500, [11, 22, 33, 44, 55]) == 0',
    'assert candidate(2000, [11, 17, 29, 31]) == 8465',
    'assert candidate(3000, [4, 9, 15, 25, 30, 50, 75]) == 816870821',
    'assert candidate(3750, [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]) == 6877248457909551',
    'assert candidate(4800, [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]) == 402020904793077',
    'assert candidate(3500, [1, 2, 5, 10, 20, 50, 100]) == 298945088016',
    'assert candidate(10000, [2, 3, 5, 7, 11, 13, 17, 19, 23]) == 11569288968418829417',
    'assert candidate(3750, [125, 250, 500, 1000, 2000]) == 166',
    'assert candidate(2750, [4, 9, 14, 19, 24, 29, 34, 39, 44, 49]) == 1980385268761',
    'assert candidate(6000, [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]) == 1608946754650872',
    'assert candidate(4500, [2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000]) == 17776167706',
    'assert candidate(4500, [5, 10, 20, 50, 100, 200]) == 94862488',
    'assert candidate(6000, [11, 22, 33, 44, 55, 66]) == 0',
    'assert candidate(5555, [7, 14, 21, 28, 35, 42, 49, 56, 63]) == 0',
    'assert candidate(2048, [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]) == 2320518947',
    'assert candidate(4000, [1, 11, 13, 19, 21, 31, 37]) == 95941704933',
    'assert candidate(2700, [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]) == 385226325096527',
    'assert candidate(4999, [1, 2, 5, 10, 25, 50, 100, 200, 500]) == 14978475244405',
    'assert candidate(700, [3, 7, 11, 13, 17, 19, 23, 29]) == 45005473',
    'assert candidate(4500, [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]) == 171076578684392',
    'assert candidate(2500, [2, 3, 5, 7, 11, 13]) == 28227697415',
    'assert candidate(500, [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]) == 0',
    'assert candidate(3500, [7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]) == 1916917910649679',
    'assert candidate(500, [11, 22, 33, 44, 55]) == 0',
    'assert candidate(8000, [1, 2, 5, 10, 20, 50, 100]) == 39042657518121',
    'assert candidate(1500, [3, 5, 7, 11, 13, 17, 19, 23]) == 38017360391',
    'assert candidate(3500, [17, 23, 29, 31, 37]) == 519429',
    'assert candidate(2700, [3, 6, 9, 12, 15, 18, 21, 24, 27]) == 35818551286815',
    'assert candidate(1500, [50, 200, 500, 1000]) == 22',
    'assert candidate(500, [11, 19, 29, 37, 47, 59, 71, 83]) == 3292',
    'assert candidate(2000, [1, 3, 7, 11]) == 5867703',
    'assert candidate(3000, [15, 25, 35, 45, 55]) == 582580',
    'assert candidate(5000, [1, 4, 9, 16, 25, 36, 49]) == 928443384056',
    'assert candidate(2500, [7, 17, 27, 37, 47, 57, 67, 77]) == 115681732',
    'assert candidate(2000, [1, 3, 4, 12, 24, 48]) == 1799991438',
    'assert candidate(3000, [2, 5, 10, 20, 50, 100]) == 238303231',
    'assert candidate(5000, [20, 25, 50, 100, 200, 500]) == 831886',
    'assert candidate(4000, [2, 4, 6, 8, 10, 12, 14, 16, 18]) == 19131722793601739',
    'assert candidate(3000, [33, 66, 99, 132, 165, 198, 231, 264, 297]) == 0',
    'assert candidate(2222, [2, 4, 6, 8, 10, 12, 14, 16, 18]) == 186150339220814',
    'assert candidate(200, [1, 3, 5, 7, 9]) == 89740',
    'assert candidate(4567, [2, 5, 10, 20, 50]) == 188174063',
    'assert candidate(800, [10, 20, 50, 100, 200, 500]) == 2064',
    'assert candidate(3333, [13, 23, 33, 43, 53, 63, 73, 83, 93, 103]) == 3570286683',
    'assert candidate(2000, [10, 25, 50, 100, 200, 500]) == 29674',
    'assert candidate(1500, [5, 11, 17, 23, 29]) == 378081',
    'assert candidate(6000, [1, 2, 3, 5, 11, 23, 37, 41]) == 5179949524521356',
    'assert candidate(3000, [1, 10, 25, 50, 100, 200]) == 11051256',
    'assert candidate(4999, [1, 3, 9, 27, 81, 243, 729, 2187, 6561]) == 3946672836',
    'assert candidate(1200, [4, 8, 15, 16, 23, 42]) == 3481694',
    'assert candidate(999, [1, 4, 9, 16, 25, 36, 49, 64, 81]) == 528165615',
    'assert candidate(1111, [1, 4, 9, 16, 25, 36, 49, 64, 81]) == 1122054398',
    'assert candidate(6666, [1, 2, 3, 5, 8, 13, 21, 34, 55]) == 858790214643388609',
    'assert candidate(4000, [3, 5, 7, 9, 11, 13, 15]) == 2941614132296',
    'assert candidate(1234, [13, 21, 34, 55, 89, 144, 233, 377, 610, 987]) == 10948',
    'assert candidate(3500, [1, 2, 4, 8, 16, 32, 64]) == 1356535733168',
    'assert candidate(1500, [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]) == 23221589514',
    'assert candidate(1200, [5, 15, 25, 50, 100, 200]) == 115862',
    'assert candidate(3000, [1, 3, 4, 10, 20, 50]) == 18144427661',
    'assert candidate(3000, [2, 5, 11, 23, 47]) == 30080239',
    'assert candidate(3456, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]) == 35362292367933393',
    'assert candidate(800, [5, 10, 20, 50, 100, 200]) == 38835',
    'assert candidate(1234, [1, 2, 5, 10, 20, 50, 100]) == 754797589',
    'assert candidate(4000, [11, 22, 33, 44, 55]) == 0',
    'assert candidate(2000, [7, 11, 13, 17, 19, 23]) == 40067247',
    'assert candidate(1800, [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]) == 1067122993784732',
    'assert candidate(7000, [1, 5, 10, 25, 50, 100, 200, 500]) == 399576201827',
    'assert candidate(4000, [8, 16, 24, 32, 40, 48, 56]) == 5078412464',
    'assert candidate(1500, [2, 5, 11, 25, 40, 60]) == 12079534',
    'assert candidate(1800, [2, 6, 12, 18, 24, 30]) == 192387751',
    'assert candidate(1500, [7, 11, 13, 17, 19]) == 712518',
    'assert candidate(3500, [5, 15, 25, 35, 45, 55, 65, 75]) == 10998232465',
    'assert candidate(1234, [3, 5, 7, 11, 13, 17, 19]) == 1209189166',
    'assert candidate(750, [7, 14, 21, 28, 35, 42]) == 0',
    'assert candidate(2000, [1, 3, 5, 7, 9, 11, 13]) == 707531982781',
    'assert candidate(4000, [5, 11, 17, 23, 29, 35, 41, 47, 53, 59]) == 7799502297011',
    'assert candidate(4000, [5, 10, 25, 50, 100]) == 9370181',
    'assert candidate(1800, [15, 25, 35, 45, 55, 65, 75, 85, 95, 105]) == 79077323',
    'assert candidate(7777, [13, 26, 39, 52, 65, 78, 91, 104, 117]) == 0',
    'assert candidate(9000, [15, 25, 35, 45, 55, 65]) == 1244874855',
    'assert candidate(4000, [7, 14, 21, 28, 35]) == 0',
    'assert candidate(4321, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) == 8412107116918783059141522248',
    'assert candidate(2000, [101, 103, 107, 109]) == 0',
    'assert candidate(2500, [2, 5, 11, 17, 23, 29, 35, 41, 47]) == 623719935720',
    'assert candidate(500, [1, 2, 5, 10, 20, 50, 100]) == 5824071',
    'assert candidate(5000, [1, 2, 5, 10, 20, 50, 100, 200, 500]) == 18682149631801',
    'assert candidate(2000, [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]) == 264830889564',
    'assert candidate(4500, [7, 13, 19, 23, 37, 41]) == 275308289',
    'assert candidate(8888, [11, 22, 33, 44, 55, 66, 77, 88, 99]) == 15453068500547',
    'assert candidate(1500, [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]) == 0',
    'assert candidate(7000, [3, 5, 7, 11, 13, 17, 19]) == 34788754338474',
    'assert candidate(3000, [1, 3, 5, 10, 25, 50]) == 11669586691',
    'assert candidate(1999, [111, 222, 333, 444, 555, 666, 777, 888]) == 0',
    'assert candidate(999, [1, 2, 4, 8, 16, 32, 64]) == 944362512',
    'assert candidate(6000, [3, 6, 12, 24, 48, 96]) == 8807842176',
    'assert candidate(5000, [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]) == 1027087367648016934506457070508',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().change)
