# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for coin-change
_test_lines = [
    'assert candidate([186, 419, 83, 408], 6249) == 20',
    'assert candidate([3, 7, 405, 436], 8839) == 25',
    'assert candidate([3, 7, 405], 8839) == 71',
    'assert candidate([2, 5, 10, 1], 27) == 4',
    'assert candidate([1, 2, 5], 1) == 1',
    'assert candidate([1, 3, 4, 5], 7) == 2',
    'assert candidate([1], 0) == 0',
    'assert candidate([5, 7, 8], 100) == 13',
    'assert candidate([1, 3, 4], 6) == 2',
    'assert candidate([4, 2, 1], 11) == 4',
    'assert candidate([1, 3, 4], 6) == 2',
    'assert candidate([1, 2, 5], 11) == 3',
    'assert candidate([1, 2, 5], 0) == 0',
    'assert candidate([2], 3) == -1',
    'assert candidate([70, 171, 358, 439, 286], 9963) == 27',
    'assert candidate([3, 7, 405, 88, 43], 6803) == 24',
    'assert candidate([5, 7], 15) == 3',
    'assert candidate([18, 27, 41], 987) == 26',
    'assert candidate([1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048], 4095) == 12',
    'assert candidate([5, 15, 25, 50], 3000) == 60',
    'assert candidate([1, 2, 4, 8, 16], 2048) == 128',
    'assert candidate([10, 20, 30, 40, 50, 60], 1234) == -1',
    'assert candidate([3, 5, 7, 9, 11], 9876) == 898',
    'assert candidate([18, 24, 28], 100) == 4',
    'assert candidate([17, 29, 31, 37, 41, 43], 5000) == 118',
    'assert candidate([3, 5], 11) == 3',
    'assert candidate([17, 29, 41, 53, 65], 8300) == 136',
    'assert candidate([11, 22, 33, 44, 55], 6600) == 120',
    'assert candidate([34, 7, 23, 32, 5, 62], 9999) == 164',
    'assert candidate([1, 5, 25, 50], 9999) == 208',
    'assert candidate([2, 3, 7, 10], 500) == 50',
    'assert candidate([7, 14, 21, 28, 35, 42, 49, 56], 1000) == -1',
    'assert candidate([3, 6, 9, 12, 15], 1000) == -1',
    'assert candidate([1, 5, 10, 25, 50], 78) == 5',
    'assert candidate([10, 20, 30, 40, 50], 9999) == -1',
    'assert candidate([1, 7, 11], 100) == 10',
    'assert candidate([2, 3, 6, 12, 24, 48], 500) == 13',
    'assert candidate([1, 2, 4, 8, 16, 32, 64], 1023) == 21',
    'assert candidate([1], 10000) == 10000',
    'assert candidate([7, 14, 30, 50, 80], 287) == 6',
    'assert candidate([2, 4, 8, 16, 32, 64, 128], 1023) == -1',
    'assert candidate([1, 2, 5, 10, 20, 50, 100, 200], 10002) == 51',
    'assert candidate([2, 3, 5, 7, 11, 13], 5000) == 386',
    'assert candidate([3, 5, 7, 9, 11], 10000) == 910',
    'assert candidate([7], 100) == -1',
    'assert candidate([1, 5, 10, 25, 50, 100], 99999) == 1007',
    'assert candidate([1, 2, 3, 5, 10], 5000) == 500',
    'assert candidate([3, 6, 9, 12, 15], 444) == 30',
    'assert candidate([3, 5, 7, 11, 13], 997) == 77',
    'assert candidate([1, 3, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31], 100) == 4',
    'assert candidate([7, 15, 23, 31], 750) == 26',
    'assert candidate([23, 14, 5, 12], 5000) == 220',
    'assert candidate([11, 23, 37, 41, 43, 47, 53], 12345) == 235',
    'assert candidate([1, 5, 10, 25, 50, 100], 357) == 7',
    'assert candidate([18, 24, 27, 36, 50], 999) == 21',
    'assert candidate([1, 5, 10, 25, 50], 9999) == 206',
    'assert candidate([1, 2, 5, 10, 20, 50, 100, 200], 9999) == 56',
    'assert candidate([2, 5, 10, 25], 100) == 4',
    'assert candidate([1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048], 1048575) == 522',
    'assert candidate([7, 15, 23, 42], 999) == 27',
    'assert candidate([7, 17, 23, 29, 31], 1000) == 34',
    'assert candidate([1, 3, 4, 6, 8, 10], 450) == 45',
    'assert candidate([1, 5, 10, 20, 50, 100], 10001) == 101',
    'assert candidate([2, 3, 7], 100) == 15',
    'assert candidate([5, 11, 23, 37, 41, 43, 61, 71, 73, 79, 83, 89], 999) == 13',
    'assert candidate([1, 10, 100, 1000], 9999) == 36',
    'assert candidate([1, 10, 25, 50, 100], 12345) == 126',
    'assert candidate([186, 419, 83, 408], 6249) == 20',
    'assert candidate([2, 3, 7], 27) == 5',
    'assert candidate([3, 6, 9, 12, 15], 9000) == 600',
    'assert candidate([1, 2, 5, 10, 20, 50, 100], 9999) == 105',
    'assert candidate([5, 9, 12, 27, 31], 1276) == 42',
    'assert candidate([2, 3, 7, 11, 19, 23], 987) == 44',
    'assert candidate([10, 25, 50, 100], 9876) == -1',
    'assert candidate([2, 6, 10, 14], 9999) == -1',
    'assert candidate([10, 22, 35], 1000) == 30',
    'assert candidate([2, 5, 11, 17, 23], 1000) == 44',
    'assert candidate([23, 37, 41, 53, 67, 71], 8675309) == 122189',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 12) == 12',
    'assert candidate([1, 6, 10], 111) == 12',
    'assert candidate([7, 14, 33, 19, 100], 12345) == 126',
    'assert candidate([13, 21, 34, 55, 89, 144], 6765) == 51',
    'assert candidate([1, 2, 5, 10], 27) == 4',
    'assert candidate([2, 3, 5, 7, 11, 13, 17, 19, 23, 29], 8000) == 277',
    'assert candidate([1, 5, 10, 25], 99) == 9',
    'assert candidate([1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048], 1023) == 10',
    'assert candidate([10, 15, 20], 120) == 6',
    'assert candidate([1, 2, 3, 4, 5], 10000) == 2000',
    'assert candidate([1, 11, 21, 31], 10000) == 330',
    'assert candidate([1, 3, 5, 7, 9], 10000) == 1112',
    'assert candidate([1, 2, 5, 10, 20, 50, 100, 200], 399) == 8',
    'assert candidate([13, 19, 23, 29, 31, 37, 41], 9998) == 246',
    'assert candidate([1, 6, 13, 37, 150], 9999) == 71',
    'assert candidate([10, 20, 50, 100, 200], 10000) == 50',
    'assert candidate([1, 5, 10, 25, 50], 87) == 5',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10000) == 1000',
    'assert candidate([100, 200, 300, 400, 500], 9999) == -1',
    'assert candidate([1, 3, 4, 5], 150) == 30',
    'assert candidate([2, 5, 10, 20], 98) == 9',
    'assert candidate([1, 2, 5, 10, 25], 9999) == 403',
    'assert candidate([10, 25, 50], 9999) == -1',
    'assert candidate([11, 17, 29, 31], 10000) == 324',
    'assert candidate([7, 14, 28, 29], 10000) == 345',
    'assert candidate([10, 25, 50], 99) == -1',
    'assert candidate([1, 3, 4, 5, 7], 10000) == 1429',
    'assert candidate([100, 50, 20, 10, 5, 1], 19876) == 202',
    'assert candidate([1, 3, 4, 5], 15) == 3',
    'assert candidate([2, 5, 10, 20, 50, 100], 9999) == 105',
    'assert candidate([13, 17, 19], 1234) == 66',
    'assert candidate([1, 2, 5, 10, 20, 50, 100], 3689) == 42',
    'assert candidate([335, 23, 102, 75, 402], 9783) == 30',
    'assert candidate([2, 5, 10, 20, 50], 399) == 12',
    'assert candidate([17, 29, 31, 37, 41, 43], 8942) == 208',
    'assert candidate([2, 5, 10, 20, 50, 100], 363) == 9',
    'assert candidate([12, 25, 50, 100, 200], 3678) == 37',
    'assert candidate([13, 23, 33, 43, 53], 888) == 26',
    'assert candidate([3, 6, 9, 12, 15, 18], 100) == -1',
    'assert candidate([11, 17, 23], 457) == 23',
    'assert candidate([2, 5, 10, 25], 9999) == 403',
    'assert candidate([29, 81, 135, 50, 1], 2101) == 19',
    'assert candidate([33, 37, 41, 43, 47, 53, 59], 10000) == 170',
    'assert candidate([5, 11, 13], 10000) == 770',
    'assert candidate([10, 20, 50, 100], 345) == -1',
    'assert candidate([5, 10, 20, 50, 100], 4321) == -1',
    'assert candidate([13, 112, 197, 84, 205], 4873) == 26',
    'assert candidate([33, 77, 111, 155], 8500) == 60',
    'assert candidate([7, 15, 23], 1000) == 48',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().coinChange)
