# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for distinct-subsequences
_test_lines = [
    "assert candidate('abc', 'abcd') == 0",
    "assert candidate('abcd', 'abcd') == 1",
    "assert candidate('rabbbit', 'rabbit') == 3",
    "assert candidate('aaa', 'a') == 3",
    "assert candidate('', 'abc') == 0",
    "assert candidate('mississippi', 'isip') == 16",
    "assert candidate('aaaaa', 'aa') == 10",
    "assert candidate('abcde', 'ae') == 1",
    "assert candidate('abcde', '') == 1",
    "assert candidate('abcd', 'ab') == 1",
    "assert candidate('a', 'a') == 1",
    "assert candidate('abcdabcabc', 'abc') == 10",
    "assert candidate('babgbag', 'bag') == 5",
    "assert candidate('abc', 'abc') == 1",
    "assert candidate('pppp', 'p') == 4",
    "assert candidate('abab', 'aba') == 1",
    "assert candidate('', '') == 1",
    "assert candidate('leetcodeisgood', 'code') == 1",
    "assert candidate('abcdefghijklmnopqrstuvwxyz', 'acegikmoqsuwy') == 1",
    "assert candidate('zzzzzzzzzzzzzzzzzzzz', 'zzz') == 1140",
    "assert candidate('dynamicprogramming', 'dpm') == 2",
    "assert candidate('ababababab', 'abab') == 35",
    "assert candidate('abcdabcdabcd', 'abcd') == 15",
    "assert candidate('abcdabcdabcdabcd', 'abcd') == 35",
    "assert candidate('zzzzzzzzzz', 'zzzz') == 210",
    "assert candidate('aaaabbbbccccdddd', 'abcd') == 256",
    "assert candidate('abracadabra', 'abrac') == 1",
    "assert candidate('abcdefgabcdefgabcdefgabcdefgabcdefg', 'abcdefg') == 330",
    "assert candidate('abcabcabcabcabcabcabcabc', 'abcabc') == 924",
    "assert candidate('ababcabcabc', 'abc') == 19",
    "assert candidate('abcdefghikjlmnopqrstuvwxyz', 'xyz') == 1",
    "assert candidate('abcabcabcabc', 'abc') == 20",
    "assert candidate('abcbabc', 'abc') == 5",
    "assert candidate('xyzxyzxyz', 'xyzyx') == 1",
    "assert candidate('aabbbccc', 'abc') == 18",
    "assert candidate('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', 'zzzzzzzzzz') == 64512240",
    "assert candidate('xyzxyzxyzxyz', 'xyz') == 20",
    "assert candidate('aabbccddeeffgg', 'aabbcc') == 1",
    "assert candidate('abcdeabcdeabcde', 'abc') == 10",
    "assert candidate('xyzzxyzzxyzzxyzz', 'xyz') == 40",
    "assert candidate('xxyxyxyxyxyxyxyx', 'xyx') == 112",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz', 'abc') == 8",
    "assert candidate('xyxxyxyxyx', 'xyx') == 27",
    "assert candidate('mississippi', 'issi') == 15",
    "assert candidate('pneumonoultramicroscopicsilicovolcanoconiosis', 'pneumo') == 23",
    "assert candidate('pppppppppppp', 'pppp') == 495",
    "assert candidate('aaaaabaaaaabaabaaabaababab', 'aab') == 686",
    "assert candidate('abcdefg', 'xyz') == 0",
    "assert candidate('rabbbitrabbbitrabbbit', 'rabbit') == 126",
    "assert candidate('leetcodeleetcode', 'leet') == 12",
    "assert candidate('xyzxyzxyzxyz', 'xyzxyz') == 28",
    "assert candidate('abcdefghijk', 'acegi') == 1",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz', 'abcdefghijklmnopqrstuvwxyz') == 67108864",
    "assert candidate('aabbccddeeffgg', 'abcde') == 32",
    "assert candidate('longerstringexample', 'long') == 3",
    "assert candidate('abracadabra', 'abra') == 9",
    "assert candidate('xxyyzzxxxyyzz', 'xyxz') == 24",
    "assert candidate('pppppppp', 'pp') == 28",
    "assert candidate('attatchmentattach', 'attach') == 32",
    "assert candidate('abcdefghijabcdefghij', 'abcde') == 6",
    "assert candidate('abcdabcdeabcdeabcd', 'abcd') == 35",
    "assert candidate('abcdefghij', 'abcdefghijk') == 0",
    "assert candidate('zzzzzzzzzz', 'zz') == 45",
    "assert candidate('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', 'zzzzzzzzzz') == 14782231840815648",
    "assert candidate('ppppppppp', 'ppp') == 84",
    "assert candidate('abcdefghij', 'j') == 1",
    "assert candidate('abcdabcdabcdabcdabcd', 'abcd') == 70",
    "assert candidate('repeatedsequence', 'seq') == 1",
    "assert candidate('aaaaaaaaaaaaaab', 'aaab') == 364",
    "assert candidate('aabbaabbaabbaabbaabb', 'aabb') == 415",
    "assert candidate('mixedcharacters', 'mix') == 1",
    "assert candidate('abababababab', 'ababab') == 84",
    "assert candidate('abcabcabcabc', 'abcabc') == 28",
    "assert candidate('aaaaaaabbaaaaa', 'aaaaaab') == 14",
    "assert candidate('abcabcabc', 'abc') == 10",
    "assert candidate('abcdabcdabcd', 'abca') == 5",
    "assert candidate('babgbagbabgbagbabgbag', 'bagbag') == 329",
    "assert candidate('anappleperap', 'ape') == 10",
    "assert candidate('zzzzzzzzzz', 'zzz') == 120",
    "assert candidate('aaaaaaaaaa', 'aaaaa') == 252",
    "assert candidate('abcdefghij', 'af') == 1",
    "assert candidate('abcabcabcabcabcabcabcabcabcabc', 'abcabc') == 3003",
    "assert candidate('complexpattern', 'comp') == 2",
    "assert candidate('abcdefghij', 'a') == 1",
    "assert candidate('aabbaabbaabbaabbaabb', 'aab') == 190",
    "assert candidate('abracadabraabracadabra', 'abra') == 103",
    "assert candidate('leetcodeleetcodeleetcode', 'leet') == 51",
    "assert candidate('aabbccddeeffgghhiijjkkllmnoonnpooqqrrssttuuvvwwxxyyzz', 'abcxyz') == 64",
    "assert candidate('abcdefabcdefabcdef', 'abcdef') == 28",
    "assert candidate('abcdefghij', 'acegi') == 1",
    "assert candidate('pppppppppp', 'pp') == 45",
    "assert candidate('hellohellohello', 'hellohello') == 17",
    "assert candidate('abcdefghij', 'aceg') == 1",
    "assert candidate('aabbccddeeffgg', 'abcdefg') == 128",
    "assert candidate('hellohellohello', 'he') == 6",
    "assert candidate('thisisaverylongstringthisisaverylongstring', 'thisisaverylongstring') == 73",
    "assert candidate('subsequenceexample', 'subseq') == 1",
    "assert candidate('abracadabra', 'aca') == 6",
    "assert candidate('abcdeabcde', 'abc') == 4",
    "assert candidate('aaaaabaaaabaaaab', 'aaab') == 380",
    "assert candidate('abcdefghijabcdefghijabcdefghij', 'abcde') == 21",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().numDistinct)
