# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for edit-distance
_test_lines = [
    "assert candidate('park', 'spake') == 3",
    "assert candidate('algorithm', 'altruistic') == 6",
    "assert candidate('abc', '') == 3",
    "assert candidate('horse', 'ros') == 3",
    "assert candidate('a', 'b') == 1",
    "assert candidate('kitten', 'sitting') == 3",
    "assert candidate('a', 'a') == 0",
    "assert candidate('a', '') == 1",
    "assert candidate('abcdefghij', 'jihgfedcba') == 10",
    "assert candidate('', 'a') == 1",
    "assert candidate('', 'abc') == 3",
    "assert candidate('abc', 'abc') == 0",
    "assert candidate('intention', 'execution') == 5",
    "assert candidate('abcd', 'dcba') == 4",
    "assert candidate('', '') == 0",
    "assert candidate('abc', 'def') == 3",
    "assert candidate('flaw', 'lawn') == 2",
    "assert candidate('example', 'samples') == 3",
    "assert candidate('abbreviation', 'acceleration') == 6",
    "assert candidate('abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba') == 26",
    "assert candidate('acknowledgment', 'acknowledge') == 3",
    "assert candidate('xylophone', 'xylophone') == 0",
    "assert candidate('dynamic', 'programming') == 8",
    "assert candidate('embarrassing', 'aberration') == 7",
    "assert candidate('supercalifragilisticexpialidocious', 'supercalifragilisticexpialidociousness') == 4",
    "assert candidate('sequential', 'sequentialization') == 7",
    "assert candidate('algorithm', 'alligator') == 6",
    "assert candidate('distance', 'distinction') == 5",
    "assert candidate('irreversible', 'reversible') == 2",
    "assert candidate('serendipity', 'inspiration') == 10",
    "assert candidate('karolin', 'kathrin') == 3",
    "assert candidate('representative', 'reproductive') == 6",
    "assert candidate('congratulations', 'congratulate') == 4",
    "assert candidate('supercalifragilisticexpialidocious', 'pseudopseudohypoparathyroidism') == 30",
    "assert candidate('qwerty', 'azerty') == 2",
    "assert candidate('mississippi', 'mispelling') == 7",
    "assert candidate('levenshtein', 'levenshtein') == 0",
    "assert candidate('sequential', 'concurrent') == 9",
    "assert candidate('psychological', 'psychologist') == 3",
    "assert candidate('interpretation', 'interpretive') == 4",
    "assert candidate('transient', 'transitory') == 4",
    "assert candidate('abcdefgh', 'xyz') == 8",
    "assert candidate('algorithmic', 'algebraic') == 6",
    "assert candidate('transformation', 'transfiguration') == 4",
    "assert candidate('edit', 'editing') == 3",
    "assert candidate('levenshtein', 'levenschtein') == 1",
    "assert candidate('abracadabra', 'barbarian') == 8",
    "assert candidate('encyclopedia', 'encyclopedic') == 1",
    "assert candidate('transformation', 'transmogrification') == 6",
    "assert candidate('complexity', 'simplicity') == 4",
    "assert candidate('transformation', 'transformation') == 0",
    "assert candidate('transformation', 'transform') == 5",
    "assert candidate('abcdexyz', 'abcd') == 4",
    "assert candidate('zoology', 'botany') == 5",
    "assert candidate('computation', 'computational') == 2",
    "assert candidate('pharmaceuticals', 'pharmacology') == 8",
    "assert candidate('distance', 'difference') == 5",
    "assert candidate('reciprocal', 'perpendicular') == 10",
    "assert candidate('development', 'evolution') == 7",
    "assert candidate('amplification', 'attenuation') == 7",
    "assert candidate('thermodynamics', 'thermodynamic') == 1",
    "assert candidate('metamorphosis', 'metaphysics') == 5",
    "assert candidate('quantum', 'quark') == 4",
    "assert candidate('repetition', 'repetitions') == 1",
    "assert candidate('transform', 'transformation') == 5",
    "assert candidate('sequence', 'consequence') == 3",
    "assert candidate('abbreviation', 'contraction') == 8",
    "assert candidate('development', 'independently') == 9",
    "assert candidate('distance', 'distant') == 2",
    "assert candidate('mississippi', 'mississipi') == 1",
    "assert candidate('biographical', 'biographies') == 3",
    "assert candidate('optimization', 'maximization') == 3",
    "assert candidate('photosynthesis', 'photosynthetic') == 2",
    "assert candidate('supercalifragilisticexpialidocious', 'pneumonoultramicroscopicsilicovolcanoconiosis') == 31",
    "assert candidate('algorithm', 'altruism') == 5",
    "assert candidate('representation', 'representative') == 2",
    "assert candidate('reptile', 'reptilian') == 3",
    "assert candidate('abacaxi', 'abacax') == 1",
    "assert candidate('mississippi', 'misisippi') == 2",
    "assert candidate('electrical', 'electronic') == 4",
    "assert candidate('photograph', 'photography') == 1",
    "assert candidate('python', 'typhon') == 2",
    "assert candidate('kayak', 'racecar') == 5",
    "assert candidate('optimization', 'minimization') == 3",
    "assert candidate('biological', 'biographic') == 7",
    "assert candidate('congratulations', 'congratulations') == 0",
    "assert candidate('photography', 'photomontage') == 7",
    "assert candidate('babble', 'bubble') == 1",
    "assert candidate('transformation', 'transmute') == 7",
    "assert candidate('supercalifragilisticexpialidocious', 'antidisestablishmentarianism') == 26",
    "assert candidate('semantically', 'syntactically') == 4",
    "assert candidate('synchronous', 'asynchronous') == 1",
    "assert candidate('evolution', 'revolution') == 1",
    "assert candidate('abcdefghij', 'zyxwvutsrqponmlkjihgfedcba') == 25",
    "assert candidate('misunderstanding', 'understanding') == 3",
    "assert candidate('combinatorics', 'computation') == 7",
    "assert candidate('electromagnetic', 'electroencephalography') == 13",
    "assert candidate('permutation', 'combination') == 6",
    "assert candidate('subsequence', 'supersequence') == 3",
    "assert candidate('lumberjack', 'lumbersome') == 4",
    "assert candidate('optimization', 'information') == 7",
    "assert candidate('interpolation', 'interpretation') == 3",
    "assert candidate('magnificent', 'magnanimous') == 6",
    "assert candidate('xylophone', 'xylography') == 6",
    "assert candidate('biochemistry', 'bioinformatics') == 10",
    "assert candidate('exaggeration', 'aggrandizement') == 10",
    "assert candidate('abcde', 'fghij') == 5",
    "assert candidate('mississippi', 'mispell') == 8",
    "assert candidate('interpolation', 'internationalization') == 8",
    "assert candidate('entomology', 'herpetology') == 5",
    "assert candidate('interference', 'interferometer') == 5",
    "assert candidate('communication', 'communism') == 6",
    "assert candidate('characterization', 'categorization') == 6",
    "assert candidate('abracadabra', 'cabracadabara') == 2",
    "assert candidate('transformation', 'transference') == 7",
    "assert candidate('decomposition', 'discombobulation') == 7",
    "assert candidate('intermediate', 'interim') == 6",
    "assert candidate('interpolation', 'intrapolation') == 2",
    "assert candidate('visualization', 'representation') == 9",
    "assert candidate('abbreviation', 'elision') == 7",
    "assert candidate('metamorphism', 'metempsychosis') == 8",
    "assert candidate('encyclopedia', 'encyclopedia') == 0",
    "assert candidate('interdisciplinary', 'transdisciplinary') == 5",
    "assert candidate('unbelievable', 'believable') == 2",
    "assert candidate('abracadabra', 'cadabra') == 4",
    "assert candidate('hydrostatic', 'hydrodynamics') == 5",
    "assert candidate('parallel', 'perpendicular') == 10",
    "assert candidate('administration', 'administrative') == 2",
    "assert candidate('cosmology', 'cosmonautics') == 7",
    "assert candidate('development', 'develpoment') == 2",
    "assert candidate('photosynthesis', 'photography') == 8",
    "assert candidate('biochemistry', 'biological') == 8",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().minDistance)
