# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for evaluate-reverse-polish-notation
_test_lines = [
    "assert candidate(['4', '13', '5', '/', '+']) == 6",
    "assert candidate(['2', '1', '+', '3', '*']) == 9",
    "assert candidate(['10', '6', '9', '3', '+', '-11', '*', '/', '*', '17', '+', '5', '+']) == 22",
    "assert candidate(['20', '5', '/', '2', '+', '10', '3', '/', '-', '3', '4', '*', '+', '2', '-', '1', '*']) == 13",
    "assert candidate(['100', '50', '/', '3', '-', '2', '*', '4', '1', '+', '/', '5', '-', '2', '*']) == -10",
    "assert candidate(['-10', '-3', '/', '2', '*']) == 6",
    "assert candidate(['20', '5', '*']) == 100",
    "assert candidate(['3', '-4', '+', '2', '*', '5', '/', '10', '+']) == 10",
    "assert candidate(['8', '4', '+', '3', '*', '2', '/', '7', '-', '1', '+', '5', '*']) == 60",
    "assert candidate(['17', '5', '+', '3', '8', '*', '-', '10', '2', '/', '+']) == 3",
    "assert candidate(['10', '-5', '*', '2', '-', '3', '*']) == -156",
    "assert candidate(['100', '50', '-', '20', '*', '2', '/', '3', '+', '5', '-', '6', '*', '7', '/', '8', '+', '9', '-']) == 425",
    "assert candidate(['100', '50', '/', '20', '10', '/', '*', '30', '2', '*', '+']) == 64",
    "assert candidate(['100', '-50', '/', '20', '-10', '/', '*']) == 4",
    "assert candidate(['1', '2', '+', '3', '4', '+', '*', '5', '6', '+', '7', '8', '+', '*', '9', '10', '+', '*']) == 21",
    "assert candidate(['8', '4', '*', '6', '2', '/', '-', '5', '+', '3', '2', '*']) == 34",
    "assert candidate(['-10', '-5', '/', '2', '*', '-1', '+']) == 3",
    "assert candidate(['8', '12', '+', '3', '/', '4', '*', '5', '2', '/', '-', '7', '+', '2', '*']) == 58",
    "assert candidate(['1', '2', '+', '3', '4', '+', '*']) == 21",
    "assert candidate(['3', '8', '2', '/', '+', '4', '*', '10', '5', '/', '-', '2', '*']) == 52",
    "assert candidate(['20', '5', '+', '3', '*', '2', '-', '8', '/', '4', '*']) == 36",
    "assert candidate(['5', '2', '/', '1', '+', '4', '*']) == 12",
    "assert candidate(['7', '3', '+', '2', '*', '5', '-']) == 15",
    "assert candidate(['8', '2', '/', '3', '4', '+', '*', '1', '5', '-', '*']) == -112",
    "assert candidate(['20', '10', '/', '5', '*']) == 10",
    "assert candidate(['1', '3', '2', '*', '+', '5', '-', '1', '2', '+', '/']) == 0",
    "assert candidate(['10', '5', '2', '/', '+', '3', '-14', '*', '8', '/']) == 12",
    "assert candidate(['-1', '3', '*', -1, '2', '+', '*', '4', '1', '-']) == -3",
    "assert candidate(['10', '5', '+', '20', '-', '2', '/', '15', '*', '3', '-', '10', '/', '2', '+', '1', '-', '7', '*', '3', '/', '2', '*']) == -8",
    "assert candidate(['12', '-3', '*', '4', '/', '8', '+', '2', '-', '5', '*', '-2', '/']) == 7",
    "assert candidate(['5', '8', '4', '/', '+']) == 7",
    "assert candidate(['10', '4', '2', '+', '*']) == 60",
    "assert candidate(['10', '3', '5', '/', '2', '*', '+', '8', '3', '2', '*', '-', '4', '*', '2', '/', '+']) == 14",
    "assert candidate(['12', '3', '*']) == 36",
    "assert candidate(['17', '5', '+', '3', '*', '2', '-', '1', '+', '4', '/', '2', '*', '3', '+', '1', '-', '9', '/', '3', '*', '-11', '+', '-2', '*', '-3', '+', '17', '/', '5', '-', '7', '+', '-4', '*']) == -8",
    "assert candidate(['18', '4', '-']) == 14",
    "assert candidate(['10', '20', '+', '30', '*', '40', '+', '50', '*', '60', '-']) == 46940",
    "assert candidate(['10', '-5', '*', '2', '+', '20', '-10', '/', '*', '3', '+', '2', '*']) == 198",
    "assert candidate(['10', '20', '30', '40', '+', '*']) == 10",
    "assert candidate(['8', '3', '-', '2', '1', '/', '*']) == 10",
    "assert candidate(['9', '3', '+', '6', '2', '/', '-', '11', '*', '7', '/', '2', '+']) == 16",
    "assert candidate(['1', '2', '3', '4', '+', '*', '5', '/']) == 1",
    "assert candidate(['1', '2', '3', '+', '4', '/', '+', '5', '-', '6', '*']) == -18",
    "assert candidate(['1', '1', '+', '1', '1', '+', '1', '1', '+', '1', '1', '+', '1', '1', '+']) == 2",
    "assert candidate(['-7', '3', '/', '2', '-3', '*']) == -2",
    "assert candidate(['9', '3', '+', '6', '2', '/', '*']) == 36",
    "assert candidate(['9', '3', '-', '4', '/', '8', '2', '*', '+', '6', '1', '-', '*', '3', '+', '5', '-', '11', '/']) == 7",
    "assert candidate(['7', '-8', '*', '2', '/', '3', '+', '1', '-', '5', '11', '+', '2', '/', '*', '4', '-']) == -212",
    "assert candidate(['100', '50', '+', '25', '-', '10', '*', '5', '/']) == 250",
    "assert candidate(['7', '-3', '*', '2', '1', '+', '*', '5', '-', '3', '+', '2', '*']) == -130",
    "assert candidate(['10', '3', '/', '5', '+', '-3', '*', '7', '2', '/', '+', '8', '-', '2', '*', '3', '+', '6', '-', '4', '/', '9', '+', '11', '-', '13', '*', '15', '/', '17', '+', '19', '-']) == -16",
    "assert candidate(['5', '8', '4', '2', '+', '*']) == 5",
    "assert candidate(['5', '3', '+', '2', '*', '8', '4', '/', '-']) == 14",
    "assert candidate(['-1', '-2', '*']) == 2",
    "assert candidate(['15', '7', '1', '1', '+', '-', '3', '/', '2', '1', '1', '+', '+', '-']) == 15",
    "assert candidate(['20', '4', '/', '5', '2', '*', '+']) == 15",
    "assert candidate(['8', '4', '+', '2', '/', '3', '*', '1', '+', '6', '-']) == 13",
    "assert candidate(['9', '3', '/', '2', '1', '+', '*']) == 9",
    "assert candidate(['18', '7', '+', '3', '-', '1', '*', '2', '+', '5', '/', '9', '+', '1', '+', '-11', '*', '13', '-', '5', '+', '9', '+', '15', '+', '1', '-', '7', '*', '8', '+', '-3', '-', '2', '-']) == -964",
    "assert candidate(['10', '-5', '+', '20', '-10', '/', '2', '*']) == 5",
    "assert candidate(['5', '-2', '*']) == -10",
    "assert candidate(['10', '20', '5', '/', '2', '*']) == 10",
    "assert candidate(['13', '7', '2', '+', '/']) == 1",
    "assert candidate(['-1', '-1', '*', '-2', '-', '2', '*', '-3', '/', '4', '-']) == -6",
    "assert candidate(['1', '3', '-']) == -2",
    "assert candidate(['15', '11', '+']) == 26",
    "assert candidate(['10', '20', '+', '30', '40', '+', '50', '60', '+', '70', '80', '+', '90', '*']) == 30",
    "assert candidate(['6', '3', '1', '+', '*', '4', '/']) == 6",
    "assert candidate(['15', '7', '1', '1', '+', '-', '/', '3', '*', '2', '1', '1', '+', '+', '-']) == 5",
    "assert candidate(['100', '50', '+', '20', '*', '4', '/', '2', '+', '8', '-', '3', '*']) == 2232",
    "assert candidate(['1', '2', '+', '3', '4', '+', '*', '5', '6', '+', '*', '7', '8', '+', '*', '9', '10', '+', '*']) == 65835",
    "assert candidate(['100', '50', '-']) == 50",
    "assert candidate(['100', '200', '+', '50', '-', '2', '/', '3', '*', '10', '+']) == 385",
    "assert candidate(['5', '3', '+', '7', '4', '-', '*']) == 24",
    "assert candidate(['1', '2', '+', '3', '*', '4', '+', '5', '*', '6', '+', '7', '*', '8', '+', '9', '+', '10', '+', '11', '+', '12', '+', '13', '+', '14', '+', '15', '+', '16', '+', '17', '+', '18', '+', '19', '+']) == 659",
    "assert candidate(['100', '50', '/', '20', '*', '10', '-', '5', '+', '2', '*', '3', '/', '1', '+', '4', '-']) == 20",
    "assert candidate(['18', '5', '+', '12', '-', '3', '/', '2', '*', '4', '-']) == 2",
    "assert candidate(['8', '3', '2', '*', '1', '-', '2', '/']) == 8",
    "assert candidate(['-11', '-12', '-', '13', '-14', '-', '*']) == 27",
    "assert candidate(['20', '5', '2', '/', '*']) == 40",
    "assert candidate(['0', '3', '/', '5', '+']) == 5",
    "assert candidate(['3', '-4', '*', '2', '/', '5', '-']) == -11",
    "assert candidate(['1', '2', '3', '+', '*']) == 5",
    "assert candidate(['100', '50', '2', '*', '-', '30', '20', '+', '/', '10', '+']) == 10",
    "assert candidate(['7', '-3', '*', '11', '5', '-', '/', '2', '2', '+', '*']) == -12",
    "assert candidate(['7', '-3', '*', '2', '1', '+', '-', '15', '5', '/', '+']) == -21",
    "assert candidate(['2', '3', '4', '5', '+', '*', '6', '/']) == 2",
    "assert candidate(['10', '6', '9', '3', '+', '-11', '*']) == 10",
    "assert candidate(['7', '-3', '*']) == -21",
    "assert candidate(['10', '5', '-', '3', '*', '4', '+', '2', '/']) == 9",
    "assert candidate(['7', '-3', '*', '2', '+', '15', '5', '/', '*']) == -57",
    "assert candidate(['15', '-3', '/', '7', '+', '2', '*', '10', '-', '5', '*']) == -30",
    "assert candidate(['100', '50', '/', '25', '*', '5', '+', '3', '-', '2', '*']) == 104",
    "assert candidate(['7', '-8', '*', '5', '+', '3', '-12', '/', '4', '*']) == -51",
    "assert candidate(['7', '8', '3', '*', '+', '2', '/', '4', '-', '10', '5', '*', '+']) == 61",
    "assert candidate(['5', '2', '/', '10', '2', '/', '-', '3', '*', '7', '+', '-1', '*']) == 2",
    "assert candidate(['5', '2', '/', '-1', '*', '3', '-']) == -5",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().evalRPN)
