# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for find-the-duplicate-number
_test_lines = [
    'assert candidate([1, 2, 3, 3, 3, 3]) == 3',
    'assert candidate([1, 2, 2, 3, 4]) == 2',
    'assert candidate([7, 9, 7, 4, 6, 2, 3, 8, 5, 1]) == 7',
    'assert candidate([3, 1, 3, 4, 2]) == 3',
    'assert candidate([1, 2, 3, 4, 4, 4, 5]) == 4',
    'assert candidate([3, 3, 3, 3, 3]) == 3',
    'assert candidate([1, 3, 4, 2, 2]) == 2',
    'assert candidate([5, 1, 2, 3, 4, 5]) == 5',
    'assert candidate([1, 2, 3, 4, 5, 6, 6]) == 6',
    'assert candidate([1, 2, 3, 4, 4]) == 4',
    'assert candidate([1, 1, 2, 3, 4, 5]) == 1',
    'assert candidate([1, 1, 2, 3, 4]) == 1',
    'assert candidate([2, 2, 2, 2, 1]) == 2',
    'assert candidate([2, 2, 2, 2, 2]) == 2',
    'assert candidate([2, 1, 2, 3, 4, 5]) == 2',
    'assert candidate([1, 2, 3, 4, 5, 5]) == 5',
    'assert candidate([1, 4, 4, 2, 3]) == 4',
    'assert candidate([2, 5, 9, 6, 9, 3, 8, 9, 7, 1]) == 9',
    'assert candidate([5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 5',
    'assert candidate([1, 3, 2, 4, 5, 5, 6, 7, 8, 9]) == 5',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 7]) == 7',
    'assert candidate([1, 3, 2, 5, 4, 6, 7, 8, 9, 10, 3]) == 3',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10]) == 10',
    'assert candidate([2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 2]) == 2',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2]) == 2',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5]) == 5',
    'assert candidate([5, 1, 4, 2, 5, 3, 5, 5, 5, 5]) == 5',
    'assert candidate([5, 4, 3, 2, 1, 6, 7, 8, 9, 2, 2]) == 2',
    'assert candidate([2, 1, 4, 3, 5, 6, 7, 8, 9, 10, 2]) == 2',
    'assert candidate([8, 7, 3, 6, 4, 2, 5, 7, 1, 9]) == 7',
    'assert candidate([1, 5, 2, 3, 5, 4, 5, 5, 5, 5, 5]) == 5',
    'assert candidate([2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1]) == 1',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 1',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]) == 1',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 1]) == 1',
    'assert candidate([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) == 2',
    'assert candidate([8, 9, 7, 6, 5, 4, 3, 2, 1, 8, 8]) == 8',
    'assert candidate([3, 2, 1, 4, 5, 6, 7, 8, 9, 10, 3]) == 3',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 4]) == 4',
    'assert candidate([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1]) == 2',
    'assert candidate([50000, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 50000]) == 12',
    'assert candidate([1, 5, 3, 4, 2, 5]) == 5',
    'assert candidate([1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 1',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) == 5',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10]) == 9',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 1]) == 1',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8]) == 8',
    'assert candidate([100000, 99999, 99998, 99997, 99996, 99995, 99994, 99993, 99992, 99991, 99991]) == 11',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1, 1]) == 1',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 9]) == 9',
    'assert candidate([10, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1]) == 1',
    'assert candidate([5, 4, 3, 2, 1, 2, 6, 7, 8, 9, 10]) == 2',
    'assert candidate([7, 6, 5, 4, 3, 2, 1, 1]) == 1',
    'assert candidate([1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 1',
    'assert candidate([8, 7, 6, 5, 4, 3, 2, 1, 1, 9, 10]) == 1',
    'assert candidate([100000, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100000]) == 11',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 6]) == 6',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100]) == 11',
    'assert candidate([10, 8, 7, 4, 6, 2, 9, 5, 3, 10, 1]) == 10',
    'assert candidate([1, 3, 2, 5, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 5]) == 5',
    'assert candidate([5, 2, 4, 3, 1, 5, 5, 5, 5, 5, 5]) == 5',
    'assert candidate([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 1, 1]) == 1',
    'assert candidate([50000, 49999, 1, 2, 3, 4, 5, 6, 7, 8, 50000]) == 11',
    'assert candidate([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]) == 7',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 10]) == 1',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1, 5, 5]) == 5',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 2]) == 2',
    'assert candidate([7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 7]) == 11',
    'assert candidate([5, 4, 3, 2, 1, 1, 6, 7, 8, 9, 10]) == 1',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1, 9, 9]) == 9',
    'assert candidate([1, 3, 2, 4, 5, 6, 7, 8, 9, 10, 8, 8, 8, 8, 8]) == 8',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3]) == 3',
    'assert candidate([1, 100000, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 100000]) == 21',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1, 1, 10]) == 1',
    'assert candidate([5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5]) == 5',
    'assert candidate([99999, 99998, 99997, 99996, 99995, 99994, 99993, 99992, 99991, 99990, 99991]) == 11',
    'assert candidate([2, 3, 1, 4, 5, 6, 7, 8, 9, 10, 2]) == 2',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 1]) == 11',
    'assert candidate([5, 4, 3, 2, 1, 6, 5, 7, 8, 9, 10]) == 5',
    'assert candidate([1, 3, 5, 4, 2, 5, 6]) == 5',
    'assert candidate([8, 9, 7, 6, 5, 4, 3, 2, 1, 8]) == 8',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) == 3',
    'assert candidate([10, 8, 9, 6, 3, 1, 2, 7, 4, 10, 5]) == 10',
    'assert candidate([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2]) == 11',
    'assert candidate([1, 5, 4, 2, 3, 6, 7, 8, 9, 9, 10]) == 9',
    'assert candidate([10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9]) == 9',
    'assert candidate([1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5]) == 5',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().findDuplicate)
