# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for group-anagrams
def _sk(o):
    return (type(o).__name__, repr(o))
def _canon(x, deep):
    if isinstance(x, (list, tuple)):
        e = [_canon(i, deep) for i in x]
        if deep:
            e = sorted(e, key=_sk)
        return tuple(e)
    return x
def _eq_outer(a, b):
    if a is None or b is None:
        return a == b
    return sorted((_canon(x, False) for x in a), key=_sk) == sorted((_canon(x, False) for x in b), key=_sk)
def _eq_outer_inner(a, b):
    if a is None or b is None:
        return a == b
    return sorted((_canon(x, True) for x in a), key=_sk) == sorted((_canon(x, True) for x in b), key=_sk)
def _valid_two_sum(res, arr, target, one_indexed, expected):
    if expected is None:
        return res is None or res == [] or res == ()
    if not res or len(res) != 2:
        return False
    off = 1 if one_indexed else 0
    i, j = res[0] - off, res[1] - off
    n = len(arr)
    if not (0 <= i < n and 0 <= j < n and i != j):
        return False
    return arr[i] + arr[j] == target

_test_lines = [
    "assert _eq_outer_inner(candidate(['a', 'b', 'c', 'd', 'e']), [['a'], ['b'], ['c'], ['d'], ['e']])",
    "assert _eq_outer_inner(candidate(['abc', 'bca', 'cab', 'xyz', 'zyx', 'yxz']), [['abc', 'bca', 'cab'], ['xyz', 'zyx', 'yxz']])",
    "assert _eq_outer_inner(candidate(['abc', 'def', 'ghi', 'jkl']), [['abc'], ['def'], ['ghi'], ['jkl']])",
    "assert _eq_outer_inner(candidate(['abc', 'acb', 'bac', 'bca', 'cab', 'cba']), [['abc', 'acb', 'bac', 'bca', 'cab', 'cba']])",
    "assert _eq_outer_inner(candidate(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']), [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist']), [['listen', 'silent', 'enlist']])",
    "assert _eq_outer_inner(candidate(['a']), [['a']])",
    "assert _eq_outer_inner(candidate(['aabb', 'bbaa', 'abab', 'baab', 'baba', 'abba', 'aaaa', 'bbbb']), [['aabb', 'bbaa', 'abab', 'baab', 'baba', 'abba'], ['aaaa'], ['bbbb']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl']), [['listen', 'silent', 'enlist'], ['google', 'gooegl']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'rat', 'tar', 'art']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['rat', 'tar', 'art']])",
    "assert _eq_outer_inner(candidate(['abc', 'bac', 'cab', 'bca', 'acb', 'cba']), [['abc', 'bac', 'cab', 'bca', 'acb', 'cba']])",
    "assert _eq_outer_inner(candidate(['dormitory', 'dirtyroom', 'conversation', 'voicesranton', 'listen', 'silent']), [['dormitory', 'dirtyroom'], ['conversation', 'voicesranton'], ['listen', 'silent']])",
    "assert _eq_outer_inner(candidate(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']), [['a'], ['b'], ['c'], ['d'], ['e'], ['f'], ['g'], ['h'], ['i'], ['j']])",
    "assert _eq_outer_inner(candidate(['hello', 'world', 'hold', 'olelh', 'dlrow', 'owrld']), [['hello', 'olelh'], ['world', 'dlrow', 'owrld'], ['hold']])",
    "assert _eq_outer_inner(candidate(['dormitory', 'dirtyroom', 'conversation', 'voicesranton', 'schoolmaster', 'theclassroom']), [['dormitory', 'dirtyroom'], ['conversation', 'voicesranton'], ['schoolmaster', 'theclassroom']])",
    "assert _eq_outer_inner(candidate(['hello', 'bello', 'olelh', 'world', 'dlrow', 'dlorw', 'droll']), [['hello', 'olelh'], ['bello'], ['world', 'dlrow', 'dlorw'], ['droll']])",
    "assert _eq_outer_inner(candidate(['']), [['']])",
    "assert _eq_outer_inner(candidate(['abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba', 'cba', 'bca', 'bac', 'acb', 'cab', 'abc']), [['abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba'], ['cba', 'bca', 'bac', 'acb', 'cab', 'abc']])",
    "assert _eq_outer_inner(candidate(['abc', 'abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab', 'abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab', 'abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab']), [['abc'], ['abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab', 'abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab', 'abcd', 'abdc', 'bacd', 'badc', 'cabd', 'cadb', 'dcba', 'dcab']])",
    "assert _eq_outer_inner(candidate(['abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba', 'mnopqrstuvwxyzabcdefghijkl', 'qrstuvwxyzaabcdefghijklmnop', 'hgfedcbazyxwvutsrqponmlkjijklmnopqrstuvwxyzabcde']), [['abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba', 'mnopqrstuvwxyzabcdefghijkl'], ['qrstuvwxyzaabcdefghijklmnop'], ['hgfedcbazyxwvutsrqponmlkjijklmnopqrstuvwxyzabcde']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'child', 'brink', 'drink', 'crimp', 'crimp', 'stick', 'smirk', 'smirk', 'smith', 'tinsy', 'stint']), [['dusty', 'study'], ['night', 'thing'], ['child'], ['brink'], ['drink'], ['crimp', 'crimp'], ['stick'], ['smirk', 'smirk'], ['smith'], ['tinsy'], ['stint']])",
    "assert _eq_outer_inner(candidate(['aabb', 'abab', 'baba', 'baab', 'abba', 'bbaa', 'aabb', 'abab', 'baba', 'baab', 'abba', 'bbaa']), [['aabb', 'abab', 'baba', 'baab', 'abba', 'bbaa', 'aabb', 'abab', 'baba', 'baab', 'abba', 'bbaa']])",
    "assert _eq_outer_inner(candidate(['apple', 'pepal', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'appel', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe']), [['apple', 'pepal', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'appel', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe', 'ppale', 'pplea', 'ppela', 'elppa', 'ppael', 'palpe']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'delta', 'tigon', 'state', 'taste', 'date', 'rated']), [['dusty', 'study'], ['night', 'thing'], ['delta'], ['tigon'], ['state', 'taste'], ['date'], ['rated']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'baccab', 'acbbac', 'cabbaa', 'aabbcc', 'abcabc']), [['aabbcc', 'abcabc', 'baccab', 'acbbac', 'aabbcc', 'abcabc'], ['cabbaa']])",
    "assert _eq_outer_inner(candidate(['rat', 'car', 'tar', 'arc', 'cat', 'tac', 'act', 'rat', 'car', 'tar', 'arc', 'cat', 'tac', 'act']), [['rat', 'tar', 'rat', 'tar'], ['car', 'arc', 'car', 'arc'], ['cat', 'tac', 'act', 'cat', 'tac', 'act']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'aabbcc', 'ccbaab', 'abcabc', 'baccab', 'bacabc', 'cababc', 'abcabc']), [['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'aabbcc', 'ccbaab', 'abcabc', 'baccab', 'bacabc', 'cababc', 'abcabc']])",
    "assert _eq_outer_inner(candidate(['aabb', 'abab', 'bbaa', 'abba', 'baab', 'aaba', 'baba', 'bbba', 'baaa', 'aaaa', 'bbbb']), [['aabb', 'abab', 'bbaa', 'abba', 'baab', 'baba'], ['aaba', 'baaa'], ['bbba'], ['aaaa'], ['bbbb']])",
    "assert _eq_outer_inner(candidate(['ab', 'ba', 'ac', 'ca', 'ad', 'da', 'bc', 'cb', 'ef', 'fe', 'gh', 'hg', 'ij', 'ji', 'kl', 'lk', 'mnop', 'nopm', 'opmn', 'pmno', 'qrst', 'srqt', 'tqrs', 'qrst', 'stqr', 'qrstuv', 'rstquv', 'tsrquv', 'uvqrst', 'vqrstu', 'wxyz', 'xyzw', 'yzwx', 'zwxy']), [['ab', 'ba'], ['ac', 'ca'], ['ad', 'da'], ['bc', 'cb'], ['ef', 'fe'], ['gh', 'hg'], ['ij', 'ji'], ['kl', 'lk'], ['mnop', 'nopm', 'opmn', 'pmno'], ['qrst', 'srqt', 'tqrs', 'qrst', 'stqr'], ['qrstuv', 'rstquv', 'tsrquv', 'uvqrst', 'vqrstu'], ['wxyz', 'xyzw', 'yzwx', 'zwxy']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'rat', 'tar', 'art', 'arc', 'car', 'arc']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['rat', 'tar', 'art'], ['arc', 'car', 'arc']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'abc', 'cab', 'bac', 'bca', 'acb', 'cba']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['abc', 'cab', 'bac', 'bca', 'acb', 'cba']])",
    "assert _eq_outer_inner(candidate(['zzzz', 'zazaz', 'zzzzz', 'zz', 'z', 'za', 'az', 'zzzz', 'zazaz', 'zzzzz', 'zz', 'z', 'za', 'az']), [['zzzz', 'zzzz'], ['zazaz', 'zazaz'], ['zzzzz', 'zzzzz'], ['zz', 'zz'], ['z', 'z'], ['za', 'az', 'za', 'az']])",
    "assert _eq_outer_inner(candidate(['aabb', 'bbaa', 'abab', 'abba', 'baab', 'baba', 'aaaa', 'bbbb', 'aabbcc', 'ccbaab', 'aabbc', 'abbac', 'abc', 'acb', 'bac', 'bca', 'cab', 'cba', 'zzz', 'zzzz', 'zzzzz']), [['aabb', 'bbaa', 'abab', 'abba', 'baab', 'baba'], ['aaaa'], ['bbbb'], ['aabbcc', 'ccbaab'], ['aabbc', 'abbac'], ['abc', 'acb', 'bac', 'bca', 'cab', 'cba'], ['zzz'], ['zzzz'], ['zzzzz']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'aabbcc', 'ccbaab', 'abcabc', 'baccab', 'bacabc', 'cababc', 'abcabc', 'xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz']), [['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'aabbcc', 'ccbaab', 'abcabc', 'baccab', 'bacabc', 'cababc', 'abcabc'], ['xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz', 'zyx', 'yzx', 'zyx', 'xyz', 'yzx', 'zyx', 'xyz']])",
    "assert _eq_outer_inner(candidate(['python', 'typhon', 'hypton', 'pythno', 'ypthon', 'thypno', 'hypnot', 'hypnotize', 'notphyno', 'nothpyin', ' hypnot', 'hypnotic', 'hypnothize', 'hypnothise', 'notthpyin', 'pythonic', 'typhonian', 'pythongod', 'hypno', 'hypnosis', 'hypnotherapy', 'hypnagogia', 'hypnoid']), [['python', 'typhon', 'hypton', 'pythno', 'ypthon', 'thypno', 'hypnot'], ['hypnotize'], ['notphyno'], ['nothpyin'], [' hypnot'], ['hypnotic', 'pythonic'], ['hypnothize'], ['hypnothise'], ['notthpyin'], ['typhonian'], ['pythongod'], ['hypno'], ['hypnosis'], ['hypnotherapy'], ['hypnagogia'], ['hypnoid']])",
    "assert _eq_outer_inner(candidate(['abcde', 'edcba', 'bcdea', 'decba', 'bacde', 'cabde', 'eabcd', 'acbde', 'dbcea', 'adbce']), [['abcde', 'edcba', 'bcdea', 'decba', 'bacde', 'cabde', 'eabcd', 'acbde', 'dbcea', 'adbce']])",
    "assert _eq_outer_inner(candidate(['abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed']), [['abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed', 'abcde', 'edcba', 'bcdea', 'decba', 'edbac', 'acbed']])",
    "assert _eq_outer_inner(candidate(['abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba']), [['abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba', 'adbc', 'cbad', 'abcd', 'bcda', 'abcd', 'dcba']])",
    "assert _eq_outer_inner(candidate(['abcd', 'dcba', 'cabd', 'badc', 'dacb', 'cdab', 'bcad', 'bcda', 'acbd', 'cadb', 'acdb', 'abdc']), [['abcd', 'dcba', 'cabd', 'badc', 'dacb', 'cdab', 'bcad', 'bcda', 'acbd', 'cadb', 'acdb', 'abdc']])",
    "assert _eq_outer_inner(candidate(['dormitory', 'dirtyroom', 'listen', 'silent', 'enlist', 'google', 'gooegl', 'abc', 'cab', 'bac', 'bca', 'acb', 'cba', 'zzz', 'zzzz', 'zzzzz', 'zzzzzz']), [['dormitory', 'dirtyroom'], ['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['abc', 'cab', 'bac', 'bca', 'acb', 'cba'], ['zzz'], ['zzzz'], ['zzzzz'], ['zzzzzz']])",
    "assert _eq_outer_inner(candidate(['abcd', 'dcba', 'abcd', 'cdab', 'bdac', 'cabd', 'bacd', 'abcd', 'dcba', 'abcd']), [['abcd', 'dcba', 'abcd', 'cdab', 'bdac', 'cabd', 'bacd', 'abcd', 'dcba', 'abcd']])",
    "assert _eq_outer_inner(candidate(['aabb', 'abab', 'bbaa', 'abba', 'aaaa', 'aaab', 'baaa', 'baba', 'abba', 'aabb', 'abab', 'bbaa', 'aaaa']), [['aabb', 'abab', 'bbaa', 'abba', 'baba', 'abba', 'aabb', 'abab', 'bbaa'], ['aaaa', 'aaaa'], ['aaab', 'baaa']])",
    "assert _eq_outer_inner(candidate(['abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb']), [['abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb', 'abcd', 'dcba', 'adcb', 'cbad', 'bdac', 'cabd', 'bacd', 'acbd', 'dbca', 'bcad', 'cadb']])",
    "assert _eq_outer_inner(candidate(['anagram', 'nagaram', 'margana', 'anagrama', 'anagram', 'anagram', 'granama', 'nagaramm']), [['anagram', 'nagaram', 'margana', 'anagram', 'anagram', 'granama'], ['anagrama'], ['nagaramm']])",
    "assert _eq_outer_inner(candidate(['aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc', 'aaa', 'bbb', 'ccc']), [['aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa', 'aaa'], ['bbb', 'bbb', 'bbb', 'bbb', 'bbb', 'bbb', 'bbb', 'bbb'], ['ccc', 'ccc', 'ccc', 'ccc', 'ccc', 'ccc', 'ccc', 'ccc']])",
    "assert _eq_outer_inner(candidate(['aabb', 'bbaa', 'abab', 'baba', 'abba', 'baab', 'abc', 'bac', 'bca', 'acb', 'cba', 'zzz', 'zzzz', 'zzzzz', 'zzzzzz', 'zzzzzzz', 'zzzzzzzz', 'zzzzzzzzz']), [['aabb', 'bbaa', 'abab', 'baba', 'abba', 'baab'], ['abc', 'bac', 'bca', 'acb', 'cba'], ['zzz'], ['zzzz'], ['zzzzz'], ['zzzzzz'], ['zzzzzzz'], ['zzzzzzzz'], ['zzzzzzzzz']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'gnhit', 'inthe', 'night', 'thing', 'night', 'thing', 'night']), [['dusty', 'study'], ['night', 'thing', 'gnhit', 'night', 'thing', 'night', 'thing', 'night'], ['inthe']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac']), [['aabbcc', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac', 'abcabc', 'bcaacb', 'cababc', 'bcacab', 'bacbac', 'aabbcc', 'aabbcc', 'aabcbc', 'bcaabc', 'abacbc', 'babcac']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'abccba', 'acbbac', 'baccab', 'bcacab', 'bacbac', 'acbacb', 'bacbac', 'bacbac', 'bacbac', 'bacbac', 'bacbac']), [['aabbcc', 'abcabc', 'bcaabc', 'cababc', 'abccba', 'acbbac', 'baccab', 'bcacab', 'bacbac', 'acbacb', 'bacbac', 'bacbac', 'bacbac', 'bacbac', 'bacbac']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'eight', 'gnite', 'inthe', 'front', 'trofn', 'gnhet', 'gfno', 'gnfoe', 'thingo', 'niothg', 'ightn']), [['dusty', 'study'], ['night', 'thing', 'ightn'], ['eight'], ['gnite'], ['inthe'], ['front', 'trofn'], ['gnhet'], ['gfno'], ['gnfoe'], ['thingo', 'niothg']])",
    "assert _eq_outer_inner(candidate(['rat', 'car', 'tar', 'arc', 'arc', 'rta', 'cat', 'tac', 'act', 'cta', 'tca', 'atc']), [['rat', 'tar', 'rta'], ['car', 'arc', 'arc'], ['cat', 'tac', 'act', 'cta', 'tca', 'atc']])",
    "assert _eq_outer_inner(candidate(['abcde', 'edcba', 'fghij', 'jihgf', 'mnopq', 'qponm', 'rstuv', 'vutsr', 'wxyz', 'zyxw', 'aaaaa', 'bbbbb', 'ccccc', 'ddddd', 'eeeee', 'zzzzz']), [['abcde', 'edcba'], ['fghij', 'jihgf'], ['mnopq', 'qponm'], ['rstuv', 'vutsr'], ['wxyz', 'zyxw'], ['aaaaa'], ['bbbbb'], ['ccccc'], ['ddddd'], ['eeeee'], ['zzzzz']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'inlets', 'banana', 'anabna', 'xyz', 'zyx']), [['listen', 'silent', 'enlist', 'inlets'], ['google', 'gooegl'], ['banana', 'anabna'], ['xyz', 'zyx']])",
    "assert _eq_outer_inner(candidate(['abcd', 'dcba', 'abcd', 'abcd', 'dcba', 'abcd', 'dcba', 'abcd', 'abcd']), [['abcd', 'dcba', 'abcd', 'abcd', 'dcba', 'abcd', 'dcba', 'abcd', 'abcd']])",
    "assert _eq_outer_inner(candidate(['zzzz', 'zzz', 'zz', 'z', 'aaaa', 'aaa', 'aa', 'a', 'bbbb', 'bbb', 'bb', 'b', 'cccc', 'ccc', 'cc', 'c', 'dddd', 'ddd', 'dd', 'd', 'eeee', 'eee', 'ee', 'e']), [['zzzz'], ['zzz'], ['zz'], ['z'], ['aaaa'], ['aaa'], ['aa'], ['a'], ['bbbb'], ['bbb'], ['bb'], ['b'], ['cccc'], ['ccc'], ['cc'], ['c'], ['dddd'], ['ddd'], ['dd'], ['d'], ['eeee'], ['eee'], ['ee'], ['e']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'rat', 'tar', 'art', 'elbow', 'below']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['rat', 'tar', 'art'], ['elbow', 'below']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'abc', 'cab', 'bac']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['abc', 'cab', 'bac']])",
    "assert _eq_outer_inner(candidate(['xyz', 'zyx', 'yxz', 'xzy', 'zyx', 'yzy', 'xyx', 'xxy', 'xyy', 'yxx', 'yyx', 'yyy', 'xxx']), [['xyz', 'zyx', 'yxz', 'xzy', 'zyx'], ['yzy'], ['xyx', 'xxy', 'yxx'], ['xyy', 'yyx'], ['yyy'], ['xxx']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'enlist', 'google', 'gogole', 'inlets', 'abc', 'cba', 'bac', 'zyx', 'xyz', 'xyzzyx', 'zyxzyx']), [['dusty', 'study'], ['night', 'thing'], ['enlist', 'inlets'], ['google', 'gogole'], ['abc', 'cba', 'bac'], ['zyx', 'xyz'], ['xyzzyx', 'zyxzyx']])",
    "assert _eq_outer_inner(candidate(['hello', 'ohell', 'lohel', 'ollhe', 'elohl', '', '', '', 'a', 'a', 'a', 'a', 'a']), [['hello', 'ohell', 'lohel', 'ollhe', 'elohl'], ['', '', ''], ['a', 'a', 'a', 'a', 'a']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'rat', 'tar', 'art', 'rom', 'mor', 'arm', 'rmo']), [['listen', 'silent', 'enlist'], ['google', 'gooegl'], ['rat', 'tar', 'art'], ['rom', 'mor', 'rmo'], ['arm']])",
    "assert _eq_outer_inner(candidate(['aabbcc', 'abcabc', 'aabbbc', 'aacbbc', 'aabcc', 'abcacb', 'abacbc', 'bbaacc', 'abccba', 'bcaacb']), [['aabbcc', 'abcabc', 'aacbbc', 'abcacb', 'abacbc', 'bbaacc', 'abccba', 'bcaacb'], ['aabbbc'], ['aabcc']])",
    "assert _eq_outer_inner(candidate(['listen', 'silent', 'enlist', 'google', 'gooegl', 'inlets', 'banana']), [['listen', 'silent', 'enlist', 'inlets'], ['google', 'gooegl'], ['banana']])",
    "assert _eq_outer_inner(candidate(['abcde', 'edcba', 'bcdea', 'decab', 'cabed', 'edbac', 'baced', 'deabc', 'ebadc', 'acbed']), [['abcde', 'edcba', 'bcdea', 'decab', 'cabed', 'edbac', 'baced', 'deabc', 'ebadc', 'acbed']])",
    "assert _eq_outer_inner(candidate(['abc', 'bcd', 'cab', 'bac', 'bca', 'cba', 'xyz', 'zyx', 'yxz', 'zy', 'yz', 'z', 'a', 'b', 'c']), [['abc', 'cab', 'bac', 'bca', 'cba'], ['bcd'], ['xyz', 'zyx', 'yxz'], ['zy', 'yz'], ['z'], ['a'], ['b'], ['c']])",
    "assert _eq_outer_inner(candidate(['a', 'b', 'c', 'aa', 'bb', 'cc', 'aaa', 'bbb', 'ccc', 'aaaa', 'bbbb', 'cccc']), [['a'], ['b'], ['c'], ['aa'], ['bb'], ['cc'], ['aaa'], ['bbb'], ['ccc'], ['aaaa'], ['bbbb'], ['cccc']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'inhti', 'ytsud', 'ytsdu', 'gnith', 'dusty', 'study', 'night', 'thing', 'inhti', 'ytsud', 'ytsdu', 'gnith', 'dusty', 'study', 'night', 'thing', 'inhti', 'ytsud', 'ytsdu', 'gnith', 'dusty', 'study', 'night', 'thing', 'inhti', 'ytsud', 'ytsdu', 'gnith']), [['dusty', 'study', 'ytsud', 'ytsdu', 'dusty', 'study', 'ytsud', 'ytsdu', 'dusty', 'study', 'ytsud', 'ytsdu', 'dusty', 'study', 'ytsud', 'ytsdu'], ['night', 'thing', 'gnith', 'night', 'thing', 'gnith', 'night', 'thing', 'gnith', 'night', 'thing', 'gnith'], ['inhti', 'inhti', 'inhti', 'inhti']])",
    "assert _eq_outer_inner(candidate(['ab', 'ba', 'abc', 'cba', 'bac', 'bca', 'cab', 'acb', 'abc', 'cba', 'bac', 'bca', 'cab', 'acb']), [['ab', 'ba'], ['abc', 'cba', 'bac', 'bca', 'cab', 'acb', 'abc', 'cba', 'bac', 'bca', 'cab', 'acb']])",
    "assert _eq_outer_inner(candidate(['dusty', 'study', 'night', 'thing', 'sight', 'fling', 'tying', 'sting', 'dusty']), [['dusty', 'study', 'dusty'], ['night', 'thing'], ['sight'], ['fling'], ['tying'], ['sting']])",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().groupAnagrams)
