# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for house-robber
_test_lines = [
    'assert candidate(nums = [1]) == 1',
    'assert candidate(nums = [1, 2, 3, 1]) == 4',
    'assert candidate(nums = [2, 1, 1, 2]) == 4',
    'assert candidate(nums = [5, 2, 6, 3, 4, 1]) == 15',
    'assert candidate(nums = [5, 2, 6, 3, 1, 8, 9, 4, 7]) == 28',
    'assert candidate(nums = [1, 2]) == 2',
    'assert candidate(nums = [10, 2, 3, 8, 10, 1]) == 23',
    'assert candidate(nums = [0]) == 0',
    'assert candidate(nums = [3, 2, 5, 10, 7]) == 15',
    'assert candidate(nums = [5, 10, 5, 10]) == 20',
    'assert candidate(nums = [1, 3, 1, 3, 100]) == 103',
    'assert candidate(nums = [10, 20, 30, 40, 50]) == 90',
    'assert candidate(nums = [0, 0, 0, 0]) == 0',
    'assert candidate(nums = [50, 10, 100, 10, 5]) == 155',
    'assert candidate(nums = [3, 5, 100, 1, 1, 1, 1, 1, 100, 1, 1, 1, 1]) == 207',
    'assert candidate(nums = [2, 7, 9, 3, 1]) == 12',
    'assert candidate(nums = [3, 10, 3, 1, 2, 1]) == 12',
    'assert candidate(nums = [300, 400, 500, 100, 200, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500]) == 6500',
    'assert candidate(nums = [299, 399, 199, 299, 399, 199, 299, 399, 199, 299, 399, 199, 299, 399, 199, 299, 399, 199, 299, 399]) == 3090',
    'assert candidate(nums = [10, 5, 15, 20, 25, 30, 35, 40]) == 100',
    'assert candidate(nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]) == 136',
    'assert candidate(nums = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]) == 3000',
    'assert candidate(nums = [400, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 400',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 30',
    'assert candidate(nums = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]) == 27',
    'assert candidate(nums = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]) == 11000',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) == 42',
    'assert candidate(nums = [399, 0, 399, 0, 399, 0, 399, 0, 399, 0, 399, 0, 399, 0, 399, 0, 399]) == 3591',
    'assert candidate(nums = [100, 0, 100, 0, 100, 0, 100, 0, 100]) == 500',
    'assert candidate(nums = [4, 1, 2, 7, 5, 3, 9, 2, 8, 6, 4, 10, 1, 2, 5, 3, 7, 8, 6, 9]) == 60',
    'assert candidate(nums = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 10',
    'assert candidate(nums = [200, 100, 150, 50, 300, 100, 400, 200, 350, 150]) == 1400',
    'assert candidate(nums = [300, 200, 100, 50, 25, 10, 5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 458',
    'assert candidate(nums = [400, 399, 398, 397, 396, 395, 394, 393, 392, 391]) == 1980',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]) == 240',
    'assert candidate(nums = [400, 0, 400, 0, 400, 0, 400, 0, 400, 0]) == 2000',
    'assert candidate(nums = [10, 20, 10, 20, 10, 20, 10, 20, 10, 20]) == 100',
    'assert candidate(nums = [10, 1, 20, 3, 40, 5, 60, 7, 80]) == 210',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) == 64',
    'assert candidate(nums = [10, 5, 1, 2, 12, 4, 5, 6, 1, 2]) == 31',
    'assert candidate(nums = [100, 1, 1, 100, 1, 1, 100, 1, 1, 100]) == 400',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]) == 420',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0, 0, 0, 0, 400]) == 400',
    'assert candidate(nums = [1, 3, 1, 1, 3, 1, 1, 3, 1, 1]) == 10',
    'assert candidate(nums = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 16',
    'assert candidate(nums = [400, 300, 200, 100, 0, 0, 0, 0, 0, 0]) == 600',
    'assert candidate(nums = [100, 0, 50, 0, 200, 0, 300, 0, 400, 0]) == 1050',
    'assert candidate(nums = [300, 200, 100, 400, 300, 500, 400, 600, 500, 700]) == 2500',
    'assert candidate(nums = [150, 100, 120, 200, 180, 170, 160, 250, 300, 290]) == 1060',
    'assert candidate(nums = [300, 0, 400, 0, 300, 0]) == 1000',
    'assert candidate(nums = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 400]) == 435',
    'assert candidate(nums = [400, 300, 200, 100, 50, 40]) == 650',
    'assert candidate(nums = [300, 0, 0, 300, 0, 0, 300, 0, 0, 300]) == 1200',
    'assert candidate(nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]) == 55',
    'assert candidate(nums = [2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1]) == 14',
    'assert candidate(nums = [1, 3, 1, 5, 2, 2, 1, 3, 4]) == 14',
    'assert candidate(nums = [3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3]) == 21',
    'assert candidate(nums = [100, 200, 300, 400, 500, 600]) == 1200',
    'assert candidate(nums = [1, 3, 1, 3, 100, 1, 1, 1, 1, 1]) == 105',
    'assert candidate(nums = [400, 0, 400, 0, 400, 0, 400, 0, 400, 0, 400, 0, 400, 0, 400, 0, 400, 0, 400, 0]) == 4000',
    'assert candidate(nums = [5, 4, 3, 2, 1, 0, 9, 8, 7, 6]) == 25',
    'assert candidate(nums = [4, 2, 3, 6, 3, 8, 5, 10, 7]) == 28',
    'assert candidate(nums = [10, 15, 20, 25, 30, 35, 40, 45, 50, 55]) == 175',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) == 110',
    'assert candidate(nums = [399, 1, 399, 1, 399, 1, 399, 1, 399, 1]) == 1995',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate(nums = [3, 10, 3, 1, 2, 9, 5, 4, 6, 8, 1, 7]) == 39',
    'assert candidate(nums = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 30',
    'assert candidate(nums = [10, 5, 15, 20, 25, 30, 35, 40, 45, 50]) == 150',
    'assert candidate(nums = [100, 0, 100, 0, 100, 0, 100]) == 400',
    'assert candidate(nums = [3, 2, 5, 10, 7, 8, 5, 1, 100, 2, 5, 8, 5, 1, 100]) == 231',
    'assert candidate(nums = [1, 2, 3, 1, 1, 2, 3, 1, 1, 2]) == 10',
    'assert candidate(nums = [10, 5, 10, 5, 10, 5, 10, 5, 10, 5]) == 50',
    'assert candidate(nums = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]) == 128',
    'assert candidate(nums = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == 5',
    'assert candidate(nums = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) == 300',
    'assert candidate(nums = [1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]) == 30',
    'assert candidate(nums = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 60',
    'assert candidate(nums = [200, 100, 200, 200, 100, 300, 150, 250, 200, 100]) == 1050',
    'assert candidate(nums = [300, 1, 1, 300, 1, 1, 300, 1, 1, 300, 1, 1, 300, 1, 1, 300, 1, 1, 300, 1]) == 2100',
    'assert candidate(nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 30',
    'assert candidate(nums = [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]) == 7',
    'assert candidate(nums = [1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]) == 18',
    'assert candidate(nums = [300, 100, 200, 150, 250, 125, 350]) == 1100',
    'assert candidate(nums = [100, 1, 200, 3, 400, 5]) == 700',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate(nums = [150, 200, 50, 100, 100, 50, 200, 150, 100, 100, 50, 200, 150]) == 800',
    'assert candidate(nums = [100, 200, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) == 260',
    'assert candidate(nums = [300, 200, 100, 0, 50, 10, 20, 30, 40, 5]) == 510',
    'assert candidate(nums = [10, 22, 9, 33, 21, 50, 41, 60, 80, 70]) == 235',
    'assert candidate(nums = [50, 1, 50, 1, 50, 1, 50, 1, 50, 1]) == 250',
    'assert candidate(nums = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 5',
    'assert candidate(nums = [300, 200, 100, 400, 300, 500, 200]) == 1200',
    'assert candidate(nums = [300, 200, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 400',
    'assert candidate(nums = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate(nums = [50, 100, 200, 50, 100, 200, 50, 100, 200, 50]) == 650',
    'assert candidate(nums = [1, 10, 1, 10, 1, 10, 1, 10, 1, 10]) == 50',
    'assert candidate(nums = [1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1]) == 18',
    'assert candidate(nums = [50, 10, 40, 70, 30, 60, 20, 80, 100, 90]) == 350',
    'assert candidate(nums = [31, 41, 59, 26, 53, 58, 97, 93, 23, 84, 62, 64, 33, 83, 27, 95, 8, 41, 32, 9]) == 617',
    'assert candidate(nums = [400, 300, 200, 100, 0, 100, 200, 300, 400]) == 1200',
    'assert candidate(nums = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 90',
    'assert candidate(nums = [4, 1, 2, 7, 5, 3, 1, 1, 1, 2, 3, 4, 5]) == 23',
    'assert candidate(nums = [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]) == 20',
    'assert candidate(nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]) == 66',
    'assert candidate(nums = [3, 7, 5, 1, 9, 2, 6, 4]) == 23',
    'assert candidate(nums = [400, 399, 398, 397, 396, 395, 394, 393, 392, 391]) == 1980',
    'assert candidate(nums = [4, 1, 2, 7, 5, 3, 1, 1, 1, 1]) == 16',
    'assert candidate(nums = [10, 15, 10, 5, 10, 15, 10, 5, 10, 15]) == 55',
    'assert candidate(nums = [10, 5, 10, 5, 15, 20]) == 40',
    'assert candidate(nums = [2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2]) == 10',
    'assert candidate(nums = [10, 0, 0, 0, 0, 10, 0, 0, 0, 0, 10]) == 30',
    'assert candidate(nums = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]) == 3000',
    'assert candidate(nums = [3, 5, 100, 1, 1, 1, 1, 1, 100, 1, 1, 5, 3]) == 210',
    'assert candidate(nums = [8, 2, 8, 10, 6, 5, 1, 9, 3, 7, 4, 2, 5]) == 44',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().rob)
