# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for insert-interval
_test_lines = [
    'assert candidate(intervals = [[1, 5]],newInterval = [2, 3]) == [[1, 5]]',
    'assert candidate(intervals = [[1, 5]],newInterval = [0, 3]) == [[0, 5]]',
    'assert candidate(intervals = [[1, 2], [3, 10], [12, 16]],newInterval = [10, 11]) == [[1, 2], [3, 11], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8]],newInterval = [1, 8]) == [[1, 8]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [13, 14]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 3], [5, 7]],newInterval = [4, 4]) == [[1, 3], [4, 4], [5, 7]]',
    'assert candidate(intervals = [],newInterval = [5, 7]) == [[5, 7]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8]],newInterval = [0, 9]) == [[0, 9]]',
    'assert candidate(intervals = [[1, 3], [6, 9]],newInterval = [10, 12]) == [[1, 3], [6, 9], [10, 12]]',
    'assert candidate(intervals = [[1, 3], [5, 7]],newInterval = [4, 6]) == [[1, 3], [4, 7]]',
    'assert candidate(intervals = [[1, 5]],newInterval = [0, 0]) == [[0, 0], [1, 5]]',
    'assert candidate(intervals = [[1, 5]],newInterval = [6, 8]) == [[1, 5], [6, 8]]',
    'assert candidate(intervals = [[1, 3], [6, 9]],newInterval = [2, 5]) == [[1, 5], [6, 9]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [4, 8]) == [[1, 2], [3, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [5, 6], [9, 10], [14, 15], [19, 20]],newInterval = [3, 18]) == [[1, 2], [3, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 3], [8, 10], [15, 17]],newInterval = [4, 6]) == [[1, 3], [4, 6], [8, 10], [15, 17]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [1, 3]) == [[1, 4], [5, 6], [7, 8], [9, 10]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25], [30, 35]],newInterval = [6, 14]) == [[1, 5], [6, 15], [20, 25], [30, 35]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8]],newInterval = [3, 3]) == [[1, 2], [3, 3], [4, 5], [7, 8]]',
    'assert candidate(intervals = [[2, 3], [5, 6], [8, 9], [11, 12], [14, 15]],newInterval = [7, 13]) == [[2, 3], [5, 6], [7, 13], [14, 15]]',
    'assert candidate(intervals = [],newInterval = [0, 0]) == [[0, 0]]',
    'assert candidate(intervals = [[1, 3], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [14, 16]) == [[1, 3], [4, 6], [8, 10], [12, 18]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [2, 16]) == [[1, 16], [17, 19]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [1, 18]) == [[1, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 4], [7, 10], [12, 16], [20, 24]],newInterval = [5, 18]) == [[1, 4], [5, 18], [20, 24]]',
    'assert candidate(intervals = [[1, 2], [6, 7], [11, 12]],newInterval = [5, 6]) == [[1, 2], [5, 7], [11, 12]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [0, 20]) == [[0, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [0, 20]) == [[0, 20]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [4, 11]) == [[1, 3], [4, 11], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 4], [9, 10], [11, 12], [13, 14]],newInterval = [5, 13]) == [[1, 4], [5, 14]]',
    'assert candidate(intervals = [[0, 2], [3, 6], [8, 10], [12, 14], [16, 19]],newInterval = [1, 18]) == [[0, 19]]',
    'assert candidate(intervals = [[1, 2]],newInterval = [3, 4]) == [[1, 2], [3, 4]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14]],newInterval = [1, 14]) == [[1, 14]]',
    'assert candidate(intervals = [[5, 10], [15, 20], [25, 30], [35, 40]],newInterval = [22, 28]) == [[5, 10], [15, 20], [22, 30], [35, 40]]',
    'assert candidate(intervals = [[1, 3], [8, 10], [15, 17], [20, 22]],newInterval = [4, 9]) == [[1, 3], [4, 10], [15, 17], [20, 22]]',
    'assert candidate(intervals = [[1, 2], [3, 6], [8, 10], [12, 15]],newInterval = [7, 9]) == [[1, 2], [3, 6], [7, 10], [12, 15]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [11, 15]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 15]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [2, 18]) == [[1, 19]]',
    'assert candidate(intervals = [[1, 2], [4, 7], [8, 10], [12, 15], [17, 20]],newInterval = [3, 18]) == [[1, 2], [3, 20]]',
    'assert candidate(intervals = [[1, 100], [200, 300], [400, 500]],newInterval = [150, 250]) == [[1, 100], [150, 300], [400, 500]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25], [30, 35]],newInterval = [5, 30]) == [[1, 35]]',
    'assert candidate(intervals = [[1, 3], [5, 8], [10, 15], [16, 20]],newInterval = [4, 18]) == [[1, 3], [4, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16], [19, 20]],newInterval = [10, 19]) == [[1, 2], [3, 5], [6, 7], [8, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [2, 16]) == [[1, 16]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [17, 20]) == [[1, 3], [5, 7], [8, 10], [12, 14], [16, 20]]',
    'assert candidate(intervals = [[1, 3], [6, 9], [12, 15], [18, 21], [24, 27]],newInterval = [5, 20]) == [[1, 3], [5, 21], [24, 27]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [8, 14]) == [[1, 3], [5, 7], [8, 15], [17, 19]]',
    'assert candidate(intervals = [[1, 2], [5, 6], [9, 10], [13, 14], [17, 18]],newInterval = [3, 15]) == [[1, 2], [3, 15], [17, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [17, 20]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16], [17, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [7, 15]) == [[1, 2], [3, 5], [6, 16]]',
    'assert candidate(intervals = [],newInterval = [1, 5]) == [[1, 5]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [0, 15]) == [[0, 15]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14]],newInterval = [4, 11]) == [[1, 3], [4, 11], [12, 14]]',
    'assert candidate(intervals = [[1, 10], [20, 30], [40, 50]],newInterval = [15, 25]) == [[1, 10], [15, 30], [40, 50]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [3, 12]) == [[1, 2], [3, 16]]',
    'assert candidate(intervals = [[1, 10000]],newInterval = [5000, 15000]) == [[1, 15000]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 8], [9, 10], [12, 14], [16, 18]],newInterval = [3, 13]) == [[1, 2], [3, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25], [30, 35]],newInterval = [18, 22]) == [[1, 5], [10, 15], [18, 25], [30, 35]]',
    'assert candidate(intervals = [[5, 7], [10, 12], [15, 17], [20, 22]],newInterval = [8, 19]) == [[5, 7], [8, 19], [20, 22]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [3, 17]) == [[1, 2], [3, 18], [19, 20]]',
    'assert candidate(intervals = [[3, 5], [10, 12], [15, 18]],newInterval = [6, 11]) == [[3, 5], [6, 12], [15, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [1, 3]) == [[1, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [0, 0]) == [[0, 0], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]',
    'assert candidate(intervals = [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]],newInterval = [0, 6]) == [[0, 6]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [3, 5]) == [[1, 2], [3, 6], [8, 10], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [10, 11]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 11]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [2, 9]) == [[1, 10]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18], [20, 22], [24, 26], [28, 30]],newInterval = [3, 27]) == [[1, 2], [3, 27], [28, 30]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [0, 17]) == [[0, 17]]',
    'assert candidate(intervals = [[1, 2], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [3, 12]) == [[1, 2], [3, 12], [13, 15], [17, 19]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [5, 10]) == [[1, 2], [3, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [6, 12]) == [[1, 2], [3, 5], [6, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]],newInterval = [1, 12]) == [[1, 12]]',
    'assert candidate(intervals = [[1, 5], [6, 10], [11, 15], [16, 20]],newInterval = [1, 20]) == [[1, 20]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [18, 20]) == [[1, 3], [5, 7], [8, 10], [12, 14], [16, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [7, 13]) == [[1, 2], [3, 4], [5, 6], [7, 14], [15, 16], [17, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18], [20, 22], [24, 26], [28, 30]],newInterval = [5, 25]) == [[1, 2], [4, 26], [28, 30]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15]],newInterval = [2, 14]) == [[1, 15]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [7, 9], [11, 13], [15, 17], [19, 21]],newInterval = [5, 16]) == [[1, 2], [3, 4], [5, 17], [19, 21]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [5, 9]) == [[1, 2], [4, 10], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [15, 20]],newInterval = [4, 10]) == [[1, 3], [4, 11], [15, 20]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [6, 9]) == [[1, 3], [5, 11], [13, 15], [17, 19]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [1, 9]) == [[1, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 4], [6, 8], [10, 12], [14, 16]],newInterval = [5, 15]) == [[1, 4], [5, 16]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18], [20, 22], [24, 26], [28, 30]],newInterval = [1, 30]) == [[1, 30]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 9], [11, 13], [15, 17], [19, 21]],newInterval = [4, 18]) == [[1, 2], [3, 18], [19, 21]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [10, 11], [13, 14], [16, 17], [19, 20]],newInterval = [3, 19]) == [[1, 2], [3, 20]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [10, 11], [13, 14], [16, 17], [19, 20]],newInterval = [6, 18]) == [[1, 2], [4, 5], [6, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25], [30, 35], [40, 45]],newInterval = [22, 33]) == [[1, 5], [10, 15], [20, 35], [40, 45]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 7], [9, 10]],newInterval = [3, 8]) == [[1, 2], [3, 8], [9, 10]]',
    'assert candidate(intervals = [[1, 3], [5, 6], [7, 8], [11, 12], [13, 14]],newInterval = [2, 10]) == [[1, 10], [11, 12], [13, 14]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [14, 16]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8]],newInterval = [5, 7]) == [[1, 2], [4, 8]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [4, 10]) == [[1, 3], [4, 11], [13, 15], [17, 19]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [15, 17]) == [[1, 3], [5, 7], [8, 10], [12, 14], [15, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [2, 19]) == [[1, 20]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 7], [9, 10], [12, 13]],newInterval = [3, 8]) == [[1, 2], [3, 8], [9, 10], [12, 13]]',
    'assert candidate(intervals = [[1, 10], [15, 20], [25, 30], [35, 40]],newInterval = [12, 28]) == [[1, 10], [12, 30], [35, 40]]',
    'assert candidate(intervals = [[1, 100]],newInterval = [50, 50]) == [[1, 100]]',
    'assert candidate(intervals = [[1, 10], [15, 20], [25, 30]],newInterval = [11, 19]) == [[1, 10], [11, 20], [25, 30]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [0, 1]) == [[0, 3], [5, 7], [8, 10], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2]],newInterval = [0, 0]) == [[0, 0], [1, 2]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [0, 0]) == [[0, 0], [1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [0, 11]) == [[0, 11]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [5, 13]) == [[1, 2], [4, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 3], [6, 9], [11, 12], [15, 18], [20, 22]],newInterval = [13, 16]) == [[1, 3], [6, 9], [11, 12], [13, 18], [20, 22]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25]],newInterval = [6, 19]) == [[1, 5], [6, 19], [20, 25]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [15, 16]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [10, 11], [13, 14]],newInterval = [3, 12]) == [[1, 2], [3, 12], [13, 14]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [0, 1]) == [[0, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [10, 11]) == [[1, 2], [3, 5], [6, 7], [8, 11], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [10, 10]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [11, 12]) == [[1, 3], [5, 7], [8, 10], [11, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [11, 12]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [10, 12], [15, 18]],newInterval = [6, 11]) == [[1, 3], [5, 12], [15, 18]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 7], [9, 10], [12, 13]],newInterval = [3, 11]) == [[1, 2], [3, 11], [12, 13]]',
    'assert candidate(intervals = [[1, 2]],newInterval = [2, 2]) == [[1, 2]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [15, 18]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 18]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 12], [15, 18]],newInterval = [4, 11]) == [[1, 3], [4, 12], [15, 18]]',
    'assert candidate(intervals = [[1, 10], [14, 20], [22, 30], [32, 40]],newInterval = [12, 28]) == [[1, 10], [12, 30], [32, 40]]',
    'assert candidate(intervals = [[1, 2], [10, 15], [20, 25], [30, 35]],newInterval = [5, 19]) == [[1, 2], [5, 19], [20, 25], [30, 35]]',
    'assert candidate(intervals = [[1, 50]],newInterval = [25, 75]) == [[1, 75]]',
    'assert candidate(intervals = [[1, 2], [4, 10], [15, 20], [25, 30]],newInterval = [5, 18]) == [[1, 2], [4, 20], [25, 30]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [19, 20]) == [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [8, 9], [12, 13], [16, 17], [20, 21]],newInterval = [6, 14]) == [[1, 2], [4, 5], [6, 14], [16, 17], [20, 21]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [5, 15]) == [[1, 2], [3, 16]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 7], [9, 10], [12, 13]],newInterval = [5, 9]) == [[1, 2], [4, 10], [12, 13]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [11, 11]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 11]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 7], [8, 9], [10, 11]],newInterval = [5, 6]) == [[1, 2], [4, 7], [8, 9], [10, 11]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [17, 20]) == [[1, 2], [4, 6], [8, 10], [12, 14], [16, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [12, 13]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [0, 1]) == [[0, 2], [3, 4], [5, 6], [7, 8], [9, 10]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [9, 11]) == [[1, 2], [3, 4], [5, 6], [7, 8], [9, 12], [13, 14], [15, 16], [17, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [10, 18]) == [[1, 2], [3, 5], [6, 7], [8, 18]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [11, 12]],newInterval = [3, 10]) == [[1, 2], [3, 10], [11, 12]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [8, 10], [12, 14], [16, 18]],newInterval = [14, 15]) == [[1, 3], [5, 7], [8, 10], [12, 15], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [6, 7], [11, 12]],newInterval = [3, 5]) == [[1, 2], [3, 5], [6, 7], [11, 12]]',
    'assert candidate(intervals = [[1, 2], [5, 10], [15, 20], [25, 30], [35, 40]],newInterval = [0, 45]) == [[0, 45]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19]],newInterval = [0, 20]) == [[0, 20]]',
    'assert candidate(intervals = [[1, 3], [6, 10], [14, 16], [19, 22], [24, 26]],newInterval = [11, 15]) == [[1, 3], [6, 10], [11, 16], [19, 22], [24, 26]]',
    'assert candidate(intervals = [],newInterval = [1, 2]) == [[1, 2]]',
    'assert candidate(intervals = [[1, 3], [5, 6], [8, 10], [12, 14], [16, 18]],newInterval = [7, 13]) == [[1, 3], [5, 6], [7, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [6, 7], [11, 12]],newInterval = [1, 17]) == [[1, 17]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [10, 12], [14, 16], [18, 20]],newInterval = [3, 17]) == [[1, 2], [3, 17], [18, 20]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14]],newInterval = [3, 7]) == [[1, 2], [3, 7], [8, 10], [12, 14]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [8, 10], [12, 14], [16, 18]],newInterval = [6, 11]) == [[1, 2], [4, 5], [6, 11], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [1, 20]) == [[1, 20]]',
    'assert candidate(intervals = [[1, 3], [5, 7], [9, 11], [13, 15], [17, 19], [21, 23], [25, 27], [29, 31]],newInterval = [4, 29]) == [[1, 3], [4, 31]]',
    'assert candidate(intervals = [[1, 5], [10, 15], [20, 25], [30, 35], [40, 45]],newInterval = [26, 34]) == [[1, 5], [10, 15], [20, 25], [26, 35], [40, 45]]',
    'assert candidate(intervals = [[0, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [3, 15]) == [[0, 2], [3, 15], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [9, 15]) == [[1, 2], [4, 6], [8, 15], [16, 18]]',
    'assert candidate(intervals = [[1, 3], [6, 9], [13, 17], [20, 24], [27, 30]],newInterval = [11, 22]) == [[1, 3], [6, 9], [11, 24], [27, 30]]',
    'assert candidate(intervals = [[1, 3], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [2, 4]) == [[1, 6], [8, 10], [12, 14], [16, 18]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8]],newInterval = [0, 1]) == [[0, 2], [4, 5], [7, 8]]',
    'assert candidate(intervals = [[1, 2], [5, 8], [10, 15], [20, 25]],newInterval = [3, 23]) == [[1, 2], [3, 25]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [7, 8], [10, 11], [13, 14], [16, 17]],newInterval = [3, 12]) == [[1, 2], [3, 12], [13, 14], [16, 17]]',
    'assert candidate(intervals = [[1, 2], [4, 5], [6, 10], [12, 18], [20, 25]],newInterval = [3, 11]) == [[1, 2], [3, 11], [12, 18], [20, 25]]',
    'assert candidate(intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]],newInterval = [16, 16]) == [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]',
    'assert candidate(intervals = [[1, 2], [4, 6], [8, 10], [12, 14], [16, 18]],newInterval = [15, 17]) == [[1, 2], [4, 6], [8, 10], [12, 14], [15, 18]]',
    'assert candidate(intervals = [[1, 3], [6, 9], [12, 15], [18, 21], [24, 27]],newInterval = [10, 25]) == [[1, 3], [6, 9], [10, 27]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]],newInterval = [8, 10]) == [[1, 2], [3, 4], [5, 6], [7, 10]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],newInterval = [0, 16]) == [[0, 16]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]],newInterval = [5, 15]) == [[1, 2], [3, 4], [5, 16], [17, 18], [19, 20]]',
    'assert candidate(intervals = [[1, 3], [6, 9], [13, 17], [20, 24], [27, 30], [33, 37], [40, 45]],newInterval = [11, 34]) == [[1, 3], [6, 9], [11, 37], [40, 45]]',
    'assert candidate(intervals = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],newInterval = [1, 16]) == [[1, 16]]',
    'assert candidate(intervals = [[1, 2]],newInterval = [0, 3]) == [[0, 3]]',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().insert)
