# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for koko-eating-bananas
_test_lines = [
    'assert candidate([1, 2, 3], 5) == 2',
    'assert candidate([805306400, 805306400, 805306400], 3000000000) == 1',
    'assert candidate([1000000000], 1000000000) == 1',
    'assert candidate([805306457, 805306457, 805306457], 1000000000) == 3',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 5) == 2',
    'assert candidate([30, 11, 23, 4, 20], 5) == 30',
    'assert candidate([805306457, 933693859, 908256970, 820324087, 610103336], 5) == 933693859',
    'assert candidate([1, 1, 1, 1], 4) == 1',
    'assert candidate([10, 10, 10, 10], 10) == 5',
    'assert candidate([3, 3, 3, 3, 3], 5) == 3',
    'assert candidate([3, 3, 3, 3, 3], 10) == 2',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 1',
    'assert candidate([3, 6, 7, 11], 10) == 3',
    'assert candidate([1], 1) == 1',
    'assert candidate([3, 6, 7, 11], 8) == 4',
    'assert candidate([8, 9, 7, 4, 2], 3) == 10',
    'assert candidate([1, 999999999], 2) == 999999999',
    'assert candidate([1, 2, 3], 3) == 3',
    'assert candidate([805306368, 805306368, 805306368], 1000000000) == 3',
    'assert candidate([1000000000, 1000000000, 1000000000], 3) == 1000000000',
    'assert candidate([30, 11, 23, 4, 20], 6) == 23',
    'assert candidate([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], 10) == 3',
    'assert candidate([1, 1, 1, 1, 1], 5) == 1',
    'assert candidate([30, 11, 23, 4, 20, 35], 7) == 30',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10) == 10',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 20) == 35',
    'assert candidate([1000000000, 1000000000, 1000000000, 1000000000, 1000000000], 5) == 1000000000',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 10) == 19',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 10) == 10',
    'assert candidate([5, 8, 6, 29, 33, 12], 9) == 15',
    'assert candidate([5, 8, 6, 12, 20], 5) == 20',
    'assert candidate([5, 8, 10, 12, 15, 17, 20, 23, 25, 28, 30, 33, 35, 38, 40], 15) == 40',
    'assert candidate([332484035, 524908576, 855865114, 632739624, 265801521], 8) == 427932557',
    'assert candidate([312884470], 312884469) == 2',
    'assert candidate([3, 6, 7, 11, 30, 20], 15) == 6',
    'assert candidate([5, 8, 6, 3], 15) == 2',
    'assert candidate([10, 10, 10, 10, 10, 10, 10, 10, 10, 10], 5) == 11',
    'assert candidate([1000000000, 999999999, 888888888, 777777777], 10) == 444444444',
    'assert candidate([1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000], 9) == 100000000',
    'assert candidate([1, 10, 100, 1000, 10000, 100000], 6) == 100000',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 100) == 1',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 10) == 10',
    'assert candidate([3, 6, 7, 11, 20, 25, 30], 15) == 9',
    'assert candidate([50, 25, 75, 25, 100, 50, 25, 75, 25, 100, 50, 25, 75, 25, 100, 50, 25, 75, 25, 100], 50) == 25',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 15) == 15',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1], 9) == 9',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 20) == 20',
    'assert candidate([1, 10, 100, 1000, 10000, 100000, 1000000], 14) == 125000',
    'assert candidate([1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000], 25) == 66666667',
    'assert candidate([10, 20, 30, 40, 50], 100) == 2',
    'assert candidate([5, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30], 15) == 26',
    'assert candidate([1000000000, 1, 1000000000, 1, 1000000000], 1000000000) == 4',
    'assert candidate([3, 6, 7, 11, 11, 11, 11, 11, 11, 11], 10) == 11',
    'assert candidate([3, 6, 7, 11, 20, 30, 40, 50, 60, 70, 80, 90, 100], 15) == 80',
    'assert candidate([5, 8, 6, 7, 1, 2, 3, 4, 5], 9) == 8',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 100) == 3',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1], 5) == 10',
    'assert candidate([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10], 20) == 10',
    'assert candidate([100, 200, 300, 400, 500], 50) == 32',
    'assert candidate([1000000000, 1000000000, 1000000000], 3) == 1000000000',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 10) == 10',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 2',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000], 100) == 234',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 10) == 6',
    'assert candidate([300000000, 100000000, 200000000, 400000000, 500000000], 1000000000) == 2',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 100) == 1',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 5) == 11',
    'assert candidate([5, 4, 3, 2, 1], 15) == 1',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 10) == 100',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 9) == 20',
    'assert candidate([1, 10, 100, 1000, 10000], 10) == 1667',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1) == 2',
    'assert candidate([100, 150, 200, 250, 300, 350, 400], 15) == 150',
    'assert candidate([100000000, 200000000, 300000000, 400000000, 500000000], 5) == 500000000',
    'assert candidate([3, 6, 7, 11, 100, 101, 200], 20) == 26',
    'assert candidate([8, 5, 6, 10, 12], 7) == 8',
    'assert candidate([100, 100, 100, 100, 100, 100, 100, 100, 100, 100], 10) == 100',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 50) == 120',
    'assert candidate([100, 100, 100, 100, 100], 10) == 50',
    'assert candidate([1000000000, 1000000000, 1000000000], 1000000000) == 4',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 19) == 2',
    'assert candidate([50, 50, 50, 50, 50, 50, 50, 50, 50, 50], 100) == 5',
    'assert candidate([332484035, 524900671, 855865114, 632088198, 232463062], 8) == 427932557',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 10) == 5',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 15) == 10',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 9) == 11',
    'assert candidate([10, 15, 20, 25, 30, 35, 40], 20) == 10',
    'assert candidate([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000], 10000) == 1',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 5) == 101',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 15) == 50',
    'assert candidate([805306368, 805306368, 805306368], 1000000000) == 3',
    'assert candidate([900000000, 800000000, 700000000, 600000000, 500000000], 5) == 900000000',
    'assert candidate([8, 5, 4, 10, 7, 9, 6], 15) == 4',
    'assert candidate([5, 10, 15, 20, 25, 30, 35, 40, 45, 50], 15) == 25',
    'assert candidate([10, 15, 7, 30], 6) == 15',
    'assert candidate([3, 6, 7, 11, 33, 45, 55], 25) == 7',
    'assert candidate([8, 12, 15, 18, 22], 12) == 8',
    'assert candidate([3, 6, 7, 11, 11, 11, 11, 11, 11, 11], 20) == 6',
    'assert candidate([10, 20, 30, 40, 50], 20) == 9',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 9) == 11',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 5) == 2',
    'assert candidate([1000000000, 1000000000, 1000000000], 3000000000) == 1',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 20) == 1',
    'assert candidate([3, 6, 7, 11, 20, 25, 30], 25) == 5',
    'assert candidate([1000000000, 1000000000, 1000000000, 1000000000, 1000000000, 1000000000, 1000000000, 1000000000], 32) == 250000000',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 5) == 20',
    'assert candidate([999999999, 999999998, 999999997, 999999996, 999999995], 10) == 500000000',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 15) == 21',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5) == 11',
    'assert candidate([33, 41, 17, 29, 38, 36, 40, 9, 66, 27], 13) == 38',
    'assert candidate([1000000000, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 1000000000',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 9) == 20',
    'assert candidate([30, 11, 23, 4, 20], 7) == 20',
    'assert candidate([8, 8, 8, 8, 8, 8, 8, 8, 8, 8], 5) == 9',
    'assert candidate([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30], 20) == 20',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 5) == 11',
    'assert candidate([987654321, 123456789, 987654321, 123456789, 987654321], 5) == 987654321',
    'assert candidate([10, 10, 10, 10, 10, 10, 10, 10, 10, 10], 1) == 11',
    'assert candidate([2, 4, 9, 16, 25, 36, 49, 64, 81, 100], 15) == 41',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 25) == 27',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 1',
    'assert candidate([1, 100, 1, 100, 1, 100, 1, 100, 1, 100, 1, 100, 1, 100, 1, 100, 1, 100, 1, 100], 20) == 100',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 1) == 11',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 20) == 4',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().minEatingSpeed)
