# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for longest-palindromic-substring
_test_lines = [
    'assert candidate(s = "abba") == "abba"',
    'assert candidate(s = "aaaa") == "aaaa"',
    'assert candidate(s = "abacdfgdcaba") == "aba"',
    'assert candidate(s = "ac") == "a"',
    'assert candidate(s = "babad") == "aba"',
    'assert candidate(s = "noon") == "noon"',
    'assert candidate(s = "cbbd") == "bb"',
    'assert candidate(s = "abcba") == "abcba"',
    'assert candidate(s = "bcbabcbabcba") == "bcbabcbabcb"',
    'assert candidate(s = "noonhighnoon") == "noon"',
    'assert candidate(s = "forgeeksskeegfor") == "geeksskeeg"',
    'assert candidate(s = "aaabaaaa") == "aaabaaa"',
    'assert candidate(s = "abcdedcba") == "abcdedcba"',
    'assert candidate(s = "aaa") == "aaa"',
    'assert candidate(s = "aaaaa") == "aaaaa"',
    'assert candidate(s = "racecar") == "racecar"',
    'assert candidate(s = "a") == "a"',
    'assert candidate(s = "abcdefg") == "a"',
    'assert candidate(s = "aabbccddeeeffgg") == "eee"',
    'assert candidate(s = "abcdedcba12321") == "abcdedcba"',
    'assert candidate(s = "xxyyyxyxyxyxyxyxxyyxyxyxyxyxyx") == "xyxyxyxyxyx"',
    'assert candidate(s = "thisisanexamplewithlongestpalindromeonyxdxyxdx") == "xdxyxdx"',
    'assert candidate(s = "12345678987654321") == "12345678987654321"',
    'assert candidate(s = "xyzaaazyxzyzyxyz") == "xyzaaazyx"',
    'assert candidate(s = "12321abcdcba45654") == "abcdcba"',
    'assert candidate(s = "012210") == "012210"',
    'assert candidate(s = "tattarrattat") == "tattarrattat"',
    'assert candidate(s = "aabbabbaa") == "aabbabbaa"',
    'assert candidate(s = "abacdfgdcaba12321") == "12321"',
    'assert candidate(s = "xyxxyxyxyxyxyxyx") == "xyxyxyxyxyxyx"',
    'assert candidate(s = "1234321abcdefghgfedcba") == "abcdefghgfedcba"',
    'assert candidate(s = "abababababababababababababababababababababababababababababababab") == "bababababababababababababababababababababababababababababababab"',
    'assert candidate(s = "abacdfgdcabaxxxabcdcba") == "abcdcba"',
    'assert candidate(s = "12321abccba45654") == "abccba"',
    'assert candidate(s = "12321abcdedcbavcvcv") == "abcdedcba"',
    'assert candidate(s = "abcbaekayakecivic") == "ekayake"',
    'assert candidate(s = "noonmoonnoon") == "oonnoo"',
    'assert candidate(s = "abcbaxxxxxabcdcba") == "cbaxxxxxabc"',
    'assert candidate(s = "noonhighnoonnoon") == "noonnoon"',
    'assert candidate(s = "noonmidnightnoon") == "noon"',
    'assert candidate(s = "abcba12321defedcba") == "defed"',
    'assert candidate(s = "aabbabaaaabbaaabaaabbbbbaaaaaabbbaaaabbbbaaabbaabbbaaaabbbaaabbbbaaabbaabbaabbab") == "bbaaabbbbaaabb"',
    'assert candidate(s = "ababababababababa") == "ababababababababa"',
    'assert candidate(s = "noonnoonnoonnoonnoonnoon") == "noonnoonnoonnoonnoonnoon"',
    'assert candidate(s = "abccbaabacdfgdcaba") == "abccba"',
    'assert candidate(s = "racecarxracecar") == "racecarxracecar"',
    'assert candidate(s = "madamracecarlevel") == "racecar"',
    'assert candidate(s = "babcbabcbabcba") == "abcbabcbabcba"',
    'assert candidate(s = "abacdfgdcabaabacdfgdcaba") == "dcabaabacd"',
    'assert candidate(s = "madamintanimadaminabba") == "animadamina"',
    'assert candidate(s = "noonracecarracecar") == "racecarracecar"',
    'assert candidate(s = "zzzzzzzzzzzz") == "zzzzzzzzzzzz"',
    'assert candidate(s = "racecar2racecar") == "racecar2racecar"',
    'assert candidate(s = "zxyabcddcbaabczyx") == "abcddcba"',
    'assert candidate(s = "deeee") == "eeee"',
    'assert candidate(s = "abacdfgdcabacdfgdcaba") == "dcabacd"',
    'assert candidate(s = "1234543216789876") == "123454321"',
    'assert candidate(s = "abcbaaabcba") == "abcbaaabcba"',
    'assert candidate(s = "abcdedcbaefghihgfexyzzyx") == "efghihgfe"',
    'assert candidate(s = "abcdefgfebac") == "efgfe"',
    'assert candidate(s = "levelhannahlevel") == "levelhannahlevel"',
    'assert candidate(s = "xxyyzzzyyxx") == "xxyyzzzyyxx"',
    'assert candidate(s = "abcddcbaabcddcbaxyzzyx") == "abcddcbaabcddcba"',
    'assert candidate(s = "racecar12321racecar") == "racecar12321racecar"',
    'assert candidate(s = "abcdeffedcba") == "abcdeffedcba"',
    'assert candidate(s = "civicracecar") == "racecar"',
    'assert candidate(s = "levelmadammadam") == "madammadam"',
    'assert candidate(s = "zxyaxzyaz") == "z"',
    'assert candidate(s = "abcdefedcba") == "abcdefedcba"',
    'assert candidate(s = "12321321321321321") == "12321"',
    'assert candidate(s = "xyzzyxcbaapqrqpabczyzyx") == "apqrqpa"',
    'assert candidate(s = "abacdfgdcaba123321") == "123321"',
    'assert candidate(s = "abacdfgdcabaxxxxxabcdcba") == "baxxxxxab"',
    'assert candidate(s = "aabcdcbadefedcbaa") == "abcdcba"',
    'assert candidate(s = "abcdefghijiklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == "klmnopqrstuvwxyzzyxwvutsrqponmlk"',
    'assert candidate(s = "bananaananab") == "bananaananab"',
    'assert candidate(s = "aabbccddeedcba") == "deed"',
    'assert candidate(s = "noonhighnoonnoonhighnoon") == "hnoonnoonh"',
    'assert candidate(s = "babaddabba") == "baddab"',
    'assert candidate(s = "abababababababababababababababababababababababababababababababbababa") == "babababababababababababababababababababababababababababababab"',
    'assert candidate(s = "abcdeedcba1234321xyzzyx") == "abcdeedcba"',
    'assert candidate(s = "aabb") == "bb"',
    'assert candidate(s = "mamamamamamamamama") == "amamamamamamamama"',
    'assert candidate(s = "abcdefgfedcba") == "abcdefgfedcba"',
    'assert candidate(s = "abcbabcba") == "abcbabcba"',
    'assert candidate(s = "xyzzzzyxabcdefedcba") == "abcdefedcba"',
    'assert candidate(s = "banana") == "anana"',
    'assert candidate(s = "abcbcbcbcbcbcbcbcbcbcbcbcb") == "bcbcbcbcbcbcbcbcbcbcbcbcb"',
    'assert candidate(s = "anana") == "anana"',
    'assert candidate(s = "aabbccddeeeeddccbbbaa") == "bbccddeeeeddccbb"',
    'assert candidate(s = "12321abcdedcba45654") == "abcdedcba"',
    'assert candidate(s = "aabbccddeeffgg") == "gg"',
    'assert candidate(s = "levelracecardeifiedracecar") == "racecardeifiedracecar"',
    'assert candidate(s = "aaaaabbbbbaaaa") == "aaaabbbbbaaaa"',
    'assert candidate(s = "abccba") == "abccba"',
    'assert candidate(s = "abcdcba12321xyzzyx") == "abcdcba"',
    'assert candidate(s = "12321abcba21321") == "abcba"',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == "zz"',
    'assert candidate(s = "abcdcbaxxxabcdcbaabcdcbaxxxabcdcba") == "abcdcbaxxxabcdcbaabcdcbaxxxabcdcba"',
    'assert candidate(s = "xyzabcbaxyz") == "abcba"',
    'assert candidate(s = "racecarannakayak") == "racecar"',
    'assert candidate(s = "abacdfgdcab") == "aba"',
    'assert candidate(s = "abcdeedcbafedcbe") == "abcdeedcba"',
    'assert candidate(s = "a1b2c3d4c3b2a") == "a"',
    'assert candidate(s = "abccccba") == "abccccba"',
    'assert candidate(s = "noonnoonnoon") == "noonnoonnoon"',
    'assert candidate(s = "aabbccddeeeedddccbaa") == "ddeeeedd"',
    'assert candidate(s = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz") == "A"',
    'assert candidate(s = "acbbac") == "bb"',
    'assert candidate(s = "noonlevelnoon") == "noonlevelnoon"',
    'assert candidate(s = "abbaabba") == "abbaabba"',
    'assert candidate(s = "rotor1234321rotor") == "rotor1234321rotor"',
    'assert candidate(s = "aaaaabaaa") == "aaabaaa"',
    'assert candidate(s = "abcdefghihgfedcba") == "abcdefghihgfedcba"',
    'assert candidate(s = "civicdeifiedrotorlevel") == "deified"',
    'assert candidate(s = "aquickbrownfoxjumpsoverthelazydog") == "a"',
    'assert candidate(s = "zyxwvutsrqponmlkjihgfedcbaedcba") == "z"',
    'assert candidate(s = "aabcddeffedcba") == "deffed"',
    'assert candidate(s = "pppppppppppppppppppppppppppppppp") == "pppppppppppppppppppppppppppppppp"',
    'assert candidate(s = "aabbccddeeeedddccbbaa") == "ddeeeedd"',
    'assert candidate(s = "a1b2c3d4e5f6g7h8i9j0j9i8h7g6f5e4d3c2b1a") == "a1b2c3d4e5f6g7h8i9j0j9i8h7g6f5e4d3c2b1a"',
    'assert candidate(s = "mississippi") == "ississi"',
    'assert candidate(s = "zxcvbnmlkjhgfdsapoiuytrewqpoiuytrewqpoiuytrewqpoiuytrewq") == "z"',
    'assert candidate(s = "deifiedrotorlevel") == "deified"',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().longestPalindrome)
