# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for longest-common-subsequence
_test_lines = [
    'assert candidate(text1 = "a",text2 = "b") == 0',
    'assert candidate(text1 = "xyz",text2 = "zyx") == 1',
    'assert candidate(text1 = "ezupkr",text2 = "ubmrapg") == 2',
    'assert candidate(text1 = "abcde",text2 = "ace") == 3',
    'assert candidate(text1 = "abc",text2 = "def") == 0',
    'assert candidate(text1 = "aabcc",text2 = "dbbca") == 2',
    'assert candidate(text1 = "programming",text2 = "gaming") == 6',
    'assert candidate(text1 = "ylqpfxxqy",text2 = "wxqxalnnsow") == 2',
    'assert candidate(text1 = "pqr",text2 = "stu") == 0',
    'assert candidate(text1 = "abcdgh",text2 = "aedfhr") == 3',
    'assert candidate(text1 = "hofubmnyg",text2 = "hvmpywxck") == 3',
    'assert candidate(text1 = "abcdef",text2 = "z") == 0',
    'assert candidate(text1 = "mhunuzqrkz",text2 = "dhlmfpnqjk") == 4',
    'assert candidate(text1 = "abcdefg",text2 = "abdfg") == 5',
    'assert candidate(text1 = "a",text2 = "a") == 1',
    'assert candidate(text1 = "abc",text2 = "") == 0',
    'assert candidate(text1 = "xyz",text2 = "abc") == 0',
    'assert candidate(text1 = "",text2 = "abc") == 0',
    'assert candidate(text1 = "psnw",text2 = "vozbbmloqjbpbprqs") == 2',
    'assert candidate(text1 = "abcxyz",text2 = "xyzabc") == 3',
    'assert candidate(text1 = "abc",text2 = "abc") == 3',
    'assert candidate(text1 = "abcdef",text2 = "zabcf") == 4',
    'assert candidate(text1 = "oxcpqrsvwf",text2 = "shmtulqrypy") == 2',
    'assert candidate(text1 = "",text2 = "") == 0',
    'assert candidate(text1 = "abcdxyz",text2 = "xyzabcd") == 4',
    'assert candidate(text1 = "aaaa",text2 = "aa") == 2',
    'assert candidate(text1 = "aggtab",text2 = "gxtxayb") == 4',
    'assert candidate(text1 = "abcxyzabc",text2 = "xyzabcxyz") == 6',
    'assert candidate(text1 = "aaaaaa",text2 = "aaaaaa") == 6',
    'assert candidate(text1 = "abacdfgdcaba",text2 = "abacdgfdcaba") == 11',
    'assert candidate(text1 = "aabccbb",text2 = "dbbcbab") == 4',
    'assert candidate(text1 = "longerstringone",text2 = "short") == 3',
    'assert candidate(text1 = "mississippi",text2 = "pississippi") == 10',
    'assert candidate(text1 = "abracadabra",text2 = "avadakedavra") == 7',
    'assert candidate(text1 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",text2 = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb") == 0',
    'assert candidate(text1 = "aquickbrownfoxjumpsoverthelazydog",text2 = "lazydog") == 7',
    'assert candidate(text1 = "abcdefghij",text2 = "acegik") == 5',
    'assert candidate(text1 = "abcdpqrs",text2 = "efghijkl") == 0',
    'assert candidate(text1 = "aaaabbbbccccddddeeeeffffgggghhhhiiii",text2 = "abcdefghi") == 9',
    'assert candidate(text1 = "xyzxyzxyz",text2 = "zyxzyxzyx") == 5',
    'assert candidate(text1 = "zyxwvutsrqponmlkjihgfedcba",text2 = "abcdefghijklmnopqrstuvwxyz") == 1',
    'assert candidate(text1 = "abcdabcdabcdabcdabcdabcdabcdabcd",text2 = "zyxwvutsrqponmlkjihgfedcba") == 4',
    'assert candidate(text1 = "abcdefghijklmnopqrstuvwxyz",text2 = "zyxwvutsrqponmlkjihgfedcba") == 1',
    'assert candidate(text1 = "longestcommonsubsequence",text2 = "shortestsub") == 7',
    'assert candidate(text1 = "mississippi",text2 = "ississippi") == 10',
    'assert candidate(text1 = "aaaaabaaaabaaaabaaaa",text2 = "bbbaabbaabbaabbaab") == 11',
    'assert candidate(text1 = "abcdeabcdeabcde",text2 = "deabcdea") == 8',
    'assert candidate(text1 = "interpersonal",text2 = "personality") == 8',
    'assert candidate(text1 = "aaaaabbbb",text2 = "ababababab") == 6',
    'assert candidate(text1 = "abcdefg",text2 = "hijklmn") == 0',
    'assert candidate(text1 = "pqrstuvwxyzabcdefghijklmno",text2 = "mnopqrstuvwxyzabcdefghijkl") == 23',
    'assert candidate(text1 = "pwwkew",text2 = "wkepwkew") == 5',
    'assert candidate(text1 = "aaaaaaab",text2 = "bbbbbaaa") == 3',
    'assert candidate(text1 = "abcdexyz",text2 = "zyxeabcd") == 4',
    'assert candidate(text1 = "abcdefghij",text2 = "0123456789abcdefghij") == 10',
    'assert candidate(text1 = "thisisaverylongstring",text2 = "shisivaverylongstring") == 19',
    'assert candidate(text1 = "acbdefgh",text2 = "bdfg") == 4',
    'assert candidate(text1 = "abc",text2 = "cba") == 1',
    'assert candidate(text1 = "abacabadabacaba",text2 = "abacabadabacab") == 14',
    'assert candidate(text1 = "abcabcabcabcabcabcabcabcabcabcabc",text2 = "abcabcabcabc") == 12',
    'assert candidate(text1 = "aaaabbbbcccc",text2 = "bbcccaabbbccc") == 8',
    'assert candidate(text1 = "aaaaabbbbbbccccccdddddeeeeeeeeeffffff",text2 = "dddddeeeeeeeeeccccccbbbbaaaaaa") == 14',
    'assert candidate(text1 = "aaaaaaaaaa",text2 = "aaaaaaaaaa") == 10',
    'assert candidate(text1 = "ab",text2 = "ba") == 1',
    'assert candidate(text1 = "aaaaaaabbbbbbbccccccdddddd",text2 = "abcde") == 4',
    'assert candidate(text1 = "ababcabcabc",text2 = "abcabcabc") == 9',
    'assert candidate(text1 = "abcdefghijk",text2 = "lmnopqrstuvwxyz") == 0',
    'assert candidate(text1 = "aabccba",text2 = "abcabcabc") == 5',
    'assert candidate(text1 = "abcdefghijlkmnopqrstuvwxyz",text2 = "zxywvutsrqponmlkjihgfedcba") == 2',
    'assert candidate(text1 = "repeatedrepeated",text2 = "repeated") == 8',
    'assert candidate(text1 = "abcdefghij",text2 = "acegikmopq") == 5',
    'assert candidate(text1 = "aabbccddeeffgghhiijj",text2 = "jjiihhggffeeddccbbaa") == 2',
    'assert candidate(text1 = "supercalifragilisticexpialidocious",text2 = "superfragilistic") == 16',
    'assert candidate(text1 = "aaaaaaabbbbbbbcccccc",text2 = "bbbbbbccccccdddddd") == 12',
    'assert candidate(text1 = "abcdefghigklmnopqrstuvwxyz",text2 = "zzzyyxxwwvvuuttrrqqppoonnmmllkkjjiihhggeeffddeeccbbbaa") == 2',
    'assert candidate(text1 = "abracadabraabracadabra",text2 = "alacazamalacazam") == 10',
    'assert candidate(text1 = "abcabcabcabcabcabcabcabcabcabc",text2 = "abcabcabc") == 9',
    'assert candidate(text1 = "abababababababababababababababab",text2 = "babababababababababababababababa") == 31',
    'assert candidate(text1 = "randomsequence",text2 = "sequence") == 8',
    'assert candidate(text1 = "abcdeabcdeabcde",text2 = "cdecdecdecde") == 9',
    'assert candidate(text1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",text2 = "mnopqrstuvwxyz") == 14',
    'assert candidate(text1 = "aaaaaaabaaaaaa",text2 = "bbbbbbbbaaaaaa") == 7',
    'assert candidate(text1 = "aaaaaaaaaaaaaaaaaaaaaaaaaa",text2 = "aaaaaaaaaaaaaaaaaaaaaaaaaa") == 26',
    'assert candidate(text1 = "abcdeabcdeabcde",text2 = "deabcdeabcdeabcdeab") == 15',
    'assert candidate(text1 = "abcdexyz",text2 = "xyzabcd") == 4',
    'assert candidate(text1 = "aaaabbbb",text2 = "bbaaaa") == 4',
    'assert candidate(text1 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",text2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == 29',
    'assert candidate(text1 = "pneumonoultramicroscopicsilicovolcanoconiosis",text2 = "ultramicroscopically") == 18',
    'assert candidate(text1 = "dynamicprogramming",text2 = "rhythmprogramming") == 13',
    'assert candidate(text1 = "aaaa",text2 = "bbbb") == 0',
    'assert candidate(text1 = "abcdpqrsabcd",text2 = "dcbapqrscba") == 6',
    'assert candidate(text1 = "longestcommonsubsequence",text2 = "shortestsubsequence") == 15',
    'assert candidate(text1 = "abacabadabacaba",text2 = "abacabadabacaba") == 15',
    'assert candidate(text1 = "findlongestcommonsubsequence",text2 = "longestsubsequence") == 18',
    'assert candidate(text1 = "xyxzyzyxyzyx",text2 = "zyzyxzyxzyzyxzyzyx") == 12',
    'assert candidate(text1 = "abcdefghijklnmopqrstuvwxyz",text2 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 25',
    'assert candidate(text1 = "abcdefghigklmnopqrstuvwxyz",text2 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 25',
    'assert candidate(text1 = "abcde",text2 = "") == 0',
    'assert candidate(text1 = "pneumonoultramicroscopicsilicovolcanoconiosis",text2 = "supercalifragilisticexpialidocious") == 17',
    'assert candidate(text1 = "papiermuh",text2 = "leidermuz") == 5',
    'assert candidate(text1 = "abcdabcdabcdabcdabcdabcdabcdabcd",text2 = "cdabcdabcdabcdabcdabcdabcdabcdabc") == 31',
    'assert candidate(text1 = "pwwkew",text2 = "wkep") == 3',
    'assert candidate(text1 = "xyxzyxyxzyx",text2 = "zyxzyxzyxzyx") == 10',
    'assert candidate(text1 = "xyzzaz",text2 = "yza") == 3',
    'assert candidate(text1 = "commonsubstring",text2 = "substring") == 9',
    'assert candidate(text1 = "abcde",text2 = "edcba") == 1',
    'assert candidate(text1 = "aabbaabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",text2 = "ababababcabcacacacaddaddaeaeaeafaafagagahaiai") == 20',
    'assert candidate(text1 = "abcdabcdabcd",text2 = "dcbaabcd") == 6',
    'assert candidate(text1 = "",text2 = "abcde") == 0',
    'assert candidate(text1 = "aaaaabaaaacaaaaadaaaaa",text2 = "aaabaaaaaaacaaaaaa") == 17',
    'assert candidate(text1 = "thisisaverylongstringthatshouldtestthelimits",text2 = "stringthatshouldtest") == 20',
    'assert candidate(text1 = "mississippi",text2 = "issipi") == 6',
    'assert candidate(text1 = "longestcommonsubsequence",text2 = "shortcommonsequence") == 16',
    'assert candidate(text1 = "abcdabcdabcd",text2 = "ddd") == 3',
    'assert candidate(text1 = "longestcommonsubsequence",text2 = "commonsubsequences") == 17',
    'assert candidate(text1 = "longstringwithnocommonsubsequence",text2 = "anotherlongstringwithoutcommonsubsequence") == 32',
    'assert candidate(text1 = "abcdefghijabcdefghijabcdefghij",text2 = "abcdefghijabcdefghij") == 20',
    'assert candidate(text1 = "lclcl",text2 = "clcl") == 4',
    'assert candidate(text1 = "thequickbrownfoxjumpsoverthelazydog",text2 = "quickbrownfoxjumpsoverthelazydo") == 31',
    'assert candidate(text1 = "longestcommonsubsequenceproblem",text2 = "programmingproblemsolving") == 12',
    'assert candidate(text1 = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz",text2 = "azbycxdwevfugthsirjqkplohnmgpfnoreqmtpslknjihgfedcba") == 17',
    'assert candidate(text1 = "abcabcabcabc",text2 = "cbacbacbacba") == 7',
    'assert candidate(text1 = "abcdeabcdeabcdeabcdeabcdeabcdeabcde",text2 = "abcdeabcde") == 10',
    'assert candidate(text1 = "xyzxyzxyzxyz",text2 = "zyxzyxzyxzyx") == 7',
    'assert candidate(text1 = "aabaaaabaaaaabaaaabaaabaaa",text2 = "abaababaabaaaaabaaabaaaaabaaaab") == 24',
    'assert candidate(text1 = "qwertypasdfghjklzxcvbnm",text2 = "qwertyuiopasdfghjklzxcvbnm") == 23',
    'assert candidate(text1 = "aabbccddeeff",text2 = "abcdefabcdef") == 7',
    'assert candidate(text1 = "abcxyzdefghijklmnopqrstuvwxyz",text2 = "xyzabcghijklmnopqrstuvwxyzdef") == 23',
    'assert candidate(text1 = "abcdabcdabcdabcd",text2 = "abcabcabcabc") == 12',
    'assert candidate(text1 = "thisisatestcase",text2 = "testingthestcase") == 11',
    'assert candidate(text1 = "abacabadabacaba",text2 = "cabacabacabaca") == 12',
    'assert candidate(text1 = "dynamicprogramming",text2 = "longestincreasingsubsequence") == 8',
    'assert candidate(text1 = "abcdefg",text2 = "xyz") == 0',
    'assert candidate(text1 = "1234567890",text2 = "0987654321") == 1',
    'assert candidate(text1 = "thisisatest",text2 = "testingthest") == 7',
    'assert candidate(text1 = "aaaaaaa",text2 = "aaaaaaaaa") == 7',
    'assert candidate(text1 = "longestcommonsubsequence",text2 = "commonsequences") == 14',
    'assert candidate(text1 = "abracadabra",text2 = "alacazam") == 5',
    'assert candidate(text1 = "mississippi",text2 = "issip") == 5',
    'assert candidate(text1 = "1234567890",text2 = "9876543210") == 2',
    'assert candidate(text1 = "thisisareallylongstringthatweneedtocheck",text2 = "thisstringislong") == 11',
    'assert candidate(text1 = "abcdabcde",text2 = "abcde") == 5',
    'assert candidate(text1 = "abcdefghij",text2 = "jihgfedcba") == 1',
    'assert candidate(text1 = "abababababababab",text2 = "babababababababa") == 15',
    'assert candidate(text1 = "mississippi",text2 = "mississsippississippi") == 11',
    'assert candidate(text1 = "aaaaabbbbbcccc",text2 = "cccbbaaaa") == 4',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().longestCommonSubsequence)
