# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for longest-increasing-path-in-a-matrix
_test_lines = [
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9]]) == 9',
    'assert candidate(matrix = [[7, 8, 9], [9, 7, 8], [8, 9, 7]]) == 3',
    'assert candidate(matrix = [[1]]) == 1',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [16, 17, 24, 23, 6], [15, 26, 25, 22, 7], [14, 21, 18, 19, 8], [13, 12, 11, 10, 9]]) == 20',
    'assert candidate(matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]) == 5',
    'assert candidate(matrix = [[9, 9, 4], [6, 6, 8], [2, 1, 1]]) == 4',
    'assert candidate(matrix = [[3, 3, 3], [3, 3, 3], [3, 3, 3]]) == 1',
    'assert candidate(matrix = [[3, 4, 5], [3, 2, 6], [2, 2, 1]]) == 4',
    'assert candidate(matrix = [[1, 3, 5], [2, 6, 4], [7, 8, 9]]) == 5',
    'assert candidate(matrix = [[1, 2, 3, 4], [12, 13, 14, 5], [11, 16, 15, 6], [10, 9, 8, 7]]) == 16',
    'assert candidate(matrix = [[1, 20, 3, 10, 5], [6, 7, 8, 9, 11], [12, 13, 14, 15, 16], [17, 18, 19, 2, 1], [21, 22, 23, 24, 25]]) == 9',
    'assert candidate(matrix = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]]) == 6',
    'assert candidate(matrix = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [11, 13, 15, 17, 19], [12, 14, 16, 18, 20]]) == 8',
    'assert candidate(matrix = [[5, 8, 3, 2], [4, 10, 9, 7], [1, 6, 13, 12], [14, 11, 16, 15]]) == 5',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8], [5, 6, 7, 8, 9]]) == 9',
    'assert candidate(matrix = [[3, 3, 3, 3, 3], [3, 2, 2, 2, 3], [3, 2, 1, 2, 3], [3, 2, 2, 2, 3], [3, 3, 3, 3, 3]]) == 3',
    'assert candidate(matrix = [[10, 20, 30, 40], [41, 42, 43, 44], [45, 46, 47, 48], [49, 50, 51, 52]]) == 7',
    'assert candidate(matrix = [[1, 2, 3, 4], [12, 13, 14, 5], [11, 16, 15, 6], [10, 9, 8, 7]]) == 16',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [20, 19, 18, 17, 16, 15, 14, 13, 12, 11], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [40, 39, 38, 37, 36, 35, 34, 33, 32, 31], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [60, 59, 58, 57, 56, 55, 54, 53, 52, 51], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70], [80, 79, 78, 77, 76, 75, 74, 73, 72, 71], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], [100, 99, 98, 97, 96, 95, 94, 93, 92, 91]]) == 100',
    'assert candidate(matrix = [[1, 2], [3, 4], [5, 6]]) == 4',
    'assert candidate(matrix = [[9, 9, 9, 9], [9, 8, 7, 8], [9, 7, 6, 7], [9, 8, 7, 6]]) == 4',
    'assert candidate(matrix = [[7, 8, 9, 10], [6, 5, 4, 11], [15, 14, 13, 12], [16, 17, 18, 19]]) == 16',
    'assert candidate(matrix = [[1, 2, 3], [8, 9, 4], [7, 6, 5]]) == 9',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6], [14, 13, 12, 11, 10, 7], [15, 16, 17, 18, 19, 8], [20, 21, 22, 23, 24, 9], [25, 26, 27, 28, 29, 30]]) == 20',
    'assert candidate(matrix = [[10, 9, 8, 7, 6], [11, 10, 9, 8, 7], [12, 11, 10, 9, 8], [13, 12, 11, 10, 9], [14, 13, 12, 11, 10]]) == 9',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [16, 17, 24, 23, 6], [15, 26, 25, 22, 7], [14, 21, 18, 19, 8], [13, 12, 11, 10, 9], [32, 31, 30, 29, 28], [27, 26, 25, 24, 33], [34, 35, 36, 37, 38]]) == 20',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]]) == 10',
    'assert candidate(matrix = [[10, 16, 15, 21, 14], [9, 11, 17, 20, 13], [8, 12, 18, 19, 12], [7, 6, 5, 4, 3], [2, 1, 0, 9, 8]]) == 13',
    'assert candidate(matrix = [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]) == 10',
    'assert candidate(matrix = [[1, 0, 7], [2, 6, 8], [3, 5, 9]]) == 8',
    'assert candidate(matrix = [[5, 4, 3, 2, 1], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [20, 19, 18, 17, 16], [21, 22, 23, 24, 25]]) == 21',
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9], [12, 11, 10]]) == 12',
    'assert candidate(matrix = [[1, 10, 9, 13, 14, 15], [2, 11, 12, 16, 17, 18], [3, 4, 5, 19, 20, 21], [6, 7, 8, 22, 23, 24], [10, 9, 8, 7, 6, 5]]) == 11',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [19, 18, 17, 16, 15, 14, 13, 12, 11, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [29, 28, 27, 26, 25, 24, 23, 22, 21, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [39, 38, 37, 36, 35, 34, 33, 32, 31, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [49, 48, 47, 46, 45, 44, 43, 42, 41, 40], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [59, 58, 57, 56, 55, 54, 53, 52, 51, 50]]) == 50',
    'assert candidate(matrix = [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]) == 1',
    'assert candidate(matrix = [[1, 3, 1, 1], [1, 4, 1, 5], [1, 2, 1, 6], [1, 7, 1, 1]]) == 3',
    'assert candidate(matrix = [[5, 4, 3, 2, 1], [4, 3, 2, 1, 5], [3, 2, 1, 5, 4], [2, 1, 5, 4, 3], [1, 5, 4, 3, 2]]) == 5',
    'assert candidate(matrix = [[7, 8, 9, 10], [10, 6, 5, 4], [3, 2, 1, 12], [14, 13, 16, 15]]) == 6',
    'assert candidate(matrix = [[9, 8, 7, 6, 5], [8, 7, 6, 5, 4], [7, 6, 5, 4, 3], [6, 5, 4, 3, 2], [5, 4, 3, 2, 1]]) == 9',
    'assert candidate(matrix = [[1, 20, 3, 4, 5], [16, 17, 24, 23, 6], [15, 26, 25, 22, 7], [14, 21, 18, 19, 8], [13, 12, 11, 10, 9]]) == 18',
    'assert candidate(matrix = [[1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]]) == 11',
    'assert candidate(matrix = [[5, 8, 5, 8], [8, 8, 8, 8], [5, 8, 5, 8], [8, 8, 8, 8]]) == 2',
    'assert candidate(matrix = [[1, 3, 5, 7, 9], [10, 8, 6, 4, 2], [11, 13, 15, 17, 19], [20, 18, 16, 14, 12]]) == 12',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]) == 21',
    'assert candidate(matrix = [[100, 99, 98, 97, 96], [95, 94, 93, 92, 91], [90, 89, 88, 87, 86], [85, 84, 83, 82, 81], [80, 79, 78, 77, 76]]) == 9',
    'assert candidate(matrix = [[10, 20, 30, 40, 50], [9, 8, 7, 6, 5], [4, 3, 2, 1, 0]]) == 11',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]) == 9',
    'assert candidate(matrix = [[10, 9, 8, 7, 6], [19, 18, 17, 16, 15], [20, 21, 22, 23, 24], [29, 28, 27, 26, 25], [30, 31, 32, 33, 34]]) == 21',
    'assert candidate(matrix = [[3, 1, 6, 5, 9, 12], [10, 18, 4, 7, 11, 14], [17, 2, 19, 8, 13, 16], [15, 24, 21, 20, 23, 22]]) == 7',
    'assert candidate(matrix = [[5, 12, 15, 18, 19, 20, 21], [4, 9, 14, 17, 22, 23, 24], [3, 8, 13, 16, 25, 26, 27], [2, 7, 10, 11, 28, 29, 30], [1, 6, 5, 4, 31, 32, 33], [0, 1, 2, 3, 34, 35, 36], [37, 38, 39, 40, 41, 42, 43]]) == 22',
    'assert candidate(matrix = [[1, 100, 1], [100, 1, 100], [1, 100, 1]]) == 2',
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9], [10, 11, 12], [15, 14, 13], [16, 17, 18], [19, 20, 21], [24, 23, 22], [25, 26, 27], [30, 29, 28]]) == 26',
    'assert candidate(matrix = [[5, 3, 2, 4, 1], [4, 8, 7, 5, 6], [3, 9, 6, 2, 8], [1, 5, 4, 3, 2], [6, 7, 8, 9, 1]]) == 8',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9], [18, 17, 16, 15, 14, 13, 12, 11, 10], [19, 20, 21, 22, 23, 24, 25, 26, 27], [36, 35, 34, 33, 32, 31, 30, 29, 28], [37, 38, 39, 40, 41, 42, 43, 44, 45], [46, 47, 48, 49, 50, 51, 52, 53, 54], [63, 62, 61, 60, 59, 58, 57, 56, 55], [64, 65, 66, 67, 68, 69, 70, 71, 72], [73, 74, 75, 76, 77, 78, 79, 80, 81]]) == 65',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]) == 10',
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9]]) == 9',
    'assert candidate(matrix = [[10, 20, 10], [20, 30, 20], [10, 20, 30], [30, 40, 30], [20, 30, 40]]) == 3',
    'assert candidate(matrix = [[7, 7, 5, 2, 9], [6, 10, 11, 12, 8], [4, 5, 9, 8, 7], [3, 1, 6, 5, 4], [2, 3, 4, 5, 1]]) == 7',
    'assert candidate(matrix = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [11, 13, 15, 17, 19], [12, 14, 16, 18, 20], [21, 23, 25, 27, 29]]) == 9',
    'assert candidate(matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]) == 5',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60], [71, 72, 73, 74, 75, 76, 77, 78, 79, 80], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]) == 13',
    'assert candidate(matrix = [[10, 11, 12, 13, 14, 15], [9, 8, 7, 6, 5, 16], [18, 17, 16, 15, 14, 13], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30]]) == 13',
    'assert candidate(matrix = [[9, 2, 3], [6, 5, 4], [3, 6, 9]]) == 6',
    'assert candidate(matrix = [[5, 6, 7, 8, 9], [4, 5, 6, 7, 8], [3, 4, 5, 6, 7], [2, 3, 4, 5, 6], [1, 2, 3, 4, 5]]) == 9',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [10, 9, 8, 7, 6], [11, 12, 13, 14, 15], [20, 19, 18, 17, 16], [21, 22, 23, 24, 25]]) == 25',
    'assert candidate(matrix = [[1, 2, 3, 4], [4, 3, 2, 1], [1, 2, 3, 4], [4, 3, 2, 1]]) == 4',
    'assert candidate(matrix = [[10, 9, 10, 11], [10, 8, 9, 10], [11, 9, 8, 9], [12, 10, 9, 8]]) == 4',
    'assert candidate(matrix = [[1, 3, 2], [6, 5, 4], [7, 8, 9], [12, 11, 10], [13, 15, 14], [18, 17, 16], [19, 21, 20], [24, 23, 22], [25, 27, 26], [30, 29, 28]]) == 22',
    'assert candidate(matrix = [[1, 15, 10], [20, 11, 16], [3, 21, 12], [4, 5, 6], [22, 23, 7], [8, 9, 13], [17, 18, 14], [24, 19, 25]]) == 10',
    'assert candidate(matrix = [[10, 6, 8], [9, 5, 7], [4, 1, 3], [12, 11, 13]]) == 4',
    'assert candidate(matrix = [[5, 8, 9, 10], [3, 4, 1, 2], [6, 7, 14, 13], [11, 12, 15, 16]]) == 6',
    'assert candidate(matrix = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [11, 13, 15, 17, 19], [12, 14, 16, 18, 20]]) == 8',
    'assert candidate(matrix = [[1, 5, 20, 11, 12, 13], [24, 23, 6, 15, 16, 17], [25, 22, 7, 14, 18, 19], [20, 9, 8, 7, 6, 5], [1, 2, 3, 4, 21, 26]]) == 11',
    'assert candidate(matrix = [[10, 16, 15, 14, 13], [9, 8, 7, 6, 5], [4, 3, 2, 1, 12], [17, 18, 19, 20, 11], [24, 23, 22, 21, 25]]) == 12',
    'assert candidate(matrix = [[10, 11, 12, 13], [9, 8, 7, 6], [14, 15, 16, 5], [17, 18, 19, 4], [20, 21, 22, 3], [23, 24, 25, 2]]) == 14',
    'assert candidate(matrix = [[9, 7, 5, 3, 1], [8, 6, 4, 2, 0], [11, 10, 9, 8, 7], [16, 15, 14, 13, 12], [17, 18, 19, 20, 21]]) == 12',
    'assert candidate(matrix = [[5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [5, 5, 5, 5, 5]]) == 1',
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9], [12, 11, 10], [13, 14, 15]]) == 15',
    'assert candidate(matrix = [[1, 2, 3, 4, 5], [4, 3, 2, 1, 6], [7, 8, 9, 10, 11], [10, 9, 8, 7, 12], [13, 14, 15, 16, 17]]) == 13',
    'assert candidate(matrix = [[1, 10, 19, 28, 37], [2, 9, 18, 27, 36], [3, 8, 17, 26, 35], [4, 7, 16, 25, 34], [5, 6, 15, 24, 33]]) == 13',
    'assert candidate(matrix = [[9, 1, 2], [3, 8, 4], [5, 6, 7]]) == 4',
    'assert candidate(matrix = [[1, 1, 1, 1, 1], [1, 2, 2, 2, 1], [1, 2, 3, 2, 1], [1, 2, 2, 2, 1], [1, 1, 1, 1, 1]]) == 3',
    'assert candidate(matrix = [[3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3]]) == 1',
    'assert candidate(matrix = [[1, 1, 1, 1, 1, 1], [1, 2, 2, 2, 2, 1], [1, 2, 3, 3, 2, 1], [1, 2, 3, 4, 3, 1], [1, 2, 3, 3, 2, 1], [1, 2, 2, 2, 2, 1], [1, 1, 1, 1, 1, 1]]) == 4',
    'assert candidate(matrix = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]) == 14',
    'assert candidate(matrix = [[1, 2, 3], [6, 5, 4], [7, 8, 9], [12, 11, 10], [13, 14, 15]]) == 15',
    'assert candidate(matrix = [[3, 1, 6], [7, 5, 2], [4, 8, 9]]) == 4',
    'assert candidate(matrix = [[1, 10, 19, 28], [2, 9, 18, 27], [3, 8, 17, 26], [4, 7, 16, 25], [5, 6, 15, 24], [14, 13, 12, 11]]) == 12',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().longestIncreasingPath)
