# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for longest-repeating-character-replacement
_test_lines = [
    "assert candidate('ABABABAB', 3) == 7",
    "assert candidate('AAAAAAAAAAAAABBBAABBCCDDEE', 5) == 20",
    "assert candidate('AABBCCDD', 2) == 4",
    "assert candidate('', 0) == 0",
    "assert candidate('A', 1) == 1",
    "assert candidate('AABAABBBCCCC', 3) == 7",
    "assert candidate('ABBBB', 0) == 4",
    "assert candidate('ABCCDEEEEE', 3) == 8",
    "assert candidate('ABAB', 2) == 4",
    "assert candidate('AABBB', 2) == 5",
    "assert candidate('ZYXWVUTSRQPONMLKJIHGFEDCBA', 25) == 26",
    "assert candidate('ABACBCAB', 2) == 4",
    "assert candidate('ABBB', 0) == 3",
    "assert candidate('ABBB', 1) == 4",
    "assert candidate('ABCDE', 1) == 2",
    "assert candidate('AABABBA', 1) == 4",
    "assert candidate('AAABBBCCC', 3) == 6",
    "assert candidate('AAAA', 2) == 4",
    "assert candidate('ABCDE', 3) == 4",
    "assert candidate('ABCDE', 2) == 3",
    "assert candidate('AABBBBCCDDDDD', 2) == 7",
    "assert candidate('ACBACBACBACBACBACBACBACBACBACBAC', 5) == 8",
    "assert candidate('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 0) == 40",
    "assert candidate('AAAAAAAAAABBBBBBBBBBCCCCCCCCCCDDDDDDDDDDD', 15) == 26",
    "assert candidate('AAAAAAAAAA', 5) == 10",
    "assert candidate('ABCABCABCABCABCABCABCABCABCABC', 10) == 16",
    "assert candidate('AAAAAAAAAAAABBBBCCCC', 10) == 20",
    "assert candidate('ABABABAB', 1) == 3",
    "assert candidate('ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ', 25) == 27",
    "assert candidate('AAABBBCCCDDDAAABBBCCCDDD', 7) == 10",
    "assert candidate('QWERTYUIOPASDFGHJKLZXCVBNM', 24) == 25",
    "assert candidate('AAAAAAAAAAAABBBCCCCCCAAAAAAAAAAA', 6) == 18",
    "assert candidate('AAABBBAABBCCDDDDDDDEEFFGGHHIIJJJKKKLLLMMMNNN', 25) == 32",
    "assert candidate('AAAAAAAAAABBBBBBBBBBBCCCCCCDDDDDDDDDDD', 25) == 36",
    "assert candidate('MMMMNNNNOOOO', 5) == 9",
    "assert candidate('AAAAAAAAABBB', 2) == 11",
    "assert candidate('AABABABABAB', 5) == 11",
    "assert candidate('ABABABABABABABABABABABABABABABABAB', 15) == 31",
    "assert candidate('ABACABAACBACABCABACBACABCABACBACABCABACBACABCABACBACAB', 20) == 36",
    "assert candidate('AAAAAAAAAABBBBBBBBCCCCCCCCCC', 10) == 20",
    "assert candidate('ABCDEABCDEABCDEABCDEABCDE', 10) == 13",
    "assert candidate('ABBCCCDDDDEEEEEFFFFFF', 6) == 12",
    "assert candidate('ABABABABABABABABAB', 10) == 18",
    "assert candidate('ABACABACABACABACABACABACABACABACABACABAC', 15) == 31",
    "assert candidate('ABABABABABABABABABABABABABABABABABABABAB', 15) == 31",
    "assert candidate('ABABABABABABABABABABABABABABABAB', 0) == 1",
    "assert candidate('AABABABABABABABABABABABABABABABAB', 5) == 12",
    "assert candidate('AABCABCABCABCABCABC', 4) == 8",
    "assert candidate('BAAAAAAAAAABAAAAAAAAAAB', 5) == 23",
    "assert candidate('AABBCCDDEEFFGG', 3) == 5",
    "assert candidate('ACACACACACACAC', 2) == 5",
    "assert candidate('AAABBBCCCDDDAAABBBCCCDDDAAABBBCCCDDD', 20) == 29",
    "assert candidate('ABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABAB', 10) == 21",
    "assert candidate('ABACABACABACABACABACABACABACABAC', 5) == 11",
    "assert candidate('AAABBBCCCDDD', 4) == 7",
    "assert candidate('XYZXYZXYZXYZXYZXYZXYZXYZ', 15) == 23",
    "assert candidate('ABCDEABCDEABCDEABCDEABCDEABCDE', 6) == 8",
    "assert candidate('ABBBABAABBBBBBBBAAABBB', 5) == 17",
    "assert candidate('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 100) == 60",
    "assert candidate('AAAAAAAAAAABBBBBBBBBBB', 10) == 21",
    "assert candidate('ABABABABAB', 5) == 10",
    "assert candidate('AAABBCCDDEEFFF', 4) == 7",
    "assert candidate('AAAAAAAAAAAAAAAAAAAAAAAB', 1) == 24",
    "assert candidate('XYZXYZXYZXYZ', 3) == 5",
    "assert candidate('ABCDEFGHIJKLMNOPQRSTUVWXYZ', 26) == 26",
    "assert candidate('ABABABABABABABAB', 8) == 16",
    "assert candidate('AAAAAAAAAAAAAAAAAAAA', 0) == 20",
    "assert candidate('AABBBCCCDDDDDEEEEFFFFFFGGGGGGHHHHHIIIJJJKKKLLLLMMMMNNNNOOOOPPPP', 30) == 36",
    "assert candidate('BBBBBBBBBBBBBBBBBBBBBAAAAAAAAAAAAA', 5) == 26",
    "assert candidate('AABABBAACCCDDDEEE', 3) == 8",
    "assert candidate('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', 0) == 106",
    "assert candidate('AAAAAAAABBBBBBBB', 0) == 8",
    "assert candidate('ABABABABABABAB', 7) == 14",
    "assert candidate('AAABBBCCCDDDEEEFFFGGGHHHIIIJJJKKKLLLMMMNNNOOOPPPQQQRRRSSSTTTUUUVVVWWWXXXXYYYYZZZZ', 50) == 54",
    "assert candidate('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB', 50) == 41",
    "assert candidate('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM', 100) == 44",
    "assert candidate('ABCABCABCABCABCABCABCABC', 15) == 23",
    "assert candidate('AABBBCCDDEE', 2) == 5",
    "assert candidate('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', 1000) == 31",
    "assert candidate('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 100) == 108",
    "assert candidate('AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ', 20) == 22",
    "assert candidate('AAABBBCCCDDD', 3) == 6",
    "assert candidate('AAAAA', 0) == 5",
    "assert candidate('AABBBCCCDDDD', 3) == 7",
    "assert candidate('AAABBBCCCDDDEEEFFF', 6) == 9",
    "assert candidate('AAAAAAAAABBBBBBBBCCCCCCCCCC', 10) == 20",
    "assert candidate('BBBAAAABBBAAAABBBAAAABBB', 5) == 13",
    "assert candidate('ABABABABABABABABABAB', 5) == 11",
    "assert candidate('ACACACACACACACACACACACAC', 5) == 11",
    "assert candidate('ABACABACABAC', 4) == 9",
    "assert candidate('ABABABABABABABABABAB', 10) == 20",
    "assert candidate('AAAAAAABBBCCCDDDDDD', 5) == 12",
    "assert candidate('BBBBAAAACCCD', 4) == 8",
    "assert candidate('QWERTYUIOPASDFGHJKLZXCVBNM', 26) == 26",
    "assert candidate('XYZXYZXYZXYZXYZXYZ', 6) == 10",
    "assert candidate('AAAAAAAAAAABBBBCCCCCDDDD', 10) == 21",
    "assert candidate('BBBBAAAACCCCDDDD', 5) == 9",
    "assert candidate('XYZXYZXYZXYZXYZXYZXYZXYZ', 20) == 24",
    "assert candidate('AAAAAAAABBBBBBBB', 3) == 11",
    "assert candidate('AAAAAAAAAAAAAAAABBB', 2) == 18",
    "assert candidate('XYZXYZXYZ', 3) == 5",
    "assert candidate('AABBCDEEFGHIJKLLMNOPQRSTUVWXYZ', 25) == 27",
    "assert candidate('AABABBAABBCCDDEEFFGG', 4) == 9",
    "assert candidate('AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ', 25) == 27",
    "assert candidate('AAABBBCCCDDD', 6) == 9",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().characterReplacement)
