# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for maximum-depth-of-binary-tree
_test_lines = [
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7])) == 3',
    'assert candidate(root = tree_node([1, 2, 2, 3, 3, None, None, 4, 4, 5, 5])) == 4',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])) == 4',
    'assert candidate(root = tree_node([1, None, 3, 2, None, 4, 5])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5])) == 3',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, None, None, None, 8])) == 4',
    'assert candidate(root = tree_node([1, 2, 2, 3, 3, None, None, 4, 4])) == 4',
    'assert candidate(root = tree_node([1, None, 2])) == 2',
    'assert candidate(root = tree_node([1, None, None, 2, None, None, 3, None, None, 4, None, None, 5])) == 1',
    'assert candidate(root = tree_node([0])) == 1',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7])) == 3',
    'assert candidate(root = tree_node([1])) == 1',
    'assert candidate(root = tree_node([])) == 0',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 8, None, 6, None, 4, None, 1, None])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10])) == 10',
    'assert candidate(root = tree_node([1, 2, 2, 3, None, None, 3, 4, None, None, 4])) == 4',
    'assert candidate(root = tree_node([3, 9, 20, 15, 7, 16, 8, 13, 14, 18, 19, 20, 21, 22, 23])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, None, None, 6, None, None, 7])) == 5',
    'assert candidate(root = tree_node([10, 5, 15, 3, 7, None, 18])) == 3',
    'assert candidate(root = tree_node([1, 2, 2, 3, 3, None, None, 4, 4, 4, 4])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, None, None, None, None, None, None, 8, 9])) == 4',
    'assert candidate(root = tree_node([1, -2, -3, 4, 5, -6, -7, 8, 9, -10, -11, -12, -13, -14, -15])) == 4',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, None, 16, None, 17, None, None, None, None, 18])) == 4',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13, None, 14, None, 15])) == 15',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9])) == 9',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, None, None, 6, 7, None, 8, None, None, None, None, None, 9])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8])) == 8',
    'assert candidate(root = tree_node([1, 2, None, 3, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13, None, 14])) == 8',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 10, 11, None, 12])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, None, None, 4, 5, None, None, 6, None, None, 7, 8, 9])) == 6',
    'assert candidate(root = tree_node([1, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8])) == 8',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 16, 17, 18, 19, None, None, 20, None])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])) == 5',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 8, None, 6, None, 4, None, 1, None, 2])) == 6',
    'assert candidate(root = tree_node([0, -1, -2, -3, -4, -5, -6])) == 3',
    'assert candidate(root = tree_node([1, 2, 2, 3, 4, 4, 3, 5, 6, None, None, 6, 5])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, None, None, None, 16])) == 5',
    'assert candidate(root = tree_node([1, None, 2, 3, None, None, 4, 5, None, None, None, 6, 7, None, None, 8, 9])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, None, 4, None, 5, None, None, 6, None, 7])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, None, None, None, None, None, None, 8, 9, 10, 11, 12, 13])) == 5',
    'assert candidate(root = tree_node([10, 5, 15, 3, 7, None, 18, None, None, None, None, 17, 20])) == 4',
    'assert candidate(root = tree_node([1, 2, 2, 3, None, None, 3, 4, 5, None, None, 4, 5])) == 5',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 8, None, 9, None, None, 10])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, 6, None, 8, 9, 10, None, None, 11, 12])) == 5',
    'assert candidate(root = tree_node([2, -1, -2, None, -3, None, -4, None, -5])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, None, None, 4, 5, None, None, 6, 7])) == 4',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13, None, 14, None, 15, None, 16, None, 17, None, 18, None, 19, None, 20, None, 21, None, 22, None, 23, None, 24, None, 25, None, 26, None, 27, None, 28, None, 29, None, 30, None, 31, None, 32])) == 32',
    'assert candidate(root = tree_node([10, 9, 20, None, None, 15, 7, 12, 13, 14, 15])) == 4',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 8, 10, 11, None, 12])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, None, 6, None, 7, None, None, 8, None, 9])) == 6',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, 6, None, 7, None, 8, None, 9])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])) == 5',
    'assert candidate(root = tree_node([3, 9, None, 15, 7, 25, 30, 35, None, None, None, 40, None, None, None, None, 45])) == 6',
    'assert candidate(root = tree_node([2, 1, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10])) == 6',
    'assert candidate(root = tree_node([1, 2, None, 3, None, 4, None, 5])) == 5',
    'assert candidate(root = tree_node([5, 4, 7, 3, None, 2, None, -1, None, 9])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, None, None, None, None, 6, 7, 8, 9])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, None, None, 3, None, None, None, None, 4])) == 2',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])) == 6',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 8, 9])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, None, 6, None, None, 7, None, 8])) == 6',
    'assert candidate(root = tree_node([1, 2, 3, None, 4, None, 5, None, None, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11])) == 9',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, None, None, None, None, 6, None, None, 7, None, None, 8, None, None, 9])) == 3',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, None, 7, 8, None, None, None, None, 9])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, None, 9, None, 10, None, 11, None, 12])) == 5',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, 1, None, 18, None, None, 21])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7])) == 7',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, None, None, None, None, None, None, None, None, 9, None, None, None, None, 10])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, None, None, 6, 7, None, 8, None, 9])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, None, None, None, None, None, None, None, None, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])) == 8',
    'assert candidate(root = tree_node([1, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13, None, 14, None, 15])) == 15',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, None, None, 16, 17, None, None, None, None, 18])) == 4',
    'assert candidate(root = tree_node([1, 2, 2, 3, None, None, 3, 4, 4, None, None, 4, 4])) == 5',
    'assert candidate(root = tree_node([0, 1, 2, 3, 4, 5, 6, None, None, 7, 8, 9, 10, None, None, 11, 12])) == 5',
    'assert candidate(root = tree_node([50, 25, 75, 10, 35, 65, 100, None, None, 30, 40, 60, 80, None, None, None, None, 90, 110])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13, None, 14, None, 15, None, 16, None, 17, None, 18, None, 19, None, 20])) == 20',
    'assert candidate(root = tree_node([0, 2, 4, 1, None, 3, -1, 5, 1, None, 6, None, 8])) == 4',
    'assert candidate(root = tree_node([3, 9, 20, 8, 10, 15, 7, 6, None, None, None, None, 18])) == 4',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])) == 6',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6])) == 6',
    'assert candidate(root = tree_node([3, 9, 20, None, None, 15, 7, None, None, 16, 17, None, None, 18, 19])) == 5',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100])) == 7',
    'assert candidate(root = tree_node([1, 2, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10])) == 6',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, None, None, 8, 9, None, None, 10, 11, None, None, 12, 13, None, None, 14, 15])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12])) == 12',
    'assert candidate(root = tree_node([1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, None, None, 5, 5])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11, None, 12, None, 13])) == 13',
    'assert candidate(root = tree_node([1, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9])) == 9',
    'assert candidate(root = tree_node([3, 9, 20, 15, 7, None, None, 8, None, None, None, None, 10])) == 5',
    'assert candidate(root = tree_node([1, None, 2, None, 3, None, 4, None, 5, None, 6, None, 7, None, 8, None, 9, None, 10, None, 11])) == 11',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, None, 8, None, 9, None, None, 10])) == 4',
    'assert candidate(root = tree_node([1, None, None, None, None, None, None])) == 1',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, 6, 7, 8, None, None, 9, None, None, 10, 11, 12, None, None, 13, 14, 15, None, None, None, None, None, None, 16])) == 6',
    'assert candidate(root = tree_node([-10, 9, 20, None, None, 15, 7])) == 3',
    'assert candidate(root = tree_node([1, 2, 3, 4, None, None, 5, 6, 7, None, None, None, None, None, None, 8, 9])) == 4',
    'assert candidate(root = tree_node([1, 2, 2, 3, 4, 4, 3])) == 3',
    'assert candidate(root = tree_node([1, 2, 3, 4, 5, None, None, 6, 7, 8, 9, None, None, None, 10, None, 11])) == 5',
    'assert candidate(root = tree_node([5, 4, 8, 11, None, 13, 4, 7, 2, None, None, 5, 1])) == 4',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().maxDepth)
