# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for minimum-window-substring
_test_lines = [
    "assert candidate('acbbaca', 'aba') == 'baca'",
    "assert candidate('aabbcc', 'abc') == 'abbc'",
    "assert candidate('aaaaaaa', 'aa') == 'aa'",
    "assert candidate('a', 'aa') == ''",
    "assert candidate('abcd', 'bd') == 'bcd'",
    "assert candidate('ab', 'b') == 'b'",
    "assert candidate('aa', 'aa') == 'aa'",
    "assert candidate('ADOBECODEBANC', 'ABC') == 'BANC'",
    "assert candidate('fgrheahtfeqcrha', 'harf') == 'fgrhea'",
    "assert candidate('aaaaaaaaaaaabbbbbcdd', 'abcdd') == 'abbbbbcdd'",
    "assert candidate('abcde', 'f') == ''",
    "assert candidate('ab', 'a') == 'a'",
    "assert candidate('abababab', 'abab') == 'abab'",
    "assert candidate('a', 'a') == 'a'",
    "assert candidate('aafffrbb', 'ffab') == 'afffrb'",
    "assert candidate('bba', 'ab') == 'ba'",
    "assert candidate('cbbbaaaaabbbcccccbbaa', 'aaabbbccc') == 'aaabbbccc'",
    "assert candidate('abcabcabc', 'abc') == 'abc'",
    "assert candidate('cabwefgewcwaefgcf', 'cae') == 'cwae'",
    "assert candidate('abcabcabc', 'aaa') == 'abcabca'",
    "assert candidate('abc', 'abc') == 'abc'",
    "assert candidate('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaaaaaaa') == 'aaaaaaaaaaaaaaaaaaaaaaaaa'",
    "assert candidate('zjwsxeyrhtlnejzjwsxeyrhtlnej', 'nejxyz') == 'nejzjwsxey'",
    "assert candidate('abcdefghijk', 'jihgfedcba') == 'abcdefghij'",
    "assert candidate('abacabadabacaba', 'abc') == 'bac'",
    "assert candidate('abcabcabcabcabcabcabcabcabcabc', 'cba') == 'abc'",
    "assert candidate('aabbccddeeffgghhii', 'abcdefghi') == 'abbccddeeffgghhi'",
    "assert candidate('aaaaaaaaaabbbbbbcccccc', 'abc') == 'abbbbbbc'",
    "assert candidate('mississippi', 'issip') == 'issip'",
    "assert candidate('zzzzzzzzzzzzzzzzz', 'zzz') == 'zzz'",
    "assert candidate('xyxzyxzyxzyxzyx', 'xzy') == 'yxz'",
    "assert candidate('abcdefg', 'zyxwvutsrqponmlkjihgfedcba') == ''",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz', 'zyxwvutsrqponmlkjihgfedcba') == 'abbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz'",
    "assert candidate('xyzxzyzxzyzzyzyxzyzyxzyzyx', 'xyzzyxzyzyzx') == 'xyzxzyzxzyzzy'",
    "assert candidate('aaabbbaaabbbccc', 'aabbcc') == 'aabbbcc'",
    "assert candidate('zzzzzzzzzzz', 'z') == 'z'",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz', 'abcdef') == 'abbccddeef'",
    "assert candidate('aabbccddeeffgghhii', 'aabbccddeeffgghhii') == 'aabbccddeeffgghhii'",
    "assert candidate('abcabcabcabcabcabcabcabcabcabcabcabc', 'aabbcc') == 'abcabc'",
    "assert candidate('bbaabbbbbaabbbbaaabbbbaaabbababababab', 'bbbbaaaa') == 'aabbbbaa'",
    "assert candidate('mississippi', 'issi') == 'issi'",
    "assert candidate('aaabbcccccccdddeee', 'abcde') == 'abbcccccccddde'",
    "assert candidate('zxcvbnmasdfghjklqwertyuiop', 'opq') == 'qwertyuiop'",
    "assert candidate('aaaaaaaaaaaabbbbbbcccccccc', 'abc') == 'abbbbbbc'",
    "assert candidate('abcabcabcabcabcabc', 'cba') == 'abc'",
    "assert candidate('xyzzxyzzxyzz', 'xyz') == 'xyz'",
    "assert candidate('aaaaaaaaaaaabbbbbbbbbbbcccccccccc', 'abc') == 'abbbbbbbbbbbc'",
    "assert candidate('xyzzzyxzyxzyxzyxzy', 'zyxzyxz') == 'xyzzzyx'",
    "assert candidate('ababababababab', 'abba') == 'abab'",
    "assert candidate('abcdabcdeabcdf', 'abcfed') == 'eabcdf'",
    "assert candidate('abababababababababab', 'aabbcc') == ''",
    "assert candidate('abcdefg', 'xyz') == ''",
    "assert candidate('aabbccddeeffgghhii', 'aabbcc') == 'aabbcc'",
    "assert candidate('ababcabcabcabcabcabcabcabcabcabcabcabc', 'abcabcabc') == 'abcabcabc'",
    "assert candidate('hellohellohello', 'lle') == 'ell'",
    "assert candidate('abcdefghijklmnopqrstuvwxyz', 'zyxwvutsrqponmlkjihgfedcba') == 'abcdefghijklmnopqrstuvwxyz'",
    "assert candidate('sadjhasjhdjahsjdhasjhadsjhsahjdahjdsjahjdhasjdhajsdhasjdhajsdjasdhasjdhsa', 'hasjdh') == 'hasjhd'",
    "assert candidate('bancbbancbbanc', 'abc') == 'banc'",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzz', 'abcdefghijklmnopqrstuvwxyz') == 'abbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyz'",
    "assert candidate('thisisaverylongstringthatweneedtolookinto', 'tin') == 'int'",
    "assert candidate('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', 'zzzzzzzz') == 'zzzzzzzz'",
    "assert candidate('bbaaaaaaabbbbcccc', 'aabbbccc') == 'aabbbbccc'",
    "assert candidate('abababababababab', 'abab') == 'abab'",
    "assert candidate('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz') == ''",
    "assert candidate('aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz', 'mnopqrstuvwxyz') == 'mnnooppqqrrssttuuvvwwxxyyz'",
    "assert candidate('qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm', 'qwertyuiopzxcvbnm') == 'zxcvbnmqwertyuiop'",
    "assert candidate('xyzzyxzyzyxzyzxzyzxzyxzyzyxzyx', 'xyz') == 'xyz'",
    "assert candidate('abcbacbacbacbacbacbacbacbacbacbacbacbacbacbac', 'acbcba') == 'abcbac'",
    "assert candidate('abccbaacz', 'abc') == 'abc'",
    "assert candidate('abracadabra', 'rac') == 'rac'",
    "assert candidate('aaaaaaaaaabbbbbbbbbbcccccccccc', 'abc') == 'abbbbbbbbbbc'",
    "assert candidate('bbaaacccaaaabbbccc', 'aabbbccc') == 'aabbbccc'",
    "assert candidate('bancancode', 'abc') == 'banc'",
    "assert candidate('abcdefgabcdefg', 'abcd') == 'abcd'",
    "assert candidate('qwertyuiopasdfghjklzxcvbnm', 'qwertyuiop') == 'qwertyuiop'",
    "assert candidate('aaaaaaaaaa', 'aaa') == 'aaa'",
    "assert candidate('ababababababababababababababababababab', 'aba') == 'aba'",
    "assert candidate('aaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc', 'abc') == 'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbc'",
    "assert candidate('abcdeffeghijk', 'efg') == 'feg'",
    "assert candidate('abcabcabcabcabc', 'cba') == 'abc'",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().minWindow)
