# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for number-of-1-bits
_test_lines = [
    'assert candidate(n = 0) == 0',
    'assert candidate(n = 4095) == 12',
    'assert candidate(n = 11) == 3',
    'assert candidate(n = 15) == 4',
    'assert candidate(n = 2147483647) == 31',
    'assert candidate(n = 32) == 1',
    'assert candidate(n = 1023) == 10',
    'assert candidate(n = 2147483645) == 30',
    'assert candidate(n = 1) == 1',
    'assert candidate(n = 65535) == 16',
    'assert candidate(n = 128) == 1',
    'assert candidate(n = 3) == 2',
    'assert candidate(n = 1099511627776) == 1',
    'assert candidate(n = 2147483646) == 30',
    'assert candidate(n = 239) == 7',
    'assert candidate(n = 53) == 4',
    'assert candidate(n = 262143) == 18',
    'assert candidate(n = 43) == 4',
    'assert candidate(n = 268435456) == 1',
    'assert candidate(n = 2047) == 11',
    'assert candidate(n = 5) == 2',
    'assert candidate(n = 549755813888) == 1',
    'assert candidate(n = 103) == 5',
    'assert candidate(n = 37) == 3',
    'assert candidate(n = 223) == 7',
    'assert candidate(n = 211) == 5',
    'assert candidate(n = 73) == 3',
    'assert candidate(n = 1022) == 9',
    'assert candidate(n = 33554432) == 1',
    'assert candidate(n = 251) == 7',
    'assert candidate(n = 181) == 5',
    'assert candidate(n = 8) == 1',
    'assert candidate(n = 193) == 3',
    'assert candidate(n = 131) == 3',
    'assert candidate(n = 2048) == 1',
    'assert candidate(n = 241) == 5',
    'assert candidate(n = 263) == 4',
    'assert candidate(n = 8191) == 13',
    'assert candidate(n = 1000000000) == 13',
    'assert candidate(n = 32768) == 1',
    'assert candidate(n = 1048575) == 20',
    'assert candidate(n = 500000000) == 13',
    'assert candidate(n = 313) == 5',
    'assert candidate(n = 167) == 5',
    'assert candidate(n = 97) == 3',
    'assert candidate(n = 317) == 6',
    'assert candidate(n = 107374182) == 14',
    'assert candidate(n = 271) == 5',
    'assert candidate(n = 8589934591) == 33',
    'assert candidate(n = 21) == 3',
    'assert candidate(n = 107) == 5',
    'assert candidate(n = 163) == 4',
    'assert candidate(n = 524288) == 1',
    'assert candidate(n = 524287) == 19',
    'assert candidate(n = 28) == 3',
    'assert candidate(n = 268435455) == 28',
    'assert candidate(n = 137) == 3',
    'assert candidate(n = 4) == 1',
    'assert candidate(n = 134217728) == 1',
    'assert candidate(n = 257) == 2',
    'assert candidate(n = 1073741823) == 30',
    'assert candidate(n = 1610612735) == 30',
    'assert candidate(n = 16777215) == 24',
    'assert candidate(n = 101) == 4',
    'assert candidate(n = 68719476735) == 36',
    'assert candidate(n = 2199023255551) == 41',
    'assert candidate(n = 89) == 4',
    'assert candidate(n = 256) == 1',
    'assert candidate(n = 1099511627775) == 40',
    'assert candidate(n = 71) == 4',
    'assert candidate(n = 151) == 5',
    'assert candidate(n = 293) == 4',
    'assert candidate(n = 41) == 3',
    'assert candidate(n = 9) == 2',
    'assert candidate(n = 83) == 4',
    'assert candidate(n = 123456789) == 16',
    'assert candidate(n = 283) == 5',
    'assert candidate(n = 8388608) == 1',
    'assert candidate(n = 79) == 5',
    'assert candidate(n = 63) == 6',
    'assert candidate(n = 269) == 4',
    'assert candidate(n = 61) == 5',
    'assert candidate(n = 999999999) == 21',
    'assert candidate(n = 49) == 3',
    'assert candidate(n = 227) == 5',
    'assert candidate(n = 47) == 5',
    'assert candidate(n = 4096) == 1',
    'assert candidate(n = 113) == 4',
    'assert candidate(n = 233) == 5',
    'assert candidate(n = 32767) == 15',
    'assert candidate(n = 511) == 9',
    'assert candidate(n = 4294967295) == 32',
    'assert candidate(n = 1879048192) == 3',
    'assert candidate(n = 4194303) == 22',
    'assert candidate(n = 191) == 7',
    'assert candidate(n = 16) == 1',
    'assert candidate(n = 4026531840) == 4',
    'assert candidate(n = 17179869183) == 34',
    'assert candidate(n = 311) == 6',
    'assert candidate(n = 179) == 5',
    'assert candidate(n = 2) == 1',
    'assert candidate(n = 3221225471) == 31',
    'assert candidate(n = 2147483644) == 29',
    'assert candidate(n = 34359738367) == 35',
    'assert candidate(n = 255) == 8',
    'assert candidate(n = 127) == 7',
    'assert candidate(n = 987654321) == 17',
    'assert candidate(n = 307) == 5',
    'assert candidate(n = 14) == 3',
    'assert candidate(n = 26) == 3',
    'assert candidate(n = 281) == 4',
    'assert candidate(n = 536870911) == 29',
    'assert candidate(n = 33554431) == 25',
    'assert candidate(n = 13) == 3',
    'assert candidate(n = 277) == 4',
    'assert candidate(n = 197) == 4',
    'assert candidate(n = 157) == 5',
    'assert candidate(n = 16383) == 14',
    'assert candidate(n = 59) == 5',
    'assert candidate(n = 173) == 5',
    'assert candidate(n = 67) == 3',
    'assert candidate(n = 134217727) == 27',
    'assert candidate(n = 64) == 1',
    'assert candidate(n = 8388607) == 23',
    'assert candidate(n = 254) == 7',
    'assert candidate(n = 4094) == 11',
    'assert candidate(n = 1024) == 1',
    'assert candidate(n = 1073741824) == 1',
    'assert candidate(n = 22) == 3',
    'assert candidate(n = 149) == 4',
    'assert candidate(n = 19) == 3',
    'assert candidate(n = 1599999999) == 23',
    'assert candidate(n = 139) == 4',
    'assert candidate(n = 109) == 5',
    'assert candidate(n = 31) == 5',
    'assert candidate(n = 229) == 5',
    'assert candidate(n = 199) == 5',
    'assert candidate(n = 7) == 3',
    'assert candidate(n = 25) == 3',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().hammingWeight)
