# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for palindromic-substrings
_test_lines = [
    'assert candidate(s = "abba") == 6',
    'assert candidate(s = "aaaaa") == 15',
    'assert candidate(s = "babad") == 7',
    'assert candidate(s = "noon") == 6',
    'assert candidate(s = "banana") == 10',
    'assert candidate(s = "aabbbaa") == 14',
    'assert candidate(s = "abc") == 3',
    'assert candidate(s = "level") == 7',
    'assert candidate(s = "") == 0',
    'assert candidate(s = "aaa") == 6',
    'assert candidate(s = "civic") == 7',
    'assert candidate(s = "rotor") == 7',
    'assert candidate(s = "racecar") == 10',
    'assert candidate(s = "a") == 1',
    'assert candidate(s = "abcdefg") == 7',
    'assert candidate(s = "zxcvbnmmlkjhgfdsapoiuytrewq") == 28',
    'assert candidate(s = "abcbaabccbaabcba") == 34',
    'assert candidate(s = "amoreinimorac") == 14',
    'assert candidate(s = "atoyota") == 10',
    'assert candidate(s = "aabbcccbbbaa") == 23',
    'assert candidate(s = "abccbaabcbaabc") == 28',
    'assert candidate(s = "rotorrotor") == 19',
    'assert candidate(s = "abracadabra") == 13',
    'assert candidate(s = "levelmadam") == 14',
    'assert candidate(s = "ab") == 2',
    'assert candidate(s = "steponnopets") == 18',
    'assert candidate(s = "noonnoon") == 16',
    'assert candidate(s = "aaaaabbbb") == 25',
    'assert candidate(s = "aaaaaaaaaa") == 55',
    'assert candidate(s = "abcddcbaabcddcba") == 32',
    'assert candidate(s = "racecarracecarracecarracecar") == 82',
    'assert candidate(s = "madaminnadammadam") == 27',
    'assert candidate(s = "xyxzyzyzyxzyzyxzyzyxzyx") == 34',
    'assert candidate(s = "noonabnoon") == 14',
    'assert candidate(s = "bbaabbccddeebbaabbccddee") == 40',
    'assert candidate(s = "qwertyuiopoiuytrewq") == 28',
    'assert candidate(s = "abccbaabccba") == 24',
    'assert candidate(s = "aba") == 4',
    'assert candidate(s = "xyzyzyzyzyzyzyzy") == 65',
    'assert candidate(s = "abacbacbacbacba") == 16',
    'assert candidate(s = "noonnoonnoonnoon") == 48',
    'assert candidate(s = "aabbccddeee") == 18',
    'assert candidate(s = "abacaba") == 12',
    'assert candidate(s = "madamracecar") == 17',
    'assert candidate(s = "rotorcarrot") == 14',
    'assert candidate(s = "abca") == 4',
    'assert candidate(s = "aabbcccbbbbaaa") == 30',
    'assert candidate(s = "aabbccddeeeeeddccbbaa") == 47',
    'assert candidate(s = "aaaaaabbbb") == 31',
    'assert candidate(s = "aabbabaabbaa") == 23',
    'assert candidate(s = "abcba") == 7',
    'assert candidate(s = "abcdcba") == 10',
    'assert candidate(s = "xyzzyxzyxzyzyxzyz") == 23',
    'assert candidate(s = "madaminnakayak") == 20',
    'assert candidate(s = "abccbaabccbaabccba") == 45',
    'assert candidate(s = "aabbccccbbaa") == 26',
    'assert candidate(s = "rotorcentralrotor") == 21',
    'assert candidate(s = "racecarracecarracecar") == 51',
    'assert candidate(s = "aabbbaaabbbaaa") == 37',
    'assert candidate(s = "xxyyyxyxx") == 17',
    'assert candidate(s = "aabbccddeeefffggghhhh") == 40',
    'assert candidate(s = "abacdfgdcabaabacdfgdcaba") == 33',
    'assert candidate(s = "racecarbanana") == 20',
    'assert candidate(s = "levelup") == 9',
    'assert candidate(s = "abcdeedcba") == 15',
    'assert candidate(s = "deeee") == 11',
    'assert candidate(s = "abaaabaaab") == 24',
    'assert candidate(s = "abbaabbaba") == 20',
    'assert candidate(s = "abcbaabcbaabcbaabcba") == 58',
    'assert candidate(s = "bcbcbcbcbcbcbc") == 56',
    'assert candidate(s = "abaaabbaaabaaa") == 35',
    'assert candidate(s = "abcababcababc") == 17',
    'assert candidate(s = "levellevel") == 19',
    'assert candidate(s = "abcdefedcba") == 16',
    'assert candidate(s = "abcdefgfedcbafedcbagfedcbafedcbagfedcba") == 45',
    'assert candidate(s = "acdcacdcacdc") == 27',
    'assert candidate(s = "zxcvbnmmnbvcxz") == 21',
    'assert candidate(s = "thisisnotapalindrome") == 23',
    'assert candidate(s = "abbaeae") == 11',
    'assert candidate(s = "aaaaaaa") == 28',
    'assert candidate(s = "levellevellevel") == 36',
    'assert candidate(s = "abcdcbaabcdcba") == 27',
    'assert candidate(s = "abccbaabc") == 15',
    'assert candidate(s = "xyzyzyxzyzyzyx") == 25',
    'assert candidate(s = "abacdfgdcabaabacdfgdcabaabacdfgdcaba") == 52',
    'assert candidate(s = "leveloneeleven") == 19',
    'assert candidate(s = "babcbabcba") == 20',
    'assert candidate(s = "zyzzyzzyzyzy") == 29',
    'assert candidate(s = "abababa") == 16',
    'assert candidate(s = "xyxzyxyzyx") == 15',
    'assert candidate(s = "abacabadabacaba") == 32',
    'assert candidate(s = "civicciviccivicciviccivic") == 85',
    'assert candidate(s = "zzzzzzzzzzzzzzzzzzzz") == 210',
    'assert candidate(s = "abcbaba") == 11',
    'assert candidate(s = "abcbabcba") == 17',
    'assert candidate(s = "deifiedrotor") == 17',
    'assert candidate(s = "noonracecarrace") == 24',
    'assert candidate(s = "civiccivic") == 19',
    'assert candidate(s = "aabbccddeeffgg") == 21',
    'assert candidate(s = "abccba") == 9',
    'assert candidate(s = "aabbccddeeff") == 18',
    'assert candidate(s = "madamimadam") == 20',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == 78',
    'assert candidate(s = "racecarannakayak") == 25',
    'assert candidate(s = "amanaplanacanalpanama") == 37',
    'assert candidate(s = "abbabababa") == 24',
    'assert candidate(s = "abcdefgfeijklmmlkjihgf") == 29',
    'assert candidate(s = "racecarracecar") == 27',
    'assert candidate(s = "noonnoonnoon") == 30',
    'assert candidate(s = "deified") == 10',
    'assert candidate(s = "bcbcbcbcb") == 25',
    'assert candidate(s = "abcdef") == 6',
    'assert candidate(s = "rotorrotorrotor") == 36',
    'assert candidate(s = "abcdedcba") == 13',
    'assert candidate(s = "noonhighnoon") == 16',
    'assert candidate(s = "abcbaabcbaabcba") == 36',
    'assert candidate(s = "rotorrotorrotorrotor") == 58',
    'assert candidate(s = "abacdfgdcaba") == 14',
    'assert candidate(s = "abbaabba") == 16',
    'assert candidate(s = "ababababab") == 30',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzz") == 141',
    'assert candidate(s = "abcddcba") == 12',
    'assert candidate(s = "aaaaabaaa") == 25',
    'assert candidate(s = "abcdefghihgfedcba") == 25',
    'assert candidate(s = "xyzyxzyzyx") == 14',
    'assert candidate(s = "xyxxyxyxxyxyxyx") == 40',
    'assert candidate(s = "xyzzzyzx") == 13',
    'assert candidate(s = "abcdefgfedcbafedcbagfedcba") == 32',
    'assert candidate(s = "aabbccddeeaabbccddee") == 30',
    'assert candidate(s = "abacdfgdcababa") == 19',
    'assert candidate(s = "civicciviccivic") == 36',
    'assert candidate(s = "aabbcc") == 9',
    'assert candidate(s = "mississippi") == 20',
    'assert candidate(s = "xyzyxyzyx") == 17',
    'assert candidate(s = "abbababaabbaba") == 28',
    'assert candidate(s = "xyxzyzyxzyzyzyxzyxzyzyzyxzyzyzyzyx") == 61',
    'assert candidate(s = "forgeeksskeegfor") == 23',
    'assert candidate(s = "bananaabababa") == 27',
    'assert candidate(s = "abcbba") == 8',
    'assert candidate(s = "zzzzzzzzzzz") == 66',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().countSubstrings)
