# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for partition-labels
_test_lines = [
    'assert candidate(s = "abcdabcde") == [8, 1]',
    'assert candidate(s = "aaaaaabbbbbccccc") == [6, 5, 5]',
    'assert candidate(s = "xyzxyzxyz") == [9]',
    'assert candidate(s = "aaaabbbbbccccc") == [4, 5, 5]',
    'assert candidate(s = "abcdabcdeabcdabcde") == [18]',
    'assert candidate(s = "abcdefghijklmnopqrstuvwxyz") == [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz") == [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]',
    'assert candidate(s = "zab") == [1, 1, 1]',
    'assert candidate(s = "a") == [1]',
    'assert candidate(s = "zabbcdefghijklmnopqrstuvwxyz") == [28]',
    'assert candidate(s = "aabbccddeee") == [2, 2, 2, 2, 3]',
    'assert candidate(s = "abcdcba") == [7]',
    'assert candidate(s = "ababababab") == [10]',
    'assert candidate(s = "zabzabc") == [6, 1]',
    'assert candidate(s = "abababab") == [8]',
    'assert candidate(s = "abcde") == [1, 1, 1, 1, 1]',
    'assert candidate(s = "ababcbacadefegdehijhklij") == [9, 7, 8]',
    'assert candidate(s = "eccbbbbdec") == [10]',
    'assert candidate(s = "abcabcdabcdeabcdefabcdefg") == [24, 1]',
    'assert candidate(s = "xyzzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx") == [66]',
    'assert candidate(s = "aaaaaaaaaabbbbbbbbccccccccddddddddeeeeeeeefffffffffghhhhhhhhiiiiiiiijjjjjjjjkkkkkkkkllllllllmmmmmmmmnnnnnnnnooooooooppppppppqqqqqqqqrrrrrrrrssssssssttttttttuuuuuuuuvvvvvvvvwwwwwwwwxxxxxxxxxyyyyyyyyzzzzzzzz") == [10, 8, 8, 8, 8, 9, 1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 8, 8]',
    'assert candidate(s = "abcdabcdeabcde") == [14]',
    'assert candidate(s = "aaaabbbbccccddddeeeeffffgggg") == [4, 4, 4, 4, 4, 4, 4]',
    'assert candidate(s = "abcadefeghijklmnopqrstuvwxyzzxywvutsrqponmlkjihgfedcba") == [54]',
    'assert candidate(s = "xyzzyxzyxzzyxzyxzyxzzyxzyxzyxzzyxzyxzzyxzyxzyxzzyxzyxzyxzzyxzyxzyxzyxzzyxzyxzyxzyx") == [82]',
    'assert candidate(s = "zzyzxzyzxzyz") == [12]',
    'assert candidate(s = "abcabcabcabcabcabcabcabcabcabc") == [30]',
    'assert candidate(s = "abacabadabacabadabacabadabacabad") == [32]',
    'assert candidate(s = "abcdexyzabcdexyzabcdexyzabcdexyz") == [32]',
    'assert candidate(s = "abcdefghfedcba") == [14]',
    'assert candidate(s = "abcdefghihgfedcbaijklmnopqrstuvutsrqponmlkjihgfedcba") == [52]',
    'assert candidate(s = "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij") == [80]',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzyxwvutsrqponmlkjihgfedcba") == [78]',
    'assert candidate(s = "mnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlkjihgfedcba") == [66]',
    'assert candidate(s = "ababcbacadeafgafghijghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == [66]',
    'assert candidate(s = "zzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbaaazzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbaaazzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbaaazzzyyxxwwvvuuttssrrqqppoonnmmllkkjjiihhggffeeddccbaaa") == [212]',
    'assert candidate(s = "abcdefgabcdefgabcdefg") == [21]',
    'assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == [70]',
    'assert candidate(s = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == [62]',
    'assert candidate(s = "abcdefghihgfedcba") == [17]',
    'assert candidate(s = "abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg") == [63]',
    'assert candidate(s = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc") == [66]',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 36]',
    'assert candidate(s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz") == [52]',
    'assert candidate(s = "xyzxyzxyzxyzxyzxyzxyzxyzxyzxyz") == [30]',
    'assert candidate(s = "mnopqrsmnopqrstuvwpqrstuv") == [25]',
    'assert candidate(s = "abcabcabcabcabcabc") == [18]',
    'assert candidate(s = "lkjihgfedcbaedcba") == [1, 1, 1, 1, 1, 1, 1, 10]',
    'assert candidate(s = "abcdefghijkabcdefghijk") == [22]',
    'assert candidate(s = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz") == [52]',
    'assert candidate(s = "abcdefedcbafedcba") == [17]',
    'assert candidate(s = "aaaaabbbbccccdddddeeeeefffffggggghhhhiiiiijjjjkkkkllllmmmmnnnnoooo") == [5, 4, 4, 5, 5, 5, 5, 4, 5, 4, 4, 4, 4, 4, 4]',
    'assert candidate(s = "mnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == [28, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]',
    'assert candidate(s = "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcbaabcdefghijklmnopqrstuvwxyz") == [78]',
    'assert candidate(s = "zabacabadefegdehijhklijkmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == [63]',
    'assert candidate(s = "mnopqrstuabcrstuvwxyzzyxwvutsrqponmlkjihgfedcba") == [47]',
    'assert candidate(s = "aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzzzzzzzzzzzzzzzzzz") == [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 18]',
    'assert candidate(s = "xyzxyzxyzxyz") == [12]',
    'assert candidate(s = "abcdefghijklmnopqrstuvwxyzyxwvutsrqponmlkjihgfedcba") == [51]',
    'assert candidate(s = "abacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbacbac") == [64]',
    'assert candidate(s = "aabababababcabcabcabcdabcdabcdabcdeabcdeabcdefabcdef") == [52]',
    'assert candidate(s = "zababzabz") == [9]',
    'assert candidate(s = "aabbccddeeffaabbccddeeff") == [24]',
    'assert candidate(s = "aaaabbbbccccddddeeeeffffgggghhhh") == [4, 4, 4, 4, 4, 4, 4, 4]',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().partitionLabels)
