# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for regular-expression-matching
_test_lines = [
    "assert candidate('aa', 'a*') == True",
    "assert candidate('aab', 'c*a*b') == True",
    "assert candidate('ab', '.*') == True",
    "assert candidate('aa', 'a') == False",
    "assert candidate('mississippi', 'mis*is*p*.') == False",
    "assert candidate('aabbccddeeff', 'a*b*c*d*e*f*f*') == True",
    "assert candidate('abababa', '(ab)*a') == False",
    "assert candidate('abcde', 'a*.*e') == True",
    "assert candidate('ababcd', 'a.*a.*d') == True",
    "assert candidate('aabbbbc', 'a*b*c') == True",
    "assert candidate('aaaaaa', 'a*a*a*a*a*a') == True",
    "assert candidate('aabb', 'ab*a*b*') == True",
    "assert candidate('abcccccaaaa', 'ab*c*a*.*') == True",
    "assert candidate('abcdef', 'abc.*f') == True",
    "assert candidate('ababab', '(ab)*') == False",
    "assert candidate('ab', 'a*b*c*d*.*e*') == True",
    "assert candidate('xaymz', 'x.*z') == True",
    "assert candidate('xaybz', 'xa*y*b*z') == True",
    "assert candidate('abcdefgh', 'a*d*fh') == False",
    "assert candidate('aaa', 'a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a*a') == True",
    "assert candidate('mississippi', 'mi*ss*is*si*p*i*') == True",
    "assert candidate('zzzz', 'z*') == True",
    "assert candidate('abcdefgh', 'a.h') == False",
    "assert candidate('ababab', '(ab)*b*') == False",
    "assert candidate('abcdefgh', 'a.*h') == True",
    "assert candidate('mississippi', 'mi.*is.*p*i') == True",
    "assert candidate('abcdefgh', 'abcdefgh') == True",
    "assert candidate('abcdefg', 'a*bc.d*efg') == True",
    "assert candidate('abcdefgh', 'a*b*c*d*e*f*g*h') == True",
    "assert candidate('abcdefgh', 'a*b*c*d*e*f*g*h*') == True",
    "assert candidate('abcd', 'a.b.c.d') == False",
    "assert candidate('aabbcc', 'a*b*c*c') == True",
    "assert candidate('abc', 'abc.') == False",
    "assert candidate('mississippi', 'm*is*i*s*i*p*i') == True",
    "assert candidate('mississippi', 'm*i*ss*i*p*i*') == False",
    "assert candidate('abcde', 'a.*de') == True",
    "assert candidate('abcdeabcde', 'abc*de*abc*de*') == True",
    "assert candidate('abcd', 'a*b*c*d*') == True",
    "assert candidate('abcde', 'a*.b*c*e*') == False",
    "assert candidate('aabbbcccddd', 'a*b*c*d*') == True",
    "assert candidate('abc', 'a.b.c') == False",
    "assert candidate('abababab', '(ab)*') == False",
    "assert candidate('hello', 'he*llo*') == True",
    "assert candidate('hello', 'he.*o') == True",
    "assert candidate('abcd', 'd*') == False",
    "assert candidate('abcde', 'a..de') == True",
    "assert candidate('abcabcabcabc', '(abc)*d') == False",
    "assert candidate('abcdabcd', 'abcd*') == False",
    "assert candidate('aabb', 'aab*b*') == True",
    "assert candidate('xyzzy', 'x*zy') == False",
    "assert candidate('abcd', 'a.*d') == True",
    "assert candidate('xxyyzz', 'x*y*z*') == True",
    "assert candidate('abc', 'a.c') == True",
    "assert candidate('xyxxyxyx', '(xy)*x') == False",
    "assert candidate('aabbbccc', 'a*b*c*') == True",
    "assert candidate('abcabcabcabc', '(abc)*') == False",
    "assert candidate('abcdef', 'a*bcdef') == True",
    "assert candidate('aaaab', 'a*b*') == True",
    "assert candidate('complex', 'c*o*m*p*l*e*x*') == True",
    "assert candidate('aaa', 'a*a') == True",
    "assert candidate('xyz', 'x*y*z*') == True",
    "assert candidate('abcdefgh', 'a.*g') == False",
    "assert candidate('abcde', 'a*b.c*d*e*') == True",
    "assert candidate('abcde', 'a*b*c*d*e*') == True",
    "assert candidate('zzzzzzzzzzzz', 'z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*z*') == True",
    "assert candidate('aabbccddeeff', 'a*b*c*d*e*f*') == True",
    "assert candidate('hello', 'he.*') == True",
    "assert candidate('abcde', 'a*b*c*d.e') == False",
    "assert candidate('aaaaabbb', 'a*b*.*') == True",
    "assert candidate('aabbccddeeffgghh', 'a*b*c*d*e*f*g*h*') == True",
    "assert candidate('abbabb', 'a*b*b*') == False",
    "assert candidate('sequence', 's.e*q*u*e*n*c*e*') == True",
    "assert candidate('abcdabcd', 'a*b*c*d*') == False",
    "assert candidate('abcdedef', 'abcd*e*f*') == False",
    "assert candidate('abcdefgh', 'a.b.c.d.e.f.g.h') == False",
    "assert candidate('mississippi', 'mi.*.pi.*') == True",
    "assert candidate('hello', 'he*ll*o') == True",
    "assert candidate('abcde', 'a*bc.e*') == True",
    "assert candidate('aaaab', 'a*a*a*a') == False",
    "assert candidate('abcde', 'a.*e') == True",
    "assert candidate('aabbb', 'a*b*b') == True",
    "assert candidate('regex', 'r.e*g*e*x*') == True",
    "assert candidate('abcdef', 'a*b*c*d*e*f*') == True",
    "assert candidate('aaaa', 'a*a*a*a') == True",
    "assert candidate('teststring', 'te*t*st*ring') == False",
    "assert candidate('abcde', 'a*b*c*de') == True",
    "assert candidate('bbbac', 'ba*ac') == False",
    "assert candidate('aabbccddeeffgg', 'a*b*c*d*e*f*g*') == True",
    "assert candidate('abcde', 'a*bc*de') == True",
    "assert candidate('xyxyxyxyxyx', 'x.y.x.y.x.y.x.y.x.y.x') == False",
    "assert candidate('a', 'a*a*a*a*') == True",
    "assert candidate('abababab', 'a*b*a*b*a*b*a*b') == True",
    "assert candidate('abcdeabcdeabcde', 'abc*de*abc*de*abc*de*f*') == True",
    "assert candidate('abbbba', 'ab*ba') == True",
    "assert candidate('teststring', 't.*st.*r.*ing') == True",
    "assert candidate('abcabc', 'abc*') == False",
    "assert candidate('abcd', 'a*b*c*d*.*') == True",
    "assert candidate('zzzzzzzzzzzz', 'z*') == True",
    "assert candidate('mississippi', 'm.*s*is*p*i*.*') == True",
    "assert candidate('abcdefgh', '.*') == True",
    "assert candidate('abcdefg', '.*f.*') == True",
    "assert candidate('abccde', 'abc*d*e') == True",
    "assert candidate('aabbbccdd', 'aa*bbb*cc*dd*') == True",
    "assert candidate('foobar', 'fo*oba*r') == True",
    "assert candidate('abcde', 'a.*f') == False",
    "assert candidate('aabb', 'a*b*b*a*') == True",
    "assert candidate('zabczabcz', 'z*abc*z*') == False",
    "assert candidate('aaaabbbb', 'a*b*b*') == True",
    "assert candidate('aabbcc', 'a*b*b*c*c*') == True",
    "assert candidate('abc', 'a*b*c*') == True",
    "assert candidate('abcdeabcdeabcde', 'abc*de*abc*de*abc*de*') == True",
    "assert candidate('abcde', 'a*c*e') == False",
    "assert candidate('xyzzaz', 'x*y*.*z*') == True",
    "assert candidate('ababab', '(ab)*b') == False",
    "assert candidate('abcdef', 'abc.def') == False",
    "assert candidate('xyx', 'x*y*x*') == True",
    "assert candidate('aaaaaa', 'a*a*a*a*') == True",
    "assert candidate('abbb', 'ab*') == True",
    "assert candidate('a', '.') == True",
    "assert candidate('abcdexyz', 'abc.*xyz') == True",
    "assert candidate('aabbcc', 'a*b*c*') == True",
    "assert candidate('leetcode', 'le.*e.*tcode') == True",
    "assert candidate('aaa', 'ab*a*c*a') == True",
    "assert candidate('abcd', 'a.d') == False",
    "assert candidate('xylophone', 'x.l*o.h.p*ne') == True",
    "assert candidate('abcde', '.*') == True",
    "assert candidate('abxyzbcd', 'ab.*bc*d') == True",
    "assert candidate('zzzzz', 'z*') == True",
    "assert candidate('aaa', 'a*a*') == True",
    "assert candidate('aaaaaaab', 'a*a*a*a*a*a*a*b') == True",
    "assert candidate('hello world', 'h.*o w*r*d') == False",
    "assert candidate('abcdefgh', 'a.*b.*c.*d.*e.*f.*g.*h') == True",
    "assert candidate('hello', 'h.l.o') == True",
    "assert candidate('abcd', 'a.b*c.d') == False",
    "assert candidate('abcdefgh', 'abcdefgh.') == False",
    "assert candidate('a', 'ab*a') == False",
    "assert candidate('patternmatching', 'pat*tern*m*atching*') == True",
    "assert candidate('abcabcabc', '(abc)*') == False",
    "assert candidate('ababab', '(ab)*ab*') == False",
    "assert candidate('abcd', 'a.c*d*') == True",
    "assert candidate('a', '.*') == True",
    "assert candidate('abcdef', 'abcd.e*f') == True",
    "assert candidate('aabb', 'a*bb') == True",
    "assert candidate('abcdefgh', 'abcdefgh*') == True",
    "assert candidate('aaa', 'a*a*a*a*a*a*') == True",
    "assert candidate('aaaaaa', 'a*a*a*a*a*a*') == True",
    "assert candidate('abab', '(ab)*') == False",
    "assert candidate('mississippi', 'mi*s*is*ip*pi*s*') == True",
    "assert candidate('aaaaab', 'a*ba*') == True",
    "assert candidate('abc', '.b.') == True",
    "assert candidate('abcd', 'a*b.c*d*') == True",
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().isMatch)
