# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for remove-nth-node-from-end-of-list
_test_lines = [
    'assert is_same_list(candidate(list_node([100, 90, 80, 70, 60]), 3), list_node([100, 90, 70, 60]))',
    'assert is_same_list(candidate(list_node([1, 2]), 1), list_node([1]))',
    'assert is_same_list(candidate(list_node([5, 4, 3, 2, 1]), 5), list_node([4, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5]), 2), list_node([1, 2, 3, 5]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 5), list_node([1, 2, 3, 4, 5, 7, 8, 9, 10]))',
    'assert candidate(list_node([1]), 1) == None',
    'assert is_same_list(candidate(list_node([1, 2, 3]), 3), list_node([2, 3]))',
    'assert is_same_list(candidate(list_node([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]), 15), list_node([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 15), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 1), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]), 5), list_node([10, 20, 30, 40, 50, 70, 80, 90, 100]))',
    'assert is_same_list(candidate(list_node([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), 1), list_node([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 3), list_node([1, 2, 3, 4, 5, 6, 7, 9, 10]))',
    'assert is_same_list(candidate(list_node([30, 20, 10]), 2), list_node([30, 10]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 29), list_node([1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 30), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]), 13), list_node([7, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60]), 1), list_node([10, 20, 30, 40, 50]))',
    'assert is_same_list(candidate(list_node([2, 3, 4, 5]), 1), list_node([2, 3, 4]))',
    'assert is_same_list(candidate(list_node([1, 0, 1, 0, 1, 0, 1, 0, 1, 0]), 2), list_node([1, 0, 1, 0, 1, 0, 1, 0, 0]))',
    'assert is_same_list(candidate(list_node([5, 10]), 2), list_node([10]))',
    'assert is_same_list(candidate(list_node([3, 2, 1]), 1), list_node([3, 2]))',
    'assert is_same_list(candidate(list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89]), 1), list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60, 70, 80, 90]), 5), list_node([10, 20, 30, 40, 60, 70, 80, 90]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 10), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]), 10), list_node([20, 30, 40, 50, 60, 70, 80, 90, 100]))',
    'assert candidate(list_node([5]), 1) == None',
    'assert is_same_list(candidate(list_node([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 29), list_node([30, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45]), 7), list_node([3, 6, 9, 12, 15, 18, 21, 24, 30, 33, 36, 39, 42, 45]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 29), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 10), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60]), 30), list_node([4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 10), list_node([2, 3, 4, 5, 6, 7, 8, 9, 10]))',
    'assert is_same_list(candidate(list_node([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]), 10), list_node([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 65, 70, 75, 80, 85, 90, 95, 100]))',
    'assert is_same_list(candidate(list_node([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 30]), 16), list_node([3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 30]))',
    'assert is_same_list(candidate(list_node([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 1), list_node([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 5), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90]), 3), list_node([100, 99, 98, 97, 96, 95, 94, 93, 91, 90]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]), 1), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]))',
    'assert is_same_list(candidate(list_node([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9]), 10), list_node([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 9, 7, 9, 3, 2, 3, 8, 4, 6, 6, 4, 3, 3, 8, 3, 2, 7, 9]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 25), list_node([1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))',
    'assert is_same_list(candidate(list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]), 28), list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]), 10), list_node([1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15]))',
    'assert is_same_list(candidate(list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1]), 29), list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 20), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([3, 5, 1, 2, 4, 7, 6, 8, 9]), 3), list_node([3, 5, 1, 2, 4, 7, 8, 9]))',
    'assert is_same_list(candidate(list_node([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]), 1), list_node([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]))',
    'assert is_same_list(candidate(list_node([1, 2]), 2), list_node([2]))',
    'assert is_same_list(candidate(list_node([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]), 28), list_node([1, 3, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), 4), list_node([1, 2, 3, 4, 5, 6, 8, 9, 10]))',
    'assert is_same_list(candidate(list_node([9, 8, 7, 6, 5, 4, 3, 2, 1]), 4), list_node([9, 8, 7, 6, 5, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 15), list_node([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 1), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))',
    'assert is_same_list(candidate(list_node([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 2), list_node([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))',
    'assert is_same_list(candidate(list_node([2, 3, 4, 5]), 4), list_node([3, 4, 5]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]), 14), list_node([10, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]))',
    'assert is_same_list(candidate(list_node([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]), 1), list_node([10, 20, 30, 40, 50, 60, 70, 80, 90]))',
    'assert is_same_list(candidate(list_node([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 29), list_node([28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]), 15), list_node([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 30), list_node([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))',
    'assert is_same_list(candidate(list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]), 25), list_node([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))',
    'assert is_same_list(candidate(list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70]), 15), list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70]))',
    'assert is_same_list(candidate(list_node([6, 2, 8, 2, 8, 4, 1, 8, 5, 2, 8, 6, 4, 3, 2, 8, 6, 2, 4, 3, 8, 2, 6, 4, 3, 2, 8, 6, 2, 4]), 20), list_node([6, 2, 8, 2, 8, 4, 1, 8, 5, 2, 6, 4, 3, 2, 8, 6, 2, 4, 3, 8, 2, 6, 4, 3, 2, 8, 6, 2, 4]))',
    'assert is_same_list(candidate(list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 20), list_node([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))',
    'assert is_same_list(candidate(list_node([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71]), 10), list_node([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 79, 78, 77, 76, 75, 74, 73, 72, 71]))',
    'assert is_same_list(candidate(list_node([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 10), list_node([9, 8, 7, 6, 5, 4, 3, 2, 1]))',
    'assert is_same_list(candidate(list_node([99, 88, 77, 66, 55, 44, 33, 22, 11]), 9), list_node([88, 77, 66, 55, 44, 33, 22, 11]))',
    'assert is_same_list(candidate(list_node([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]), 1), list_node([10, 9, 8, 7, 6, 5, 4, 3, 2]))',
    'assert is_same_list(candidate(list_node([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]), 14), list_node([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]))',
    'assert is_same_list(candidate(list_node([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]), 15), list_node([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]))',
    'assert is_same_list(candidate(list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71]), 1), list_node([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72]))',
    'assert is_same_list(candidate(list_node([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71]), 1), list_node([100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72]))',
    'assert is_same_list(candidate(list_node([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 30), list_node([0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]), 7), list_node([1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]))',
    'assert is_same_list(candidate(list_node([3, 2, 1]), 2), list_node([3, 1]))',
    'assert is_same_list(candidate(list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 2), list_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30]))',
    'assert is_same_list(candidate(list_node([1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]), 8), list_node([1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15]))',
    'assert is_same_list(candidate(list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 15), list_node([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))',
    'assert is_same_list(candidate(list_node([9, 8, 7, 6, 5, 4, 3, 2, 1]), 9), list_node([8, 7, 6, 5, 4, 3, 2, 1]))',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().removeNthFromEnd)
