# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for swim-in-rising-water
_test_lines = [
    'assert candidate([[3, 0, 8, 4], [2, 5, 1, 7], [9, 6, 10, 11], [13, 12, 14, 15]]) == 15',
    'assert candidate([[7, 1, 4, 0, 5], [2, 3, 6, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]) == 24',
    'assert candidate([[0, 1, 2, 3, 4], [24, 23, 22, 21, 5], [12, 13, 14, 15, 16], [11, 17, 18, 19, 20], [10, 9, 8, 7, 6]]) == 16',
    'assert candidate([[0, 2], [1, 3]]) == 3',
    'assert candidate([[0]]) == 0',
    'assert candidate([[3, 0, 8, 0, 0], [0, 2, 0, 0, 4], [0, 0, 1, 2, 0], [0, 9, 0, 3, 0], [7, 0, 3, 0, 5]]) == 8',
    'assert candidate([[3, 0, 8, 0, 6], [5, 0, 0, 4, 0], [7, 8, 9, 5, 0], [9, 0, 0, 9, 0], [0, 4, 6, 0, 7]]) == -1',
    'assert candidate([[1, 14, 15, 16, 17, 18], [2, 13, 24, 23, 22, 19], [3, 12, 25, 28, 27, 20], [4, 11, 26, 29, 30, 21], [5, 10, 27, 32, 31, 34], [6, 9, 8, 7, 33, 35]]) == 35',
    'assert candidate([[0, 7, 4, 10, 5, 9], [2, 1, 6, 12, 8, 11], [3, 13, 30, 18, 14, 17], [15, 19, 24, 28, 21, 22], [32, 33, 31, 25, 26, 27], [16, 20, 23, 29, 34, 35]]) == 35',
    'assert candidate([[25, 24, 23, 22, 21, 20], [19, 18, 17, 16, 15, 14], [13, 12, 11, 10, 9, 8], [7, 6, 5, 4, 3, 2], [1, 0, 26, 27, 28, 29], [35, 34, 33, 32, 31, 30]]) == 30',
    'assert candidate([[0, 3, 2, 4, 1], [7, 6, 5, 8, 9], [12, 11, 10, 13, 14], [19, 18, 17, 16, 15], [24, 23, 22, 21, 20]]) == 20',
    'assert candidate([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [19, 18, 17, 16, 15, 14, 13, 12, 11, 10], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [39, 38, 37, 36, 35, 34, 33, 32, 31, 30], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49], [59, 58, 57, 56, 55, 54, 53, 52, 51, 50], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69], [79, 78, 77, 76, 75, 74, 73, 72, 71, 70], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89], [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]]) == 90',
    'assert candidate([[5, 0, 4, 1, 2, 6], [9, 11, 13, 15, 17, 19], [8, 10, 12, 14, 16, 18], [7, 3, 23, 21, 25, 27], [6, 22, 20, 24, 26, 28], [29, 30, 31, 32, 33, 34]]) == 34',
    'assert candidate([[8, 3, 2, 6, 1, 4], [7, 5, 0, 9, 11, 13], [12, 10, 14, 15, 17, 19], [16, 18, 20, 21, 23, 25], [22, 24, 26, 27, 29, 31], [28, 30, 32, 33, 34, 35]]) == 35',
    'assert candidate([[0, 1, 2, 3, 4, 5], [16, 15, 14, 13, 12, 6], [17, 28, 27, 26, 11, 7], [18, 29, 34, 25, 10, 8], [19, 30, 33, 32, 9, 13], [20, 21, 22, 23, 24, 14]]) == 14',
    'assert candidate([[30, 29, 28, 27, 26, 25, 24], [31, 8, 7, 6, 5, 4, 23], [32, 9, 0, 1, 2, 3, 22], [33, 10, 11, 12, 13, 14, 21], [34, 19, 18, 17, 16, 15, 20], [35, 36, 37, 38, 39, 40, 41], [42, 43, 44, 45, 46, 47, 48]]) == 48',
    'assert candidate([[1, 14, 15, 16, 17], [12, 8, 9, 10, 18], [11, 7, 2, 13, 19], [10, 6, 5, 3, 20], [9, 4, 1, 0, 24]]) == 24',
    'assert candidate([[0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27], [28, 29, 30, 31, 32, 33, 34], [35, 36, 37, 38, 39, 40, 41], [42, 43, 44, 45, 46, 47, 48]]) == 48',
    'assert candidate([[13, 14, 15, 16, 17], [8, 9, 10, 11, 12], [3, 4, 5, 6, 7], [0, 1, 2, 18, 19], [20, 21, 22, 23, 24]]) == 24',
    'assert candidate([[20, 21, 22, 23, 24, 25], [19, 18, 17, 16, 15, 26], [10, 9, 8, 7, 14, 27], [11, 12, 13, 6, 5, 28], [0, 1, 2, 3, 4, 29], [30, 31, 32, 33, 34, 35]]) == 35',
    'assert candidate([[4, 0, 7, 6, 5], [3, 9, 8, 1, 2], [16, 15, 14, 13, 10], [11, 12, 17, 18, 19], [20, 21, 22, 23, 24]]) == 24',
    'assert candidate([[0, 1, 2, 3, 4, 5, 6], [35, 34, 33, 32, 31, 30, 7], [36, 19, 18, 17, 16, 29, 8], [37, 20, 7, 6, 15, 28, 9], [38, 21, 8, 5, 4, 14, 10], [39, 22, 9, 10, 11, 13, 12], [40, 41, 42, 43, 44, 45, 46]]) == 46',
    'assert candidate([[0, 5, 9, 12, 17], [3, 1, 8, 10, 18], [4, 7, 2, 15, 16], [13, 6, 11, 14, 21], [22, 20, 19, 23, 24]]) == 24',
    'assert candidate([[37, 34, 26, 25, 38, 35, 31, 27, 36], [17, 20, 33, 29, 19, 23, 22, 21, 32], [2, 18, 16, 39, 40, 24, 11, 9, 30], [3, 5, 6, 42, 14, 4, 1, 8, 7], [41, 13, 43, 15, 44, 47, 50, 48, 49], [45, 12, 46, 10, 9, 11, 28, 39, 38], [29, 31, 32, 33, 34, 35, 36, 37, 38], [39, 40, 41, 42, 43, 44, 45, 46, 47], [48, 49, 50, 1, 2, 3, 4, 5, 6]]) == 51',
    'assert candidate([[3, 17, 12, 4, 16], [13, 14, 10, 11, 8], [6, 0, 7, 5, 15], [18, 1, 19, 2, 9], [24, 22, 23, 20, 21]]) == 21',
    'assert candidate([[0, 1, 2, 3, 4, 5], [19, 18, 17, 16, 15, 6], [14, 23, 22, 21, 10, 7], [13, 24, 25, 20, 11, 8], [12, 27, 26, 29, 12, 9], [34, 33, 32, 31, 30, 35]]) == 35',
    'assert candidate([[30, 29, 28, 27, 26, 25], [24, 23, 22, 21, 20, 19], [18, 17, 16, 15, 14, 13], [12, 11, 10, 9, 8, 7], [6, 5, 4, 3, 2, 1], [0, 35, 34, 33, 32, 31]]) == 31',
    'assert candidate([[49, 48, 47, 46, 45, 44, 43, 42, 41, 40], [40, 39, 38, 37, 36, 35, 34, 33, 32, 31], [31, 30, 29, 28, 27, 26, 25, 24, 23, 22], [22, 21, 20, 19, 18, 17, 16, 15, 14, 13], [13, 12, 11, 10, 9, 8, 7, 6, 5, 4], [4, 3, 2, 1, 0, 41, 42, 43, 44, 45], [46, 47, 48, 49, 50, 51, 52, 53, 54, 55], [55, 54, 53, 52, 51, 50, 49, 48, 47, 46], [45, 44, 43, 42, 41, 56, 57, 58, 59, 60], [60, 59, 58, 57, 56, 61, 62, 63, 64, 65]]) == -1',
    'assert candidate([[25, 24, 23, 22, 21, 20], [19, 18, 17, 16, 15, 14], [13, 12, 11, 10, 9, 8], [7, 6, 5, 4, 3, 2], [1, 0, 29, 28, 27, 26], [35, 34, 33, 32, 31, 30]]) == 30',
    'assert candidate([[0, 9, 8, 7, 6, 5], [1, 2, 3, 4, 30, 31], [14, 13, 12, 11, 10, 32], [15, 16, 17, 18, 19, 33], [24, 23, 22, 21, 20, 34], [25, 26, 27, 28, 29, 35]]) == 35',
    'assert candidate([[33, 16, 21, 30, 22, 10], [18, 5, 29, 3, 24, 20], [34, 2, 31, 17, 19, 9], [15, 13, 14, 23, 28, 32], [4, 35, 8, 7, 6, 27], [1, 0, 12, 11, 26, 25]]) == 33',
    'assert candidate([[5, 24, 19, 22, 21, 6], [4, 4, 20, 17, 15, 9], [14, 10, 3, 16, 1, 11], [7, 18, 23, 13, 12, 8], [2, 0, 5, 25, 27, 26], [30, 31, 32, 33, 34, 35]]) == 35',
    'assert candidate([[8, 2, 3], [4, 7, 6], [5, 1, 0]]) == 8',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().swimInWater)
