# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for target-sum
_test_lines = [
    'assert candidate([10, 20, 30], 60) == 1',
    'assert candidate([1, 2, 3, 4, 5], 3) == 3',
    'assert candidate([0, 0, 0, 0, 0], 0) == 32',
    'assert candidate([1000], 1000) == 1',
    'assert candidate([1], 1) == 1',
    'assert candidate([1, 2, 3, 4, 5], 10) == 0',
    'assert candidate([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0) == 1024',
    'assert candidate([10, 20, 30, 40, 50], 100) == 0',
    'assert candidate([1, 2, 3, 4, 5], 3) == 3',
    'assert candidate([5, 5, 5, 5, 5], 15) == 5',
    'assert candidate([10, 20, 30, 40, 50], 15) == 0',
    'assert candidate([1, 1, 1, 1, 1], 3) == 5',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 5) == 0',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150], 1000) == 10',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], -250) == 20',
    'assert candidate([50, 50, 50, 50, 50, 50, 50, 50, 50, 50], 250) == 0',
    'assert candidate([100, 200, 300, 400, 500], 500) == 3',
    'assert candidate([20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400], 2000) == 2865',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 300) == 0',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 3000) == 0',
    'assert candidate([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], 1) == 524288',
    'assert candidate([33, 49, 84, 43, 22, 14, 15, 57, 31, 30, 83, 84, 29, 3, 23, 76, 69, 38, 83, 12], 21) == 0',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 2) == 167960',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 0) == 184756',
    'assert candidate([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10], 1) == 0',
    'assert candidate([2, 3, 5, 7, 11, 13, 17, 19], 20) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 100) == 2865',
    'assert candidate([100, 50, 25, 12, 6, 3, 1], 100) == 0',
    'assert candidate([1, 1, 2, 3, 5], 3) == 0',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200], 1000) == 2865',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 5) == 0',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 0) == 0',
    'assert candidate([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], 0) == 76',
    'assert candidate([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105], 525) == 0',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 1500) == 31',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], -5) == 39',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 15504',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 250) == 20',
    'assert candidate([50, 100, 150, 200, 250, 300, 350, 400, 450, 500], 1000) == 0',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 10) == 15504',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 250) == 20',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39], 100) == 5126',
    'assert candidate([500, 500, 500, 500, 500], 1000) == 0',
    'assert candidate([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100], 550) == 1969',
    'assert candidate([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10], 0) == 29504',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 0) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 10) == 15029',
    'assert candidate([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], 5) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1) == 40',
    'assert candidate([10, 20, 30, 40, 50, 60, 70], 100) == 6',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200], -500) == 10206',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200], 500) == 10206',
    'assert candidate([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], 20) == 0',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 5000) == 0',
    'assert candidate([999, 1000, 999, 1000, 999, 1000], 0) == 0',
    'assert candidate([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], 2) == 0',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200], 1000) == 2865',
    'assert candidate([9, 7, 5, 3, 1], 3) == 1',
    'assert candidate([25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25], 250) == 15504',
    'assert candidate([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10], 50) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 30) == 0',
    'assert candidate([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100], 500) == 2865',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 20) == 0',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 2500) == 20',
    'assert candidate([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5], 15) == 1062',
    'assert candidate([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], 5) == 0',
    'assert candidate([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9], 45) == 0',
    'assert candidate([2, 10, 3, 5, 6, 9, 8], 20) == 0',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 15) == 0',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 15) == 0',
    'assert candidate([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], 1500) == 31',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 0) == 184756',
    'assert candidate([100, 200, 300, 400, 500], 1500) == 1',
    'assert candidate([10, 10, 10, 10, 10, 10, 10, 10, 10, 10], 0) == 252',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 50) == 10206',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 25) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5) == 39',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 20) == 14326',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 550) == 1',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 0) == 15272',
    'assert candidate([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 15) == 34',
    'assert candidate([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], 10) == 21',
    'assert candidate([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200], 0) == 15272',
    'assert candidate([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40], 200) == 2865',
    'assert candidate([5, 10, 15, 20, 25, 30], 50) == 0',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().findTargetSumWays)
