# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

import random
import functools
import collections
import string
import math
import datetime

from typing import *
from functools import *
from collections import *
from itertools import *
from heapq import *
from bisect import *
from string import *
from operator import *
from math import *

inf = float('inf')

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

def list_node(values: list):
    if not values:
        return None
    head = ListNode(values[0])
    p = head
    for val in values[1:]:
        node = ListNode(val)
        p.next = node
        p = node
    return head

def is_same_list(p1, p2):
    if p1 is None and p2 is None:
        return True
    if not p1 or not p2:
        return False
    return p1.val == p2.val and is_same_list(p1.next, p2.next)

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def tree_node(values: list):
    if not values:
        return None
    root = TreeNode(values[0])
    i = 1
    queue = deque()
    queue.append(root)
    while queue:
        node = queue.popleft()
        if i < len(values) and values[i] is not None:
            node.left = TreeNode(values[i])
            queue.append(node.left)
        i += 1
        if i < len(values) and values[i] is not None:
            node.right = TreeNode(values[i])
            queue.append(node.right)
        i += 1
    return root

def is_same_tree(p, q):
    if not p and not q:
        return True
    elif not p or not q:
        return False
    elif p.val != q.val:
        return False
    else:
        return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)


# ==== YOUR SOLUTION HERE ====


# Test cases for trapping-rain-water
_test_lines = [
    'assert candidate([3, 1, 2, 1, 4, 3, 2, 1, 5]) == 11',
    'assert candidate([3, 0, 1, 3, 0, 1, 3]) == 10',
    'assert candidate([5, 4, 3, 2, 1]) == 0',
    'assert candidate([1]) == 0',
    'assert candidate([2, 0, 2]) == 2',
    'assert candidate([0, 0, 1, 0, 0, 0, 0, 0, 0]) == 0',
    'assert candidate([1, 1, 1, 1, 1, 1]) == 0',
    'assert candidate([1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 1, 2]) == 12',
    'assert candidate([1, 2, 1, 0, 1, 0, 1, 0, 1, 2, 1]) == 10',
    'assert candidate([0, 0, 0, 0, 0]) == 0',
    'assert candidate([1, 2, 3, 4, 5, 4, 3, 2, 1]) == 0',
    'assert candidate([0, 0, 0, 0]) == 0',
    'assert candidate([5, 4, 1, 2]) == 1',
    'assert candidate([3, 0, 1, 3, 0, 1, 1, 3, 2, 1, 2, 1]) == 13',
    'assert candidate([4, 2, 0, 3, 2, 5]) == 9',
    'assert candidate([3, 0, 0, 2, 0, 4]) == 10',
    'assert candidate([5, 4, 3, 2, 1, 2, 3, 4, 5]) == 16',
    'assert candidate([1, 0, 2, 0, 1, 0, 3, 1, 0, 1, 2]) == 10',
    'assert candidate([0, 2, 0, 2, 0]) == 2',
    'assert candidate([1, 0, 0, 0, 1]) == 3',
    'assert candidate([3, 0, 1, 3, 0, 1, 2, 1, 2, 1]) == 9',
    'assert candidate([0, 5, 0, 5, 0]) == 5',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 6',
    'assert candidate([1, 0, 1, 0, 1]) == 2',
    'assert candidate([1, 2, 3, 4, 5]) == 0',
    'assert candidate([2, 1, 0, 2]) == 3',
    'assert candidate([10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10]) == 81',
    'assert candidate([0, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 0]) == 36',
    'assert candidate([10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10]) == 60',
    'assert candidate([6, 4, 2, 0, 3, 2, 0, 3, 1, 4, 5, 3, 2, 7, 5, 3, 0, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1]) == 52',
    'assert candidate([10, 0, 10, 0, 10, 0, 10, 0, 10]) == 40',
    'assert candidate([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 25',
    'assert candidate([100, 80, 60, 40, 20, 0, 20, 40, 60, 80, 100]) == 500',
    'assert candidate([2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]) == 6',
    'assert candidate([0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1]) == 12',
    'assert candidate([10, 9, 8, 7, 6, 5, 6, 7, 8, 9, 10]) == 25',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1]) == 0',
    'assert candidate([0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0]) == 50',
    'assert candidate([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 8',
    'assert candidate([1, 2, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 3, 2, 1, 2, 1, 5]) == 21',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 4, 3, 2, 1, 2, 1, 0, 1]) == 13',
    'assert candidate([6, 5, 4, 3, 2, 1, 2, 3, 4, 5, 6]) == 25',
    'assert candidate([1, 8, 6, 2, 5, 4, 8, 3, 7]) == 19',
    'assert candidate([0, 1, 2, 1, 0, 1, 3, 1, 0, 1, 2, 1, 0]) == 8',
    'assert candidate([10, 1, 1, 1, 1, 1, 1, 1, 1, 10]) == 72',
    'assert candidate([0, 1, 2, 3, 4, 5, 0, 5, 4, 3, 2, 1, 0]) == 5',
    'assert candidate([1, 2, 3, 4, 5, 5, 4, 3, 2, 1, 0, 0, 0, 1, 2, 3, 4, 5]) == 35',
    'assert candidate([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]) == 0',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 4, 2, 1, 3, 2, 1, 2, 1]) == 15',
    'assert candidate([10, 9, 8, 7, 6, 5, 6, 7, 8, 9, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 25',
    'assert candidate([5, 2, 1, 2, 1, 5, 1, 2, 1, 5, 1, 2, 1, 2, 1, 5]) == 43',
    'assert candidate([2, 1, 0, 1, 2]) == 4',
    'assert candidate([10, 0, 10, 0, 10, 0, 10]) == 30',
    'assert candidate([1, 2, 3, 4, 3, 2, 1, 2, 3, 4, 3, 2, 1]) == 9',
    'assert candidate([1, 0, 2, 0, 1, 0, 1, 3, 2, 1, 2, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 42',
    'assert candidate([2, 8, 5, 5, 5, 9, 8, 9, 2]) == 10',
    'assert candidate([1, 7, 8, 8, 6, 4, 3, 1, 1, 0, 1, 7, 6, 5, 4, 3, 2, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1]) == 40',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 0',
    'assert candidate([1, 2, 3, 4, 3, 2, 1, 0, 1, 0, 1, 2, 3, 2, 1]) == 14',
    'assert candidate([5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0]) == 18',
    'assert candidate([4, 2, 0, 6, 2, 3, 8, 0, 4, 4, 1, 2, 2, 2, 3, 3, 4, 0, 1, 0, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2]) == 39',
    'assert candidate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]) == 0',
    'assert candidate([2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0]) == 18',
    'assert candidate([1, 2, 3, 0, 1, 2, 0, 1, 2, 0, 1, 2]) == 9',
    'assert candidate([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]) == 23',
    'assert candidate([0, 5, 4, 3, 2, 1, 2, 3, 4, 5, 0, 5, 4, 3, 2, 1, 2, 3, 4, 5]) == 37',
    'assert candidate([2, 1, 0, 1, 2, 1, 0, 1, 2, 1]) == 8',
    'assert candidate([0, 1, 2, 3, 2, 1, 0, 1, 2, 1, 0]) == 4',
    'assert candidate([1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0]) == 16',
    'assert candidate([9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 81',
    'assert candidate([3, 0, 1, 3, 0, 1, 2, 0, 2]) == 10',
    'assert candidate([5, 0, 3, 0, 0, 0, 2, 0, 4, 0, 0, 1, 0, 0, 5]) == 55',
    'assert candidate([3, 0, 3, 0, 3, 0, 3, 0, 3, 0]) == 12',
    'assert candidate([0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5]) == 50',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 9',
    'assert candidate([0, 2, 0, 2, 0, 3, 0, 3, 0, 2, 0, 2]) == 11',
    'assert candidate([3, 0, 1, 0, 2, 0, 1, 0, 3, 0, 2, 0, 1, 0]) == 20',
    'assert candidate([5, 2, 1, 2, 1, 5, 1, 2, 1, 2, 1, 5, 1, 2, 1, 2, 1, 5, 1, 2, 1, 2, 1, 5, 1, 2, 1, 2, 1, 5]) == 86',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 1, 2, 1, 0, 2, 1, 0]) == 13',
    'assert candidate([1, 2, 1, 2, 1, 2, 1, 2, 1, 2]) == 4',
    'assert candidate([0, 1, 2, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 3, 2, 1, 2, 1, 0, 5, 0, 4]) == 28',
    'assert candidate([0, 2, 0, 2, 0, 3, 0, 3, 0, 4]) == 10',
    'assert candidate([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 0, 5, 4, 3, 2, 1]) == 30',
    'assert candidate([1, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) == 52',
    'assert candidate([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == 6',
    'assert candidate([4, 2, 0, 3, 2, 5, 0, 5, 2, 3, 0, 2, 4, 0, 5]) == 33',
    'assert candidate([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]) == 5',
    'assert candidate([3, 2, 1, 2, 3]) == 4',
    'assert candidate([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 7',
    'assert candidate([1, 8, 6, 2, 5, 4, 8, 3, 7, 9, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 35',
    'assert candidate([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]) == 9',
    'assert candidate([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 12',
    'assert candidate([4, 2, 3, 0, 3, 5, 3, 2, 1, 5, 3, 0, 3, 5, 3, 0, 3, 5, 2, 1]) == 35',
    'assert candidate([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 5',
    'assert candidate([7, 6, 5, 4, 3, 2, 1, 2, 3, 4, 5, 6, 7]) == 36',
    'assert candidate([3, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 6',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 4, 2, 1, 0, 1, 3]) == 19',
    'assert candidate([1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1]) == 12',
    'assert candidate([1, 2, 3, 0, 1, 0, 2, 0, 3, 0, 2, 0, 1, 0, 3]) == 24',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 0',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7]) == 49',
    'assert candidate([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) == 100',
    'assert candidate([3, 0, 1, 0, 2, 0, 4, 0, 3, 0, 5, 0]) == 21',
    'assert candidate([5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5]) == 35',
    'assert candidate([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) == 0',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 3, 2, 1, 2, 1]) == 15',
    'assert candidate([1, 2, 3, 4, 3, 2, 1, 2, 3, 4, 5, 4, 3, 2, 1]) == 9',
    'assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1, 0, 1, 0, 1, 3, 2, 1, 2, 1]) == 22',
    'assert candidate([2, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]) == 13',
    'assert candidate([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]) == 6',
    'assert candidate([5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5]) == 60',
    'assert candidate([1, 3, 2, 4, 1, 3, 1, 4, 5, 2, 2, 1]) == 8',
    'assert candidate([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1]) == 12',
    'assert candidate([5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5]) == 4',
    'assert candidate([5, 2, 1, 2, 1, 5]) == 14',
    'assert candidate([0, 2, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 7',
    'assert candidate([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]) == 0',
    'assert candidate([2, 0, 2, 0, 2, 0, 2]) == 6',
    'assert candidate([0, 1, 2, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 7',
    'assert candidate([0, 2, 0, 2, 0, 3, 0, 3, 0, 2, 0, 2, 0]) == 11',
    'assert candidate([5, 5, 1, 1, 1, 5, 1, 1, 1, 5, 1, 1, 1, 5, 5]) == 36',
    'assert candidate([3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0]) == 0',
    'assert candidate([6, 4, 2, 0, 3, 0, 1, 4, 6, 2, 3, 5, 1, 0, 5, 4, 3, 2, 1, 0]) == 42',
    'assert candidate([5, 0, 3, 0, 0, 5, 0, 0, 2, 4]) == 27',
    'assert candidate([3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1]) == 16',
    'assert candidate([5, 5, 1, 7, 1, 1, 5, 2, 7, 6]) == 23',
    'assert candidate([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]) == 9',
    'assert candidate([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) == 0',
]

def check(candidate):
    passed = 0
    failed = []
    ns = dict(globals())
    ns['candidate'] = candidate
    for i, line in enumerate(_test_lines, 1):
        try:
            exec(line, ns)
            passed += 1
        except AssertionError:
            failed.append((i, line, 'wrong answer'))
        except Exception as e:
            failed.append((i, line, type(e).__name__ + ': ' + str(e)))
    total = len(_test_lines)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, line, err in failed[:10]:
            print(f'  Test #{i}: {err}')
            print(f'    {line}')
        if len(failed) > 10:
            print(f'  ... and {len(failed) - 10} more')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().trap)
